/**
 * The stock.
 *
 * 239 lines from nine works. Every one was located in a source text by
 * `scripts/harvest.mjs` or `scripts/cite-quotes.mjs` rather than recalled, and
 * 196 carry the part and chapter they sit in.
 *
 * On translators. The Russian is public domain; an English translation is its
 * own copyrighted work, and four of the five source ebooks are modern ones
 * still in copyright — McDuff, Pevear & Volokhonsky, Magarshack, and an
 * unnamed Double. Each line records whose English it is, so the provenance
 * travels with the line and a later swap to a public-domain rendering is a
 * data change rather than an excavation. Where the same passage existed in
 * two translations, the public-domain one was kept.
 *
 *
 * Every line here is Dostoevsky's. Where a line carries a `ref`, it was located
 * in the book itself — Constance Garnett's translation, Project Gutenberg
 * #2554 — by `scripts/cite-quotes.mjs`, which refuses to emit anything it
 * cannot find, so the chapter on the receipt is the chapter it came from and
 * not a chapter somebody remembered. The rest are lines in common English
 * circulation whose source text this build could not reach; they are kept
 * because they are his, and marked apart because they are not checked.
 *
 * Translations differ — he wrote in Russian, and the English wording depends
 * entirely on who was doing the carrying. The receipt says as much in its small
 * print, because a quote machine that pretends to be authoritative about
 * translation is lying to you.
 *
 * Five lines that earlier versions of this file carried have been removed: they
 * circulate widely under his name, they are not in Garnett, and nothing here
 * could place them. Two more were corrected to what the book actually says.
 */

export interface Quote {
  id: string;
  text: string;
  /** The book, as it would be printed on a secondhand spine. */
  work: string;
  year: number;
  /** Where in the book, when it was checked against the book. */
  ref?: string;
  /**
   * Whose English this is. Recorded because it matters: the Russian is public
   * domain, a translation is not, and a line's provenance should travel with
   * it rather than live in a commit message.
   */
  translator?: string;
  /** Who says it, where that is a character rather than the narrator. */
  speaker?: string;
  /** What the stall charges for it, in rupees. Cheaper is not worse. */
  price: number;
}

export const QUOTES: Quote[] = [
  {
    id: 'cp01',
    text: 'Nothing in the world is harder than speaking the truth and nothing easier than flattery.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. IV',
    price: 30,
  },
  {
    id: 'cp02',
    text: 'People with new ideas, people with the faintest capacity for saying something new, are extremely few in number, extraordinarily so in fact.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 35,
  },
  {
    id: 'cp03',
    text: 'Truth won\'t escape you, but life can be cramped.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 20,
  },
  {
    id: 'cp04',
    text: 'It is in just such stupid things clever people are most easily caught.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. VI',
    price: 25,
  },
  {
    id: 'cp05',
    text: 'The more cunning a man is, the less he suspects that he will be caught in a simple thing.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. VI',
    price: 30,
  },
  {
    id: 'cp06',
    text: 'The more cunning a man is, the simpler the trap he must be caught in.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. VI',
    price: 25,
  },
  {
    id: 'cp07',
    text: 'Everything which is _of use_ to mankind is honourable.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part V, ch. I',
    price: 20,
  },
  {
    id: 'cp08',
    text: 'There is a line in everything which it is dangerous to overstep; and when it has been overstepped, there is no return.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part IV, ch. II',
    price: 35,
  },
  {
    id: 'cp09',
    text: 'To my thinking, you, with all your virtues, are not worth the little finger of that unfortunate girl at whom you throw stones.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part IV, ch. II',
    price: 35,
  },
  {
    id: 'cp10',
    text: 'There are chance meetings with strangers that interest us from the first moment, before a word is spoken.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. II',
    price: 30,
  },
  {
    id: 'cp11',
    text: 'Honoured sir, honoured sir, you know every man ought to have at least one place where people feel for him!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. II',
    price: 30,
  },
  {
    id: 'cp12',
    text: 'Almost every criminal is subject to a failure of will and reasoning power by a childish and phenomenal heedlessness, at the very instant when prudence and caution are most essential.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. VI',
    price: 45,
  },
  {
    id: 'cp13',
    text: 'We prefer to live on other people\'s ideas, it\'s what we are used to!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 25,
  },
  {
    id: 'cp14',
    text: 'I am not worthy to love you, but to do homage to you is the duty of every man who is not a perfect beast!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 30,
  },
  {
    id: 'cp15',
    text: 'We must be patient, and much, much can be forgiven.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. IV',
    price: 20,
  },
  {
    id: 'cp16',
    text: 'The man of genius is one of millions, and the great geniuses, the crown of humanity, appear on earth perhaps one in many thousand millions.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 35,
  },
  {
    id: 'cp17',
    text: 'Break what must be broken, once for all, that\'s all, and take the suffering on oneself.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part IV, ch. IV',
    price: 30,
  },
  {
    id: 'cp18',
    text: 'To what a pitch of stupidity a man can be brought by frenzy!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. IV',
    price: 25,
  },
  {
    id: 'cp19',
    text: 'Everyone thinks of himself, and he lives most gaily who knows best how to deceive himself.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. IV',
    price: 30,
  },
  {
    id: 'cp20',
    text: 'The cellar rats will swim out, and men will curse in the rain and wind as they drag their rubbish to their upper storeys.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. VI',
    price: 35,
  },
  {
    id: 'cp21',
    text: 'If only a man is a gentleman, all the rest can be gained by talents, learning, good sense, genius.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. VIII',
    price: 30,
  },
  {
    id: 'cp22',
    text: 'In the first case you are a man, in the second you\'re no better than a bird.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 25,
  },
  {
    id: 'cp23',
    text: 'Human nature is not taken into account, it is excluded, it\'s not supposed to exist!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 25,
  },
  {
    id: 'cp24',
    text: 'A man will commit a clever murder at the risk of his life and then at once he goes drinking in a tavern.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part II, ch. VI',
    price: 30,
  },
  {
    id: 'cp25',
    text: 'The first category is always the man of the present, the second the man of the future.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 30,
  },
  {
    id: 'cp26',
    text: 'It\'s not time, but yourself that will decide that.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. II',
    price: 20,
  },
  {
    id: 'cp27',
    text: 'I know that you don\'t believe it, but indeed, life will bring you through.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part VI, ch. II',
    price: 25,
  },
  {
    id: 'cp28',
    text: 'You must forgive in the hour of death, that\'s a sin, madam, such feelings are a great sin.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part II, ch. VII',
    price: 30,
  },
  {
    id: 'cp29',
    text: 'You must look things straight in the face at last, and not weep like a child and cry that God won\'t allow it.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part IV, ch. IV',
    price: 30,
  },
  {
    id: 'cp30',
    text: 'More than that, we become casuists, we learn to be Jesuitical and for a time maybe we can soothe ourselves, we can persuade ourselves that it is one\'s duty for a good object.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. IV',
    price: 45,
  },
  {
    id: 'cp31',
    text: 'From which it follows that, if society is normally organised, all crime will cease at once, since there will be nothing to protest against and all men will become righteous in one instant.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 45,
  },
  {
    id: 'cp32',
    text: 'The idea is simple, but unhappily it has been a long time reaching us, being hindered by idealism and sentimentality.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part II, ch. V',
    price: 35,
  },
  {
    id: 'cp33',
    text: 'That\'s man\'s one privilege over all creation.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 20,
  },
  {
    id: 'cp34',
    text: 'Taking a new step, uttering a new word is what they fear most.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. I',
    price: 25,
  },
  {
    id: 'cp35',
    text: 'Pain and suffering are always inevitable for a large intelligence and a deep heart.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. V',
    price: 25,
  },
  {
    id: 'cp36',
    text: 'To go wrong in one\'s own way is better than to go right in someone else\'s.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part III, ch. I',
    price: 25,
  },
  {
    id: 'cp37',
    text: 'Man grows used to everything, the scoundrel.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part I, ch. II',
    price: 20,
  },
  {
    id: 'cp38',
    text: 'I did not bow down to you, I bowed down to all the suffering of humanity.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part IV, ch. IV',
    price: 25,
  },
  {
    id: 'q12',
    text: 'The mystery of human existence lies not in just staying alive, but in finding something to live for.',
    work: 'The Brothers Karamazov',
    year: 1880,
    price: 40,
  },
  {
    id: 'q13',
    text: 'Above all, do not lie to yourself. The man who lies to himself and listens to his own lie comes to a point where he cannot distinguish the truth within him, or around him.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Father Zosima',
    price: 55,
  },
  {
    id: 'q14',
    text: 'What is hell? I maintain that it is the suffering of being unable to love.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Father Zosima',
    price: 35,
  },
  {
    id: 'q15',
    text: 'Love in action is a harsh and dreadful thing compared with love in dreams.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Father Zosima',
    price: 35,
  },
  {
    id: 'q16',
    text: 'Beauty is mysterious as well as terrible. God and the devil are fighting there, and the battlefield is the heart of man.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Dmitri',
    price: 50,
  },
  {
    id: 'q17',
    text: 'Everyone is really responsible to all men for all men and for everything.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Father Zosima',
    price: 30,
  },
  {
    id: 'q18',
    text: 'Men reject their prophets and slay them, but they love their martyrs and honour those whom they have slain.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'The Grand Inquisitor',
    price: 45,
  },
  {
    id: 'q19',
    text: 'I think the devil does not exist, but man has created him, he has created him in his own image and likeness.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'Ivan',
    price: 40,
  },
  {
    id: 'q20',
    text: 'I am a sick man. I am a spiteful man. I am an unattractive man.',
    work: 'Notes from Underground',
    year: 1864,
    speaker: 'the Underground Man',
    price: 25,
  },
  {
    id: 'q21',
    text: 'Man only likes to count his troubles; he does not calculate his happiness.',
    work: 'Notes from Underground',
    year: 1864,
    price: 30,
  },
  {
    id: 'q22',
    text: 'Man is sometimes extraordinarily, passionately, in love with suffering.',
    work: 'Notes from Underground',
    year: 1864,
    price: 30,
  },
  {
    id: 'q23',
    text: 'Every man has reminiscences which he would not tell to everyone, but only to his friends. He has other matters in his mind which he would not reveal even to his friends, but only to himself, and that in secret.',
    work: 'Notes from Underground',
    year: 1864,
    price: 60,
  },
  {
    id: 'q24',
    text: 'I say let the world go to hell, but I should always have my tea.',
    work: 'Notes from Underground',
    year: 1864,
    price: 20,
  },
  {
    id: 'q25',
    text: 'To be too conscious is an illness — a real thoroughgoing illness.',
    work: 'Notes from Underground',
    year: 1864,
    price: 30,
  },
  {
    id: 'q26',
    text: 'Beauty will save the world.',
    work: 'The Idiot',
    year: 1869,
    speaker: 'reported of Prince Myshkin',
    price: 20,
  },
  {
    id: 'q27',
    text: 'It is life that matters, nothing but life — the process of discovering, the everlasting and perpetual process, not the discovery itself at all.',
    work: 'The Idiot',
    year: 1869,
    price: 45,
  },
  {
    id: 'q28',
    text: 'Compassion is the chief law of human existence.',
    work: 'The Idiot',
    year: 1869,
    speaker: 'Prince Myshkin',
    price: 25,
  },
  {
    id: 'q29',
    text: 'What if I were not to die! What if life were given back to me — what infinity! And it would all be mine! I would turn every minute into an age.',
    work: 'The Idiot',
    year: 1869,
    speaker: 'Prince Myshkin',
    price: 40,
  },
  {
    id: 'q32',
    text: 'One can know a man from his laugh, and if you like a man’s laugh before you know anything of him, you may confidently say that he is a good man.',
    work: 'The Adolescent',
    year: 1875,
    price: 45,
  },
  {
    id: 'q33',
    text: 'If you want to be respected by others, the great thing is to respect yourself. Only by that, only by self-respect, will you compel others to respect you.',
    work: 'The Insulted and Humiliated',
    year: 1861,
    price: 45,
  },
  {
    id: 'q34',
    text: 'The degree of civilisation in a society can be judged by entering its prisons.',
    work: 'The House of the Dead',
    year: 1862,
    price: 35,
  },
  {
    id: 'q35',
    text: 'Man is a creature that can get accustomed to anything, and I think that is the best definition of him.',
    work: 'The House of the Dead',
    year: 1862,
    price: 35,
  },
  {
    id: 'q36',
    text: 'Money is coined liberty, and so it is ten times dearer to a man who is deprived of freedom.',
    work: 'The House of the Dead',
    year: 1862,
    price: 35,
  },
  {
    id: 'q37',
    text: 'Man is a mystery. It must be unravelled, and if you spend your whole life unravelling it, do not say that you have wasted time.',
    work: 'Letter to his brother Mikhail',
    year: 1839,
    price: 50,
  },
  {
    id: 'q38',
    text: 'Without a firm idea of what he lives for, man will not accept life and will rather destroy himself than remain on this earth.',
    work: 'Demons',
    year: 1872,
    price: 45,
  },
  {
    id: 'q39',
    text: 'Nothing has ever been more insupportable for a man and a human society than freedom.',
    work: 'The Brothers Karamazov',
    year: 1880,
    speaker: 'The Grand Inquisitor',
    price: 40,
  },
  {
    id: 'q40',
    text: 'A man who bows down to nothing can never bear the burden of himself.',
    work: 'Demons',
    year: 1872,
    price: 35,
  },
  {
    id: 'wn01',
    text: 'My God, a whole moment of happiness! Is that too little for the whole of a man\'s life?',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 30,
  },
  {
    id: 'wn02',
    text: 'I am a dreamer; I have so little real life that I look upon such moments as this now, as so rare, that I cannot help going over such moments again in my dreams.',
    work: 'White Nights',
    year: 1848,
    ref: '',
    price: 40,
  },
  {
    id: 'wn03',
    text: 'The dreamer — if you want an exact definition — is not a human being, but a creature of an intermediate sort.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 30,
  },
  {
    id: 'wn04',
    text: 'Some more years will pass, and after them will come gloomy solitude; then will come old age trembling on its crutch, and after it misery and desolation.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 40,
  },
  {
    id: 'wn05',
    text: 'I will treasure that memory: I will be true to it, I will not betray it, I will not betray my heart: it is too constant.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 35,
  },
  {
    id: 'wn06',
    text: 'One seems longing to pour out one\'s whole heart; one wants everything to be gay, everything to be laughing.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 30,
  },
  {
    id: 'wn07',
    text: 'His imagination is again stirred and at work, and again a new world, a new fascinating life opens vistas before him.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 35,
  },
  {
    id: 'wn08',
    text: 'I am oppressed by such strange thoughts, such gloomy sensations; questions still so obscure to me are crowding into my brain — and I seem to have neither power nor will to settle them.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 45,
  },
  {
    id: 'wn09',
    text: 'Do you know that, maybe, I shall leave off grieving over the crime and sin of my life? for such a life is a crime and a sin.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    price: 35,
  },
  {
    id: 'wn10',
    text: 'It was a wonderful night, such a night as is only possible when we are young, dear reader.',
    work: 'White Nights',
    year: 1848,
    ref: '',
    price: 30,
  },
  {
    id: 'ep001',
    text: 'Nature isn\'t taken into consideration, nature is banished, nature is not supposed to exist.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep002',
    text: 'Every decent man of our time is and must be a coward and a slave.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. I',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep003',
    text: 'Love – is God\'s mystery, and should be hidden from all other eyes, whatever happens.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VI',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep004',
    text: 'There are many women who the more they love their husbands, the more ready they are to quarrel with them.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VI',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep005',
    text: 'I have beheld it—the Truth—it is not as though I had invented it with my mind: I have beheld it, I have beheld it, and the living image of it has filled my soul for ever.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep006',
    text: 'Man needs only independent wanting, whatever this independence may cost and wherever it may lead.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep007',
    text: 'There are also such as he will reveal not even to friends, but only to himself, and that in secret.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. XI',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep008',
    text: 'Life is good even in sorrow, it\'s good to live in the world, no matter how.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VI',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep009',
    text: 'When a man is poor he may still preserve the nobility of his inborn feelings, but when he\'s destitute he never ever can.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part one, ch. II',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep010',
    text: 'If you push a man away you\'ll never set him on the right path, and the same is even truer of a boy.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part two, ch. IV',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep011',
    text: 'To talk nonsense in one\'s own way is almost better than to talk a truth that\'s someone else\'s; in the first instance you behave like a human being, while in the second you are merely being a parrot!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. I',
    translator: 'McDuff',
    price: 45,
  },
  {
    id: 'ep012',
    text: 'People of genius are born one out of millions, while the great geniuses, the achievers of humanity, only come into being after many thousands of millions of people have passed through the earth.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 45,
  },
  {
    id: 'ep013',
    text: 'Everything proceeds from the environment, and a man is nothing on his own.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part five, ch. I',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep014',
    text: 'There aren\'t many places where there are as many gloomy, harsh and strange influences on the soul of man as there are in St Petersburg.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. III',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep015',
    text: 'There is nothing in the world more difficult than plain speaking, and nothing easier than flattery.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. IV',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep016',
    text: 'Everyone must look out for himself, and the best time is had by those who\'re best able to deceive themselves.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. IV',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep017',
    text: 'There are certain things in a man\'s past which he does not divulge to everybody but, perhaps, only to his friends.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep018',
    text: 'We have lost touch so much that occasionally we cannot help feeling a sort of disgust with "real life," and that is why we are so angry when people remind us of it.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep019',
    text: 'Truth dawns upon the unhappy man in a form that is both clear and definite, at least so far as he himself is concerned.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep020',
    text: 'If you want to pass judgment on a man, you must first know all the facts about him.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep021',
    text: 'There are only people in the world, and all around them is silence—that\'s what the earth is!',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep022',
    text: 'I have beheld it in all its glory and I cannot believe that it cannot exist among men.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep023',
    text: 'There are people, gentlemen, who do not like deviousness and who wear a mask only at masked balls.',
    work: 'The Double',
    year: 1846,
    ref: 'Three',
    translator: 'unnamed',
    price: 30,
  },
  {
    id: 'ep024',
    text: 'There are people who do not regard acquiring the ability to polish a parquet floor with their shoes as the true purpose of human life.',
    work: 'The Double',
    year: 1846,
    ref: 'Three',
    translator: 'unnamed',
    price: 35,
  },
  {
    id: 'ep025',
    text: 'Nature doesn\'t ask your permission; it doesn\'t care about your wishes, or whether you like its laws or not.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. III',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep026',
    text: 'I believe in this, I will answer for this, because the whole human enterprise seems indeed to consist in man\'s proving to himself every moment that he is a man and not a sprig!',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. VIII',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep027',
    text: 'Man loves creating and the making of roads, that is indisputable.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep028',
    text: 'It is in fact worth noting that the majority of those benefactors and guiding spirits of mankind were particularly fearsome blood-letters.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep029',
    text: 'It\'s over utterly trivial things like that that clever people are caught.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. VI',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep030',
    text: 'If that were so, people would be able to do one another nothing but harm in this world, and not even possess the right to do a single crumb of good, merely because of some empty accepted convention.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part four, ch. I',
    translator: 'McDuff',
    price: 45,
  },
  {
    id: 'ep031',
    text: 'A dreamer—if you must know its exact definition—is not a man, but a sort of creature of the neuter gender.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep032',
    text: 'It is not with indifference that he looks at the sunset which is slowly fading on the cold Petersburg sky.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep033',
    text: 'It is as though they wanted to pour their hearts into the heart of another human being, as though they wanted the whole world to be gay and laugh with them.',
    work: 'White Nights',
    year: 1848,
    ref: 'Third night',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep034',
    text: 'It is positively immoral, indecent, and vulgar to live more than forty years.',
    work: 'Notes from Underground',
    year: 1864,
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep035',
    text: 'I am exaggerating because I know, as well as twice-two, that it is not the dark cellar that is better, but something else, something else altogether, something I long for but cannot find.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep036',
    text: 'I can put it even this way: the more decent a man is, the larger will the number of such things be.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep037',
    text: 'People say work makes man better and more honest.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep038',
    text: 'We are stillborn, and for a long time we have been begotten not by living fathers, and that\'s just what we seem to like more and more.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep039',
    text: 'It is said that people standing on a great height seem to be irresistibly drawn into the abyss.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep040',
    text: 'Queerness is not a vice in a man; on the contrary, it often exercises a powerful attraction on a woman\'s imagination.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep041',
    text: 'We know it and we are sorry for it, and we torment ourselves for it, and inflict pain upon ourselves, and punish ourselves more perhaps than the merciful Judge who will judge us and whose name we do not know.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 55,
  },
  {
    id: 'ep042',
    text: 'I have beheld it and I know that people can be happy and beautiful without losing their ability to live on earth.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep043',
    text: 'I am a man apart, and as far as I can see, I don\'t depend on anybody.',
    work: 'The Double',
    year: 1846,
    ref: 'Two',
    translator: 'unnamed',
    price: 25,
  },
  {
    id: 'ep044',
    text: 'I am now forty years old, and, after all, forty years – is a whole lifetime; after all, it\'s the most extreme old age.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground',
    translator: 'Pevear & Volokhonsky',
    price: 35,
  },
  {
    id: 'ep045',
    text: 'My God, but what do I care about the laws of nature and arithmetic if for some reason these laws and two times two is four are not to my liking?',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. III',
    translator: 'Pevear & Volokhonsky',
    price: 40,
  },
  {
    id: 'ep046',
    text: 'At least man has always somehow feared this two times two is four, and I fear it even now.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep047',
    text: 'Suffering – why, this is the sole cause of consciousness.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 20,
  },
  {
    id: 'ep048',
    text: 'In every man\'s memories there are such things as he will reveal not to everyone, but perhaps only to friends.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. XI',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep049',
    text: 'A developed and decent man cannot be vain without a boundless exactingness towards himself and without despising himself at moments to the point of hatred.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. I',
    translator: 'Pevear & Volokhonsky',
    price: 40,
  },
  {
    id: 'ep050',
    text: 'To deserve this love a man would be ready to lay down his soul, to face death.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep051',
    text: 'There are some encounters, even with people who are complete strangers to us, in which we begin to take an interest right from the very first glance, suddenly, before we have uttered a word.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part one, ch. II',
    translator: 'McDuff',
    price: 45,
  },
  {
    id: 'ep052',
    text: 'One death to a hundred lives – I mean, there\'s arithmetic for you!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part one, ch. VI',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep053',
    text: 'I mean, it\'s not the fact that they\'re lying; one can always forgive a man for telling lies; lying\'s a harmless activity, because it leads to the truth.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part two, ch. IV',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep054',
    text: 'There are some who reject children altogether, as they do all that suggests the family.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part five, ch. I',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep055',
    text: 'Whoever is able to spit on most things, they consider their law-giver, and the person who takes the most liberties of all is the one who is most in the right!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part five, ch. IV',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep056',
    text: 'In place of dialectics life had arrived, and in his consciousness something of a wholly different nature must now work towards fruition.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. II',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep057',
    text: 'Sitting beside you and talking to you now, I feel terrified to think of the future, for in my future I can discern nothing but more loneliness, more of this stale and unprofitable life.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep058',
    text: 'It is as though we were all afraid that our feelings would be hurt if we revealed them too soon.',
    work: 'White Nights',
    year: 1848,
    ref: 'Third night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep059',
    text: 'For to start being active you must first of all be completely composed in mind and never be in doubt.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'V',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep060',
    text: 'As a matter of fact, gentlemen, the reason why I consider myself a clever man is simply because I could never in my life finish anything I\'d started.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'V',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep061',
    text: 'All man wants is an absolutely free choice, however dear that freedom may cost him and wherever it may lead him to.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VII',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep062',
    text: 'We know that many of these altruists, sooner or later, towards the end of their lives, were untrue to themselves, committing some folly, sometimes indeed of almost indecent nature.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VIII',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep063',
    text: 'Man likes to create and to clear paths—that is undeniable.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep064',
    text: 'You need not even look up world history to prove that; ask yourself, if you are a man and have lived at all.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep065',
    text: 'I am convinced that fellows like me who live in dark cellars must be kept under restraint.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep066',
    text: 'Who knows, maybe I really had never been fastidious, but just acquired a taste for appearing fastidious out of books.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep067',
    text: 'Fathers always love their daughters more than mothers do.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VI',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep068',
    text: 'To get that peace of mind, to make sure that no one worried me, I\'d sell the whole world for a farthing.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep069',
    text: 'I cannot live without feeling that I have someone completely in my power, that I am free to tyrannise over some human being.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep070',
    text: 'We even find it hard to be men, men of real flesh and blood, our own flesh and blood.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep071',
    text: 'Men condemned to death, I\'m told, sleep very soundly indeed on the last night.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep072',
    text: 'For once you have recognised the truth and seen it, you know it is the one and only truth and that there can be no other, whether you are asleep or awake.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'II',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep073',
    text: 'I will not and I cannot believe that evil is the normal condition among men.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep074',
    text: 'I am a little man, you know yourself; but, luckily for me, I am not sorry to be a little man.',
    work: 'The Double',
    year: 1846,
    ref: 'Two',
    translator: 'unnamed',
    price: 30,
  },
  {
    id: 'ep075',
    text: 'Finally, there are people who don\'t care to caper about and fidget aimlessly and flirt and make advances, or, most of all, thrust their noses in where they are not wanted.',
    work: 'The Double',
    year: 1846,
    ref: 'Three',
    translator: 'unnamed',
    price: 45,
  },
  {
    id: 'ep076',
    text: 'I have never allowed people to wipe their feet on me, and I\'m even less likely to let an infamous wretch try it.',
    work: 'The Double',
    year: 1846,
    ref: 'Eight',
    translator: 'unnamed',
    price: 35,
  },
  {
    id: 'ep077',
    text: 'You may always find this individual, however, in the society of people of sincere and honest heart, which cannot be said of some.',
    work: 'The Double',
    year: 1846,
    ref: 'Nine',
    translator: 'unnamed',
    price: 35,
  },
  {
    id: 'ep078',
    text: 'Before every man lie many different roads, and none can tell what path any man may chance to tread.',
    work: 'The Double',
    year: 1846,
    ref: 'Twelve',
    translator: 'unnamed',
    price: 30,
  },
  {
    id: 'ep079',
    text: 'There can no longer be any doubt: I am utterly lost, I am finished; and this is all in the nature of things, it could not have been otherwise.',
    work: 'The Double',
    year: 1846,
    ref: 'Thirteen',
    translator: 'unnamed',
    price: 40,
  },
  {
    id: 'ep080',
    text: 'I have lived, as they say, keeping myself to myself, that is, utterly alone — alone, entirely alone.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Garnett',
    price: 30,
  },
  {
    id: 'ep081',
    text: 'The more conscious I was of the good and of all this "beautiful and lofty," the deeper I kept sinking into my mire, and the more capable I was of getting completely stuck in it.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep082',
    text: 'Once they are overcome, say, by vengeful feeling, then for the time there is simply nothing left in their whole being but this feeling.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. III',
    translator: 'Pevear & Volokhonsky',
    price: 35,
  },
  {
    id: 'ep083',
    text: 'For a minute or so later I\'d be reasoning spitefully that it was all a lie, a lie, a loathsome, affected lie – that is, all these repentances, tenderheartednesses, all these vows of regeneration.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. V',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep084',
    text: 'I repeat, I emphatically repeat: ingenuous people and active figures are all active simply because they are dull and narrow-minded.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. V',
    translator: 'Pevear & Volokhonsky',
    price: 35,
  },
  {
    id: 'ep085',
    text: 'Consequently, these laws of nature need only be discovered, and then man will no longer be answerable for his actions, and his life will become extremely easy.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 40,
  },
  {
    id: 'ep086',
    text: 'Suppose it is a law of logic, but perhaps not of mankind at all.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep087',
    text: 'Suppose all man ever does is search for this two times two is four; he crosses oceans, he sacrifices his life in the search; but to search it out, actually to find it – by God, he\'s somehow afraid.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep088',
    text: 'For he senses that once he finds it, there will be nothing to search for.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep089',
    text: 'In short, man is comically arranged; there is apparently a joke in all this.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep090',
    text: 'For man sometimes loves suffering terribly much, to the point of passion, and that is a fact.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep091',
    text: 'You boast about consciousness, yet all you do is vacillate, because, though your mind works, your heart is darkened by depravity, and without a pure heart there can be no full, right consciousness.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. XI',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep092',
    text: 'I was morbidly developed, as a man of our time ought to be developed.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. I',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep093',
    text: 'The first married love will pass, true, but then an even better love will come.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VI',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep094',
    text: 'It\'s your soul, your soul, over which you have no power, that you put in bondage along with your body!',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep095',
    text: 'Love! – but this is everything, it\'s a diamond, a maiden\'s treasure, this love!',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep096',
    text: 'You\'ll die – they\'ll lay you out hurriedly, strangers\' hands, grumblingly, impatiently – and no one will bless you, no one will sigh over you, all they\'ll think is how to get you off their backs quickly.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. VII',
    translator: 'Pevear & Volokhonsky',
    price: 55,
  },
  {
    id: 'ep097',
    text: 'We\'ve even grown so unaccustomed that at times we feel a sort of loathing for real "living life," and therefore cannot bear to be reminded of it.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 40,
  },
  {
    id: 'ep098',
    text: 'It\'s a burden for us even to be men – men with real, our own bodies and blood; we\'re ashamed of it, we consider it a disgrace, and keep trying to be some unprecedented omni-men.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 45,
  },
  {
    id: 'ep099',
    text: 'For there comes a time in every man\'s life when he simply must have somewhere he can go!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part one, ch. II',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep100',
    text: 'People have grown accustomed to having everything ready-made for them, they\'re used to depending on the guidance of others, having everything chewed up for them first.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part two, ch. V',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep101',
    text: 'Talk nonsense to me, by all means, but do it with your own brain, and I shall love you for it.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. I',
    translator: 'McDuff',
    price: 30,
  },
  {
    id: 'ep102',
    text: 'It\'s impossible to leap over nature solely by means of logic!',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep103',
    text: 'The ordinary must live in obedience and do not have the right to break the law, because, well, because they\'re ordinary, you see.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep104',
    text: 'The second category all break the law, are destroyers, or have a tendency that way, depending on their abilities.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep105',
    text: 'One person out of ten thousand (I\'m talking approximately, by way of illustration) is, perhaps, born with a somewhat higher degree of independence.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. V',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep106',
    text: 'I want to live my own life, too, otherwise I\'d do better not to live at all.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part three, ch. VI',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep107',
    text: 'People who go on like that sometimes have an urge to throw themselves out of windows or jump off church towers, and it\'s a tempting sort of sensation.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part four, ch. V',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep108',
    text: 'Everything depends on a man\'s surroundings and environment.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part five, ch. I',
    translator: 'McDuff',
    price: 20,
  },
  {
    id: 'ep109',
    text: 'I think you\'re one of the kind who even if his intestines were being cut out would stand looking at his torturers with a smile – as long as he\'d found a God, or a faith.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. II',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep110',
    text: 'I know you don\'t believe it, but I promise you, life will carry you through.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. II',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep111',
    text: 'A man\'s footsteps lead him to all sorts of places.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. III',
    translator: 'McDuff',
    price: 20,
  },
  {
    id: 'ep112',
    text: 'I\'m afraid of death and I don\'t like it when people talk about it.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. III',
    translator: 'McDuff',
    price: 25,
  },
  {
    id: 'ep113',
    text: 'Razumikhin will be with you; I\'ve told him… Don\'t shed any tears for me: I shall try to be brave, and honest, all the rest of my life, even though I am a murderer.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. VII',
    translator: 'McDuff',
    price: 40,
  },
  {
    id: 'ep114',
    text: 'Look, you say to yourself, look how everything in the world is growing cold.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep115',
    text: 'Your fantastic world will fade away, your dreams will wilt and die, scattering like yellow leaves from the trees.',
    work: 'White Nights',
    year: 1848,
    ref: 'Second night',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep116',
    text: 'It was a sad and dismal day today, rainy, without a ray of hope, just like the long days of my old age which I know will be as sad and dismal.',
    work: 'White Nights',
    year: 1848,
    ref: 'Third night',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep117',
    text: 'I\'ve been thinking for a long time, why aren\'t we all just like brothers to one another.',
    work: 'White Nights',
    year: 1848,
    ref: 'Third night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep118',
    text: 'For it remains imprinted in my memory like a sweet dream one remembers a long time after awakening.',
    work: 'White Nights',
    year: 1848,
    ref: 'Fourth night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep119',
    text: 'There are no honest thieves, and there never have been any.',
    work: 'The Honest Thief',
    year: 1848,
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep120',
    text: 'Never does nature ask you for your opinion; she does not care a damn for your wishes, or whether you like her laws or not.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'III',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep121',
    text: 'I\'ve already said so before, but let me repeat, and repeat most earnestly: all plain men and men of action are active only because they are dull-witted and mentally undeveloped.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'V',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep122',
    text: 'What will happen, of course, is that the day after tomorrow (and that at the latest) you will begin despising yourself for having knowingly duped yourself.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'V',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep123',
    text: 'All civilisation does is to develop in man the many-sidedness of his sensations, and nothing, absolutely nothing more.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VII',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep124',
    text: 'In short, you can say anything you like about world history, anything that might enter the head of a man with the most disordered imagination.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VIII',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep125',
    text: 'Twice-two-makes-four is, in my humble opinion, nothing but a piece of impudence.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep126',
    text: 'Perhaps suffering is just as good for him as prosperity?',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep127',
    text: 'Let me add, by the way: Heine says that true biographies are almost impossible, and that a man will most certainly tell a lot of lies about himself.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep128',
    text: 'Our romantic is a man of great breadth of vision and the most consummate rascal of all our rascals, I assure you—from experience.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep129',
    text: 'Good clothes impress people and will immediately put us on an equal footing in the eyes of society.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'XI',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep130',
    text: 'In the end I could no longer stand it myself: the older I became, the more I longed for the society of men and the more I was in need of friends.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'II',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep131',
    text: 'People take to drink because they are unhappy, don\'t they?',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VI',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep132',
    text: 'In such circumstances even hard work is a joy; even if you have to go hungry sometimes for the sake of your children, it is a joy.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VI',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep133',
    text: 'At any rate, I have felt ashamed all the time I have been writing this story: so it seems this is no longer literature, but a corrective punishment.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep134',
    text: 'A succession of memories which he recalls does at last lead him inevitably to the truth , and truth inevitably elevates his mind and heart.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep135',
    text: 'Proud women are particularly good when—well, when you\'re no longer in doubt about your power over them.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep136',
    text: 'I have spent all my life speaking without words.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep137',
    text: 'It is because of this that such women sometimes behave so outrageously that you can hardly believe your eyes.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep138',
    text: 'I love, I can only love the earth I\'ve left behind, stained with my blood when, ungrateful wretch that I am, I extinguished my life by shooting myself through the heart.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'II',
    translator: 'Magarshack',
    price: 40,
  },
  {
    id: 'ep139',
    text: 'On our earth we can truly love only with suffering and through suffering!',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'II',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep140',
    text: 'Knowledge is higher than feeling, and the consciousness of life is higher than life.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep141',
    text: 'Every one of them became so jealous of his own personality that he strove with might and main to belittle and humble it in others; and therein he saw the whole purpose of his life.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 45,
  },
  {
    id: 'ep142',
    text: 'I loved the earth they had polluted even more than when it had been a paradise, and only because sorrow had made its appearance on it.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep143',
    text: 'The main thing is to love your neighbour as yourself—that is the main thing, and that is everything, for nothing else matters.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep144',
    text: 'Once you do that, you will discover at once how everything can be arranged.',
    work: 'The Dream of a Ridiculous Man',
    year: 1877,
    ref: 'V',
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep145',
    text: 'There are people too, gentlemen, who will not say they are happy and living life to the full just because, for example, their trousers are a good fit.',
    work: 'The Double',
    year: 1846,
    ref: 'Three',
    translator: 'unnamed',
    price: 40,
  },
  {
    id: 'ep146',
    text: 'Mother Nature is bounteous; and you will not be called to account for this, you won\'t have to answer for it.',
    work: 'The Double',
    year: 1846,
    ref: 'Six',
    translator: 'unnamed',
    price: 30,
  },
  {
    id: 'ep147',
    text: 'All right, he\'s a scoundrel – well, let him be – other people are honest, to make up for it.',
    work: 'The Double',
    year: 1846,
    ref: 'Nine',
    translator: 'unnamed',
    price: 30,
  },
  {
    id: 'ep148',
    text: 'There are other positions where it is possible to be of use to One\'s country.',
    work: 'The Double',
    year: 1846,
    ref: 'Eleven',
    translator: 'unnamed',
    price: 25,
  },
  {
    id: 'ep149',
    text: 'There is sadness lurking even in gilded palaces, you can\'t escape from it anywhere.',
    work: 'The Double',
    year: 1846,
    ref: 'Twelve',
    translator: 'unnamed',
    price: 25,
  },
  {
    id: 'ep150',
    text: 'Everything that was just, but humiliated and downtrodden, they laughed at disgracefully and hardheartedly.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. II',
    translator: 'Pevear & Volokhonsky',
    price: 30,
  },
  {
    id: 'ep151',
    text: 'We don\'t even know where the living lives now, or what it is, or what it\'s called!',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part two: apropos of the wet snow, ch. IX',
    translator: 'Pevear & Volokhonsky',
    price: 25,
  },
  {
    id: 'ep152',
    text: 'People killed one another in a kind of senseless anger.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. II',
    translator: 'McDuff',
    price: 20,
  },
  {
    id: 'ep153',
    text: 'Perhaps what I resented was that among all our buildings there has never been one at which one could not stick out one\'s tongue.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 35,
  },
  {
    id: 'ep154',
    text: 'One can forgive a great deal for the sake of these moments.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'VI',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep155',
    text: 'It is their sincerity that assures them their victory.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep156',
    text: 'It is the lack of originality that has been the ruin of women.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep157',
    text: 'What is so awful is that the whole thing was just an accident—an ordinary, horrible, senseless accident!',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep158',
    text: 'To live beyond forty is indecent, banal, immoral!',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground',
    translator: 'Pevear & Volokhonsky',
    price: 20,
  },
  {
    id: 'ep159',
    text: 'We sometimes want pure rubbish precisely because, in our stupidity, we see this rubbish as the easiest path to the attainment of some preconceived profit.',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'Part one: underground, ch. VIII',
    translator: 'Pevear & Volokhonsky',
    price: 40,
  },
  {
    id: 'ep160',
    text: 'Perhaps it had been merely the strength of his own desires that made him believe he was a person to whom more was allowed than others.',
    work: 'Crime and Punishment',
    year: 1866,
    ref: 'Part six, ch. II',
    translator: 'McDuff',
    price: 35,
  },
  {
    id: 'ep161',
    text: 'We laughed, we cried, we said a thousand things without caring whether they made sense or not.',
    work: 'White Nights',
    year: 1848,
    ref: 'Fourth night',
    translator: 'Magarshack',
    price: 30,
  },
  {
    id: 'ep162',
    text: 'What is an insult but a sort of purification?',
    work: 'Notes from Underground',
    year: 1864,
    ref: 'IX',
    translator: 'Magarshack',
    price: 20,
  },
  {
    id: 'ep163',
    text: 'Truth shone forth like the sun, and there was no room left for doubt in my mind.',
    work: 'A Gentle Creature',
    year: 1876,
    translator: 'Magarshack',
    price: 25,
  },
  {
    id: 'ep164',
    text: 'The man was like everybody else, respectable, of course, like all respectable people, and perhaps even possessing some special and even fairly important merits of his own – in short, he was an ordinary man.',
    work: 'The Double',
    year: 1846,
    ref: 'Five',
    translator: 'unnamed',
    price: 55,
  },
];

export const TOTAL_QUOTES = QUOTES.length;

/** The stall itself, printed at the top of every bill. */
export const STALL = {
  name: 'NEW LIGHT BOOK STALL',
  line1: 'Secondhand · Russian classics a speciality',
  line2: 'Opp. Gandhi Maidan, Platform Road',
  phone: 'PH 2274 4190',
  est: 'EST. 1971',
  gst: '10ABCDE1234F1Z5',
};

/**
 * Deal the next line.
 *
 * Draws from a shuffled bag rather than picking at random, so you see every
 * line once before you see any of them twice — "unique each time" meaning
 * genuinely unique, not merely unlikely to repeat.
 */
export function drawNext(seen: string[]): { quote: Quote; bagReset: boolean } {
  const unseen = QUOTES.filter((q) => !seen.includes(q.id));
  if (unseen.length > 0) {
    return { quote: unseen[Math.floor(Math.random() * unseen.length)], bagReset: false };
  }

  // Bag empty: tip it out and start again. Hold back the line you just read,
  // so the seam between one bag and the next cannot hand you a repeat either.
  const last = seen[seen.length - 1];
  const fresh = QUOTES.filter((q) => q.id !== last);
  const pool = fresh.length > 0 ? fresh : QUOTES;
  return { quote: pool[Math.floor(Math.random() * pool.length)], bagReset: true };
}
