/**
 * Heirloom Wall: 28 buildable ways to display three Nathdwara paintings in a
 * living room. Every idea is written as a brief you can hand to a carpenter,
 * electrician or artisan: layout, what it is made of, who makes it, how it
 * hangs, how it is lit, how the painting is protected, and a ballpark cost.
 *
 * Sizes assume each work on its mount is about 45 × 65 cm (Shrinathji
 * 50 × 68 cm). Measure yours and use the planner on the page.
 *
 * Costs are rough 2026 ballparks for an Indian metro, in rupees, for the
 * work around the paintings (not the paintings). Get three quotes.
 */

export type Tag = 'heritage' | 'modern' | 'renter' | 'diy' | 'statement' | 'protective';

export const TAGS: { id: Tag; label: string }[] = [
  { id: 'heritage', label: 'Heritage craft' },
  { id: 'statement', label: 'Statement' },
  { id: 'modern', label: 'Modern' },
  { id: 'protective', label: 'Best protection' },
  { id: 'renter', label: 'Renter-friendly' },
  { id: 'diy', label: 'DIY-able' },
];

export type Point = { k: 'Layout' | 'Make' | 'Who' | 'Hang' | 'Light' | 'Protect' | 'Cost' | 'Why'; v: string };

export type Idea = {
  id: string;
  title: string;
  hook: string;
  tags: Tag[];
  /** ballpark, in thousands of rupees */
  cost: [number, number];
  /** 1: a good carpenter in a week · 2: a workshop and a site visit or two · 3: specialist artisans, months */
  level: 1 | 2 | 3;
  weeks: string;
  /** minimum clear wall width in cm */
  wall: number;
  points: Point[];
};

export const POINT_LABEL: Record<Point['k'], string> = {
  Layout: 'Layout',
  Make: 'Materials & build',
  Who: 'Who makes it',
  Hang: 'Fixing',
  Light: 'Lighting',
  Protect: 'Protecting the paintings',
  Cost: 'Cost & time',
  Why: 'Why it is yours alone',
};

export const IDEAS: Idea[] = [
  {
    id: 'jharokha',
    title: 'Haveli Jharokhas',
    hook: 'Three carved jharokha windows, as if Shrinathji and the two who face him were looking out of the old house into the new one.',
    tags: ['heritage', 'statement'],
    cost: [60, 150], level: 2, weeks: '4–6 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'Acharya left, Shrinathji centre, Krishna right. The centre jharokha is 20 cm taller and stands 4 cm proud of the other two. 10 cm between windows. Group about 205 cm wide, centre line at 150 cm from the floor.' },
      { k: 'Make', v: 'Each window is a cusped-arch frame in seasoned sheesham or teak, 6–8 cm wide, with a small chhajja (eave) on carved brackets above. The arch sits on a 10 cm deep box-out of 18 mm BWP plywood, painted deep indigo in matt lime-wash so the gold in the paintings carries.' },
      { k: 'Who', v: 'Jodhpur and Udaipur carving workshops sell jharokha frames ready-made. Any good carpenter can build the box-out. Send the workshop the exact opening sizes: painting plus 2 cm all round.' },
      { k: 'Hang', v: 'The box-out goes onto the wall with a 45° plywood French cleat and 8 mm screws in plugs. Each painting hangs on its own cleat inside the recess, so you can lift it out without taking the carving down.' },
      { k: 'Light', v: 'A 2700 K, CRI 95+ LED strip of about 5 W/m runs inside the top of each arch, behind a 15 mm lip so you never see the dots. Put all three on one dimmer and set them to about 80 lux on the painting.' },
      { k: 'Protect', v: 'Each painting is glazed with UV-filtering anti-reflective glass on 12 mm spacers so the glass never touches the raised gold or the kundan stones. Leave a 5 mm air gap behind and drill two small vent holes at the bottom of each recess.' },
      { k: 'Cost', v: '₹60k–1.5L depending on carving depth. Ready-made jharokhas are cheapest; custom sizes take 4–6 weeks.' },
      { k: 'Why', v: 'A jharokha is the window a haveli looks out of, and the paintings come from a haveli. Hung like this, the old house frames them again.' },
    ],
  },
  {
    id: 'pichwai',
    title: 'Pichwai Backdrop',
    hook: 'In Nathdwara a painted cloth, the pichwai, hangs behind Shrinathji. Give your three paintings one of their own.',
    tags: ['heritage', 'statement'],
    cost: [25, 300], level: 2, weeks: '3–10 weeks', wall: 260,
    points: [
      { k: 'Layout', v: 'A 240 × 160 cm painted cloth stretched on a stretcher frame and centred on the wall. The three paintings float on top of it 25 mm off the cloth, with Shrinathji in the middle. Keep at least 25 cm of cloth showing around the group.' },
      { k: 'Make', v: 'Commission a kamal talai (lotus pond) pichwai in indigo, or cows and gopis: cloth hand-painted with mineral and natural pigments. Stretch it over a 40 mm aluminium or seasoned-wood stretcher with a 2 cm return, like a canvas. A printed pichwai on cotton is a cheaper stand-in.' },
      { k: 'Who', v: 'Pichwai painters in Nathdwara, including the artist\'s own workshop line if the family can trace it. Ask for a painting with an empty band behind the three frames so no painted figure is hidden.' },
      { k: 'Hang', v: 'The stretcher hangs on two aluminium Z-clips. The paintings fix to 25 mm brass standoffs that pass through grommeted holes in the cloth into the wall behind, so the cloth carries no weight.' },
      { k: 'Light', v: 'Two ceiling spots at 30° from vertical, one for the cloth (wide 36° beam) and one for the group (24°). Set both to 2700 K, CRI 95+ and put them on a dimmer.' },
      { k: 'Protect', v: 'Painted cloth sheds dust, so vacuum it once a season through a nylon mesh. Keep the whole wall out of direct sun, because natural dyes fade within a few seasons in it.' },
      { k: 'Cost', v: 'Printed pichwai: ₹25–40k all in. Hand-painted pichwai: ₹1–3L or more, depending on size and detail. Allow 6–10 weeks for painting.' },
      { k: 'Why', v: 'This is how the paintings would be seen in the haveli they depict: in front of cloth, not on plaster.' },
    ],
  },
  {
    id: 'shutters',
    title: 'Darshan Shutters',
    hook: 'Nathdwara opens Shrinathji\'s doors for eight darshans a day. Your wall can open and close too.',
    tags: ['heritage', 'statement', 'protective'],
    cost: [70, 260], level: 2, weeks: '4–8 weeks', wall: 260,
    points: [
      { k: 'Layout', v: 'All three paintings sit in a 230 × 100 cm niche 12 cm deep. Two carved wooden doors, one pair per side, fold back like temple doors (kivad), each 57 cm wide. Closed, the wall shows a carved double door. Open, it shows the three.' },
      { k: 'Make', v: 'Doors of 25 mm teak with raised panels, brass studs and a ring knocker. They hang on concealed 165° cabinet hinges, or on a top-hung bi-fold track for a cleaner look. Line the inside of the niche with indigo velvet on 6 mm ply.' },
      { k: 'Who', v: 'A furniture carpenter for the niche and doors. A brass shop sells studs and knockers by weight. A home-automation installer can add a motorised track (Somfy or similar).' },
      { k: 'Hang', v: 'The niche is a plywood carcass fixed to the wall with 10 mm anchors. Each painting hangs on its own cleat inside. Fit the doors last and adjust them so they close flush.' },
      { k: 'Light', v: 'A 2700 K strip behind the front lip, switched by a door contact so the light comes on as the doors open, as at darshan. Add an optional timer for morning and evening openings.' },
      { k: 'Protect', v: 'This is the best light protection of any idea here. Shut, the paintings get no light at all, so a few hours a day open means far less fading. Add a silica-gel cassette at the base and a felt bumper on each door.' },
      { k: 'Cost', v: 'Manual doors: ₹70k–1.6L. Motorised: add ₹40k–1L. 4–8 weeks.' },
      { k: 'Why', v: 'It brings back how the paintings\' world works: the image is not always there, and is opened, with a little ceremony, at set times.' },
    ],
  },
  {
    id: 'torana',
    title: 'Ayodhya Stone Torana',
    hook: 'A gateway in Bansi Paharpur pink sandstone, the stone of the new Ram Mandir, carved by temple masons.',
    tags: ['heritage', 'statement'],
    cost: [150, 400], level: 3, weeks: '8–14 weeks', wall: 280,
    points: [
      { k: 'Layout', v: 'A toran (temple gateway) about 260 cm wide and 210 cm tall: two carved pillars 22 cm wide with a cusped lintel and a kalash on top. The three paintings hang inside the opening on a plain lime-plaster panel.' },
      { k: 'Make', v: 'Not solid stone. Use 25–30 mm carved sandstone cladding, CNC-roughed and hand-finished. The pillars are hollow L-sections. Allow about 65–75 kg/m² of cladding.' },
      { k: 'Who', v: 'Temple stone workshops around Pindwara (Sirohi) and in Bharatpur district, where the Bansi Paharpur stone is quarried, carve to drawings and ship in numbered pieces.' },
      { k: 'Hang', v: 'This needs a structural check. Fix with stainless-steel clamps into a brick or RCC wall, plus stone epoxy. It is not for drywall or a thin partition. Fix the paintings to the plaster panel with hidden cleats.' },
      { k: 'Light', v: 'Graze the carving from below with a 2700 K linear LED in the plinth, and give the paintings separate spots so the stone doesn\'t outshine them.' },
      { k: 'Protect', v: 'Sandstone gives off fine dust for the first months. Seal it with a breathable stone sealer before the paintings go up. Hang the paintings only after the plaster has fully cured, which takes 4+ weeks.' },
      { k: 'Cost', v: '₹1.5–4L including installation. 8–14 weeks.' },
      { k: 'Why', v: 'Three Nathdwara Vaishnava images inside a gate of the same stone as the new temple at Ayodhya.' },
    ],
  },
  {
    id: 'thikri',
    title: 'Sheesh Mahal Halo',
    hook: 'A halo of hand-cut mirror (thikri) behind the trio, the way Rajput palaces made a candle look like a sky full of stars.',
    tags: ['heritage', 'statement'],
    cost: [60, 200], level: 3, weeks: '5–8 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'A 230 × 130 cm panel with a sunburst of mirror pieces radiating from behind Shrinathji and fading out at the edges. The two side paintings sit where the rays thin out.' },
      { k: 'Make', v: 'Thikri work: small hand-cut convex and flat mirror pieces set in lime-and-marble-dust plaster on a 12 mm cement-board panel, with gold-leaf lines between the rays. Make it on the panel in the workshop, not on site.' },
      { k: 'Who', v: 'Thikri artisans from Udaipur and Jaipur, who restore palace interiors and take private commissions. Ask to see work that is at least five years old.' },
      { k: 'Hang', v: 'The panel weighs about 40–50 kg: use a full-width steel French cleat on 10 mm anchors. Fix the paintings with standoffs through pre-planned bare spots in the mirror field.' },
      { k: 'Light', v: 'One warm spot at a low angle makes the field sparkle. In the evening use a single brass oil-lamp-style LED below, never a real flame (see Protect).' },
      { k: 'Protect', v: 'Mirrors bounce light back onto the paintings, so keep the lights lower than you would on a plain wall (≈60 lux). Never put a real diya on this wall: soot settles on mirrors and paintings alike.' },
      { k: 'Cost', v: '₹60k–2L. 5–8 weeks.' },
      { k: 'Why', v: 'The kundan stones in the paintings glitter; the wall glitters back.' },
    ],
  },
  {
    id: 'molela',
    title: 'Molela Clay Frieze',
    hook: 'Terracotta plaques from Molela, a potters\' village near Nathdwara, of the cows and peacocks from Shrinathji\'s border.',
    tags: ['heritage', 'diy'],
    cost: [20, 60], level: 1, weeks: '2–4 weeks', wall: 220,
    points: [
      { k: 'Layout', v: 'A band of 10–14 terracotta plaques, each about 20 × 20 cm, along the wall under the paintings at 90 cm. Optionally add a second band above at 230 cm. The paintings hang between the bands in a normal line.' },
      { k: 'Make', v: 'Order the plaques in cow, peacock and lotus designs, unglazed or lightly washed with ochre. Ask for flat backs and two recessed key-holes each.' },
      { k: 'Who', v: 'Potter families in Molela (Rajsamand district) make votive plaques, and sell through craft fairs and directly. It is a short trip from Nathdwara.' },
      { k: 'Hang', v: 'Two screws per plaque, levelled with a laser. Seal the backs first with a dilute acrylic so they don\'t draw damp from a new wall.' },
      { k: 'Light', v: 'A wall-washer along the ceiling, or a slim linear LED on top of the lower band shining up, rakes the reliefs.' },
      { k: 'Protect', v: 'Terracotta is fine with light. The paintings above still want UV glass and 50–100 lux.' },
      { k: 'Cost', v: '₹1.5–5k a plaque. ₹20–60k with fixing. 2–4 weeks.' },
      { k: 'Why', v: 'The clay and the painting come from the same few kilometres of Rajasthan.' },
    ],
  },
  {
    id: 'repousse',
    title: 'Repoussé Brass Frames',
    hook: 'Hand-chased brass frames that carry each painting\'s own motifs out onto the wall.',
    tags: ['heritage'],
    cost: [40, 120], level: 2, weeks: '4–6 weeks', wall: 200,
    points: [
      { k: 'Layout', v: 'Classic triptych: 8 cm gaps, centre line at 150 cm. Each frame is 9–11 cm wide. The acharya\'s frame is chased with lotus buds, Shrinathji\'s with cows, and Krishna\'s with peacock feathers.' },
      { k: 'Make', v: 'A 0.6–0.8 mm brass sheet worked in repoussé (pushed out from the back) and chased from the front, wrapped over a hardwood core frame. A clear lacquer finish keeps it bright. Oil-rubbed or antique finishes are also possible.' },
      { k: 'Who', v: 'Brass workshops in Moradabad, or the temple-metal workshops of Udaipur and Nathdwara, which make shrine frames. Give them a full-size paper template of each painting.' },
      { k: 'Hang', v: 'Each frame weighs about 6–9 kg. Use two D-rings and two security hooks per frame, so it can\'t swing or come off by accident.' },
      { k: 'Light', v: 'Avoid putting picture lights on the frames, because they make hot spots on polished brass. Use two ceiling spots at 30° instead.' },
      { k: 'Protect', v: 'Use UV-filtering anti-reflective glass on spacers inside the frame. Leave the lacquer alone, because polish wears through it and then the brass tarnishes.' },
      { k: 'Cost', v: '₹40k–1.2L for the three frames. 4–6 weeks.' },
      { k: 'Why', v: 'The frame becomes part of the picture, the way a jeweller sets a stone.' },
    ],
  },
  {
    id: 'kamal',
    title: 'Kamal Talai Mural',
    hook: 'The lotus ponds at the foot of each painting spill out into one pond painted across the whole wall.',
    tags: ['heritage', 'statement'],
    cost: [40, 150], level: 2, weeks: '2–3 weeks on site', wall: 300,
    points: [
      { k: 'Layout', v: 'Paint the lower 100 cm of the wall from end to end as a pond: lotus, leaves, fish and egrets, in the same pinks and greens as the paintings. Hang the paintings with their bottom edges about 10 cm above the painted water line, as if standing on its bank.' },
      { k: 'Make', v: 'Paint in acrylic or casein on a properly primed wall, then seal it with a matt varnish so it can be wiped. Give the painter photos of the ponds in the three paintings to match.' },
      { k: 'Who', v: 'Nathdwara painters travel for wall commissions. Muralists who paint Pichwai-style walls in Udaipur, Ahmedabad and Mumbai hotels do too.' },
      { k: 'Hang', v: 'Fix the cleats before painting so the mural never has to be cut into. Fill and touch up the screw holes afterwards.' },
      { k: 'Light', v: 'A wall-washer wide enough to cover the whole mural, plus three 24° spots for the paintings. Put them on separate circuits so the pond can glow on its own at night.' },
      { k: 'Protect', v: 'Keep the sofa\'s back 10 cm off the wall to save the paint. Seal the mural before any frames go up.' },
      { k: 'Cost', v: '₹40k–1.5L for about 3 m × 1 m. 2–3 weeks of painting on site.' },
      { k: 'Why', v: 'The three paintings, made separately, end up standing at the same pond.' },
    ],
  },
  {
    id: 'araish',
    title: 'Araish Niches',
    hook: 'Three recessed niches in polished Rajasthani lime plaster, smooth as marble and warm to the touch.',
    tags: ['heritage', 'modern'],
    cost: [60, 180], level: 2, weeks: '4–6 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'A 12 cm deep false wall with three arched niches, each opening the painting plus 6 cm. The centre one is taller. The niches are 25 cm apart, and the false wall spans the full room width so it reads as architecture.' },
      { k: 'Make', v: 'A GI-stud or ply carcass, cement board, then araish: coats of lime and marble dust, polished with agate stones until it shines. Ivory for the wall, with the niche backs tinted pale indigo.' },
      { k: 'Who', v: 'Araish plasterers from Jaipur and Shekhawati. Ask your interior contractor to subcontract the finish rather than imitate it with putty.' },
      { k: 'Hang', v: 'Fix blocking into the carcass behind each niche before plastering, and hang each painting on a cleat screwed into it.' },
      { k: 'Light', v: 'One 3 W, 2700 K micro-downlight in the top of each niche, recessed and with a 24° beam.' },
      { k: 'Protect', v: 'Lime keeps curing for weeks and gives off moisture. Wait 4–6 weeks before hanging the paintings, then check the humidity with a ₹500 hygrometer.' },
      { k: 'Cost', v: '₹60k–1.8L. 4–6 weeks including curing.' },
      { k: 'Why', v: 'It has the plain old-house finish that photographs never manage, with the paintings set into the wall rather than hung on it.' },
    ],
  },
  {
    id: 'door',
    title: 'The Ancestral Door',
    hook: 'A salvaged carved haveli door becomes the frame, so the three paintings come with a door from a house like the one they left.',
    tags: ['heritage', 'statement'],
    cost: [55, 230], level: 2, weeks: '3–6 weeks', wall: 200,
    points: [
      { k: 'Layout', v: 'A carved double door of about 200 × 225 cm, fixed shut and standing against the wall. The two upper panels hold the acharya and Krishna; the lintel or a central fixed panel holds Shrinathji. If the old house still stands, use its own door.' },
      { k: 'Make', v: 'Cut each painting\'s opening out of the door panel and back it with a shadow-box tray of 12 mm ply. Treat the old wood against borers, which means fumigating it before it enters the house. Leave the brass and iron fittings on.' },
      { k: 'Who', v: 'Antique-architecture dealers in Jodhpur and Jaipur, or the family\'s own old house. A restorer-carpenter does the conversion.' },
      { k: 'Hang', v: 'Old teak doors weigh 60–120 kg. Stand the door on the floor on a hidden plinth and tie it back to the wall at the top with two steel brackets; don\'t hang it.' },
      { k: 'Light', v: 'Use two ceiling spots, or hide an LED in each shadow-box tray. Light the door\'s iron studs from below to show the texture.' },
      { k: 'Protect', v: 'Fumigate first, and check for powder (borer dust) under the door for a month before the paintings go in.' },
      { k: 'Cost', v: '₹40k–2L for the door, plus ₹15–30k to convert it. 3–6 weeks.' },
      { k: 'Why', v: 'The paintings came from an old house, and this brings a piece of that house with them.' },
    ],
  },
  {
    id: 'jaali',
    title: 'Jaali Lightbox',
    hook: 'A glowing lattice behind the paintings: by day a carved screen, by night lace made of light.',
    tags: ['modern', 'statement'],
    cost: [35, 100], level: 2, weeks: '2–4 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'A 240 × 120 cm lightbox 8 cm deep, faced with a jaali panel. The paintings float on 30 mm standoffs on the jaali\'s solid zones, which are left uncut behind each frame.' },
      { k: 'Make', v: 'CNC-cut 12 mm MDF painted lacquer black, or 3 mm brushed brass sheet for luxury. A white back panel and an LED strip around the inside perimeter, 2700 K. Diffuse the strip so it shows as an even glow, not dots.' },
      { k: 'Who', v: 'Any CNC router shop cuts from a DXF file. Use a classic Mughal eight-point star jaali, or draw one from the cow-and-lotus border.' },
      { k: 'Hang', v: 'A steel cleat on the box. Pre-drill the standoffs through the solid zones before painting.' },
      { k: 'Light', v: 'The lightbox runs on a dimmer, never at full brightness behind art (keep it under 10% at night). A separate 24° spot lights each painting\'s face.' },
      { k: 'Protect', v: 'The paintings must not sit in front of a hot box. Use a constant-current LED driver outside the box, and keep the strip under 10 W/m.' },
      { k: 'Cost', v: '₹35k–1L. 2–4 weeks.' },
      { k: 'Why', v: 'Jaali is the old way to let light into a house. Here it is turned inside out, letting the light come out of the wall.' },
    ],
  },
  {
    id: 'chhatri',
    title: 'Chhatri Wall Shrine',
    hook: 'A shallow wooden pavilion with a dome, two pillars and a step for Shrinathji. The two who face him stand outside it.',
    tags: ['heritage'],
    cost: [60, 160], level: 2, weeks: '4–6 weeks', wall: 230,
    points: [
      { k: 'Layout', v: 'A 25 cm deep chhatri about 90 cm wide and 160 cm tall, base at 75 cm, holding Shrinathji. The acharya and Krishna hang outside it at matching heights, 20 cm from the pillars.' },
      { k: 'Make', v: 'Carved teak pillars and a dome (half-dome, flat-backed), and a 15 cm ledge at the bottom for flowers or a small lamp. Finish it in natural oil or in red and gold lacquer.' },
      { k: 'Who', v: 'Mandir furniture makers in Ahmedabad, Jodhpur and Delhi (Kirti Nagar) build to size. Ask for a flat back and a removable dome.' },
      { k: 'Hang', v: 'Fix it to the wall with a cleat and two L-brackets. A ledge used for offerings should also rest on a hidden steel support.' },
      { k: 'Light', v: 'A 2700 K strip in the dome\'s underside, and two small spots for the side paintings.' },
      { k: 'Protect', v: 'If the ledge becomes a pooja ledge, use an LED diya. Real flame and incense under paper paintings leave soot and heat stains within a year.' },
      { k: 'Cost', v: '₹60k–1.6L. 4–6 weeks.' },
      { k: 'Why', v: 'It turns the wall into a small home shrine without needing a pooja room.' },
    ],
  },
  {
    id: 'hindola',
    title: 'Hindola Stand',
    hook: 'A freestanding carved swing frame, the kind brought out for the Hindola festival in Shravan, with Shrinathji hung from it on brass chains.',
    tags: ['heritage', 'statement', 'renter'],
    cost: [40, 120], level: 2, weeks: '3–5 weeks', wall: 220,
    points: [
      { k: 'Layout', v: 'A 120 cm wide, 200 cm tall hindola frame on its own base, 30 cm in front of the wall. Shrinathji hangs from its top bar on two brass chains. The acharya and Krishna hang on the wall behind at either side, so the eye reads the swing as the centre.' },
      { k: 'Make', v: 'Carved posts with parrot or peacock finials, and a wide, heavy base (70 × 40 cm, at least 25 kg) with felt pads. The chains are fixed with a locking pin at both ends, so the painting cannot swing.' },
      { k: 'Who', v: 'Wooden-toy and furniture carvers in Jodhpur, Sankheda or Channapatna make hindolas. Ask for a scaled-up frame with no seat.' },
      { k: 'Hang', v: 'No wall fixing for the centre painting, which suits renters. Tie the frame to a skirting anchor with a hidden cable so a child cannot pull it over.' },
      { k: 'Light', v: 'A spot on the swing plus a soft wall-wash behind, so the swing stands out from the wall.' },
      { k: 'Protect', v: 'Frame and glaze the centre painting to the same standard as the others. Fixed chains keep the kundan stones from being jolted.' },
      { k: 'Cost', v: '₹40k–1.2L. 3–5 weeks.' },
      { k: 'Why', v: 'In Shravan you can hang flowers on the swing, as in the haveli.' },
    ],
  },
  {
    id: 'pillar',
    title: 'The Turning Pillar',
    hook: 'A three-sided pillar on a bearing, one painting to a face. Turn it to choose the day\'s darshan; it doubles as a room divider.',
    tags: ['modern', 'statement', 'renter'],
    cost: [45, 120], level: 2, weeks: '3–4 weeks', wall: 0,
    points: [
      { k: 'Layout', v: 'A triangular prism about 70 cm a face and 200 cm tall, standing free between living and dining, with one painting centred on each face at 150 cm. It turns 120° to bring each face round.' },
      { k: 'Make', v: 'An 18 mm ply carcass veneered in walnut or teak on a 30 cm, 300 kg-rated lazy-susan bearing with a ball-detent stop every 120°. Use a cast-iron or steel ballast plate at the base to keep it stable.' },
      { k: 'Who', v: 'A good furniture workshop, with the bearing from industrial-hardware dealers. Ask for felt glides as well.' },
      { k: 'Hang', v: 'Each painting hangs on a security cleat in a 2 cm recess on its face. The pillar fixes to the ceiling with a top pin into a recessed plate, so it can turn without wobbling.' },
      { k: 'Light', v: 'One 24° ceiling spot aimed at the face toward the sofa. The faces turned away stay in the dark, which suits conservation.' },
      { k: 'Protect', v: 'Turn it slowly: the detents stop it, so nothing slams. Mount the paintings in deep frames with glazing.' },
      { k: 'Cost', v: '₹45k–1.2L. 3–4 weeks.' },
      { k: 'Why', v: 'One painting at a time, chosen each day, and it needs no wall at all.' },
    ],
  },
  {
    id: 'seasonal',
    title: 'Seasonal Shringar Rotation',
    hook: 'Nathdwara changes Shrinathji\'s pichwai with the festival. Show one painting at a time and change it with the season.',
    tags: ['protective', 'heritage'],
    cost: [40, 100], level: 1, weeks: '2–3 weeks', wall: 140,
    points: [
      { k: 'Layout', v: 'One generous niche or frame of 75 × 95 cm at eye level, with a low archival plan chest of three drawers underneath at 75 cm that holds the other two flat. Change paintings at Janmashtami, Diwali and Holi, or by your own calendar.' },
      { k: 'Make', v: 'Plan chest in birch ply, drawers 6 cm deep with acid-free board liners and silica gel. The niche gets a swap-friendly French cleat and a brass rail for a small festival toran.' },
      { k: 'Who', v: 'A carpenter. The museum board (acid-free, buffered) comes from art suppliers.' },
      { k: 'Hang', v: 'Fit every painting\'s frame with the same cleat so any of them drops into the niche in a minute.' },
      { k: 'Light', v: 'One 24° spot, dimmable. A brighter setting is fine because each painting is on show only four months a year.' },
      { k: 'Protect', v: 'Each painting gets two-thirds less light over a year, which is the biggest single reduction in fading after closing it away.' },
      { k: 'Cost', v: '₹40k–1L. 2–3 weeks.' },
      { k: 'Why', v: 'It works on a small wall and turns the festival calendar into the decorating plan.' },
    ],
  },
  {
    id: 'vitrine',
    title: 'Museum Vitrine',
    hook: 'A slim wall showcase with its own light and climate: the most protective option, and a modern-looking one.',
    tags: ['protective', 'modern'],
    cost: [60, 150], level: 2, weeks: '3–5 weeks', wall: 220,
    points: [
      { k: 'Layout', v: 'One 220 × 95 cm showcase 15 cm deep, holding the three works on a velvet back panel with 12 cm between them.' },
      { k: 'Make', v: 'A powder-coated aluminium or bronze-anodised frame, low-iron laminated glass front on a gas-strut lift or lockable side hinge, and silicone gaskets. A hidden drawer in the base takes a silica-gel cassette.' },
      { k: 'Who', v: 'Shop-fitting and jewellery-showcase makers. Ask for a museum-style sealed case, not a retail one, which leaks air.' },
      { k: 'Hang', v: 'The case (≈45 kg) hangs on a steel cleat with two bottom support brackets. Each painting hangs on a cleat on the back panel.' },
      { k: 'Light', v: 'A 2700 K, CRI 95+ linear LED along the top inside edge, with a separate driver outside the case so no heat builds up inside. Set it to 50–80 lux.' },
      { k: 'Protect', v: 'Gaskets plus silica gel set to 50% RH keeps the humidity steady through the monsoon, which matters for paper, gum and glued stones.' },
      { k: 'Cost', v: '₹60k–1.5L. 3–5 weeks.' },
      { k: 'Why', v: 'The paintings get the care of a museum without the room looking like one.' },
    ],
  },
  {
    id: 'peacock',
    title: 'Peacock Arch',
    hook: 'There is a peacock in every one of the three paintings. Here it fans its tail behind all three.',
    tags: ['statement', 'modern'],
    cost: [35, 100], level: 2, weeks: '3–4 weeks', wall: 260,
    points: [
      { k: 'Layout', v: 'A half-circle tail about 250 cm wide and 130 cm tall, centred on Shrinathji. The side paintings sit in front of the outer feathers. The peacock\'s body and head sit at the base below the centre painting.' },
      { k: 'Make', v: '3 mm laser-cut brass or 2 mm mild steel with a bronze powder-coat, in 30–40 feathers, each on a 20 mm spacer. Cut the eye of each feather open and back it with blue-green acrylic.' },
      { k: 'Who', v: 'Laser-cutting shops make it from a vector drawing, and a metal fabricator assembles it. Start the drawing from the page\'s mockup.' },
      { k: 'Hang', v: 'Fix each feather separately into plugs, so the sculpture weighs nothing on any one point. Fix the paintings through gaps in the feathers.' },
      { k: 'Light', v: 'A strip behind each feather eye (12 V, 2700 K) makes the eyes glow at night. Add spots for the paintings.' },
      { k: 'Protect', v: 'Keep metal edges 3 cm from the frames, and round every edge at the fabricator.' },
      { k: 'Cost', v: '₹35k–1L. 3–4 weeks.' },
      { k: 'Why', v: 'It takes a detail the three paintings share and builds the whole wall from it.' },
    ],
  },
  {
    id: 'gau',
    title: 'Gau Frieze',
    hook: 'The gold cows walking round Shrinathji\'s border come out of the frame and walk round the room.',
    tags: ['heritage', 'diy'],
    cost: [25, 80], level: 1, weeks: '1–3 weeks', wall: 300,
    points: [
      { k: 'Layout', v: 'A 25 cm band at dado height (90–115 cm) running the full wall, or the whole room, of cows walking toward the centre painting. The paintings hang above the band.' },
      { k: 'Make', v: 'Either: hand-painted in gold on an indigo band; or: carved MDF or wooden cows, 18 cm tall, gilded with imitation gold leaf and fixed onto the band.' },
      { k: 'Who', v: 'A sign-painter or Nathdwara painter for the painted version, and a CNC shop plus gilder for the relief version. Stencils make it a DIY job.' },
      { k: 'Hang', v: 'Fix the relief cows with construction adhesive and two pins each.' },
      { k: 'Light', v: 'A slim LED in a 2 cm shadow-gap above the band makes the gold glow at sofa height.' },
      { k: 'Protect', v: 'At knee height the band will take knocks. Use a varnish over gilding, or choose the painted version.' },
      { k: 'Cost', v: '₹25–80k. 1–3 weeks.' },
      { k: 'Why', v: 'It takes Pushtimarg\'s cows, the ones of Shrinathji\'s childhood as a cowherd, as the trim for the room.' },
    ],
  },
  {
    id: 'memory',
    title: 'Ancestral Memory Salon',
    hook: 'The three paintings at the heart of a wall that tells the story of the house they came from.',
    tags: ['diy', 'renter'],
    cost: [15, 50], level: 1, weeks: '1–2 weeks', wall: 260,
    points: [
      { k: 'Layout', v: 'The triptych at the centre. Around it, keeping 6 cm gaps and a common outer edge, a salon hang of 8–12 small things: photographs of the old house, its key or knocker in a shadow box, an enlarged print of the artist\'s signature ("अमृतलाल शर्मा नाथद्वारा") and a family note on where the paintings hung.' },
      { k: 'Make', v: 'Simple 2 cm frames in one or two finishes (black and brass), with all mats in the same off-white. Objects go in 5 cm deep shadow boxes with linen backs.' },
      { k: 'Who', v: 'You and a framer. Plan it on the floor with kraft-paper templates first, then tape the templates to the wall.' },
      { k: 'Hang', v: 'Picture rail with cables (renter-friendly), or small security hangers. Lay out from the centre outward.' },
      { k: 'Light', v: 'Wall-washer at 30°, which is easier than spotting many small frames.' },
      { k: 'Protect', v: 'Print copies of old photos and keep the originals in archival sleeves. Light fades a photo as fast as a painting.' },
      { k: 'Cost', v: '₹15–50k. 1–2 weeks.' },
      { k: 'Why', v: 'Nobody else has these objects, and the people you love end up in the frame.' },
    ],
  },
  {
    id: 'single',
    title: 'One Frame, Three Darshans',
    hook: 'One long frame with a hand-painted gold border around all three, so they read as a single piece.',
    tags: ['statement'],
    cost: [25, 70], level: 1, weeks: '2–3 weeks', wall: 220,
    points: [
      { k: 'Layout', v: 'One frame about 200 × 95 cm with three windows cut in a single indigo mat, 8 cm between windows and 12 cm margins.' },
      { k: 'Make', v: 'Cover the mat in hand-dyed indigo silk over acid-free board. A painter adds a thin gold line and a kundan-style dotted band around the windows, picking up the paintings\' own borders. The frame is 5 cm gilded wood, with UV-filtering anti-reflective acrylic (lighter than glass at this size).' },
      { k: 'Who', v: 'A conservation framer for the mat and glazing; a Nathdwara or miniature painter for the gold border.' },
      { k: 'Hang', v: 'A full-width aluminium French cleat. The frame weighs about 15–20 kg with acrylic.' },
      { k: 'Light', v: 'Two spots, or one 40° flood.' },
      { k: 'Protect', v: 'The paintings are hinged to the backing, never glued. Raised gold needs a 15 mm spacer between mat and glazing.' },
      { k: 'Cost', v: '₹25–70k. 2–3 weeks.' },
      { k: 'Why', v: 'Three separate gifts presented together as one heirloom.' },
    ],
  },
  {
    id: 'kota',
    title: 'Kota Stone & Brass Float',
    hook: 'Honed stone slabs, brass standoffs and nothing else: heritage pieces on a quiet modern wall.',
    tags: ['modern'],
    cost: [30, 90], level: 2, weeks: '2–3 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'An accent panel of 60 × 60 cm honed Kota stone (blue-grey) or Jaisalmer yellow slabs across the sofa wall. The three float 4 cm off it on four brass standoffs each, in a straight line.' },
      { k: 'Make', v: '18–20 mm slabs, honed matt, laid on adhesive with 2 mm joints. Brass standoffs 25 mm diameter. Frames are thin black or brass, with glazing.' },
      { k: 'Who', v: 'A stone-cladding contractor and a framer. Plan the standoff holes on the slab layout so no hole lands on a joint.' },
      { k: 'Hang', v: 'Drill through stone with diamond bits into the wall behind. Each standoff bolt goes into an anchor in the wall itself, not the stone.' },
      { k: 'Light', v: 'Graze the stone from above with a ceiling recess, plus spots for the paintings, so the texture shows next to the gold.' },
      { k: 'Protect', v: 'Stone walls run cool; check for condensation in the monsoon before hanging. A hygrometer behind a frame for a week will tell you.' },
      { k: 'Cost', v: '₹30–90k. 2–3 weeks.' },
      { k: 'Why', v: 'The gold looks richer against grey stone than against paint.' },
    ],
  },
  {
    id: 'bluepottery',
    title: 'Jaipur Blue Pottery Surround',
    hook: 'A panel of hand-painted blue pottery tiles: cobalt and turquoise to echo Shrinathji\'s royal-blue ground.',
    tags: ['heritage'],
    cost: [30, 80], level: 2, weeks: '4–6 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'A 230 × 120 cm field of 10 cm tiles with a three-tile border; the paintings hang on a plain white tile field in the middle so the pattern frames them rather than competing.' },
      { k: 'Make', v: 'Jaipur blue pottery is quartz-based (not clay) and hand-painted in cobalt and copper-oxide blues. Order flat-backed tiles with a little spare for breakages.' },
      { k: 'Who', v: 'Blue pottery workshops in Jaipur (Sanganer, Amer Road). Send a tile layout and they paint to order.' },
      { k: 'Hang', v: 'Tile adhesive on a primed wall, grouted white. The paintings hang on standoffs through planned grout-line holes.' },
      { k: 'Light', v: 'Glaze is shiny, so use spots at 30° or steeper to keep reflections out of the sofa\'s eye line.' },
      { k: 'Protect', v: 'Nothing special for the tiles; normal UV glazing on the paintings.' },
      { k: 'Cost', v: '₹30–80k. 4–6 weeks.' },
      { k: 'Why', v: 'Another Rajasthani craft that comes in the same blue as Shrinathji\'s ground.' },
    ],
  },
  {
    id: 'pietra',
    title: 'Parchin Kari Marble Frames',
    hook: 'White marble frames inlaid with stone lotuses: the Taj Mahal\'s technique, around the paintings.',
    tags: ['heritage', 'statement'],
    cost: [150, 500], level: 3, weeks: '8–16 weeks', wall: 200,
    points: [
      { k: 'Layout', v: 'Standard triptych spacing. Each frame is 10 cm wide Makrana marble with an inlaid lotus vine in carnelian, malachite and lapis or their cheaper stand-ins.' },
      { k: 'Make', v: 'Parchin kari (pietra dura): cut stones set into channels cut in marble. To save weight, make 15 mm thick marble face pieces glued onto a hardwood frame core.' },
      { k: 'Who', v: 'Inlay workshops in Agra. Ask whether stones are natural or reconstituted, and price both.' },
      { k: 'Hang', v: 'Even veneered, each frame weighs 12–20 kg. Use security cleats into brick or RCC.' },
      { k: 'Light', v: 'Spots at 30°. The inlay glows best with light from a slight side angle.' },
      { k: 'Protect', v: 'Order the frames slightly oversize and fit the painting in a separate inner tray. That way the painting never takes the marble\'s weight, and can be removed safely.' },
      { k: 'Cost', v: '₹1.5–5L for three. 8–16 weeks.' },
      { k: 'Why', v: 'Frames meant to outlast the house, the way the paintings outlasted the old one.' },
    ],
  },
  {
    id: 'screen',
    title: 'Three-Panel Darshan Screen',
    hook: 'A folding carved screen with one painting per panel: a room divider by day, a shrine when you angle it.',
    tags: ['renter', 'heritage'],
    cost: [50, 150], level: 2, weeks: '4–6 weeks', wall: 0,
    points: [
      { k: 'Layout', v: 'Three panels, each 60 × 190 cm, hinged in a shallow zigzag. Each painting sits at 150 cm on its panel. The back is open jaali, so the dining side sees carved lattice.' },
      { k: 'Make', v: 'Solid wood frames with plywood panels where the paintings sit, the paintings in recessed glazed trays, double-action screen hinges, and felt feet.' },
      { k: 'Who', v: 'Furniture carvers in Jodhpur and Saharanpur make folding screens to order.' },
      { k: 'Hang', v: 'Freestanding, but the zigzag must be at least 30° per fold for stability. Add a floor-pin socket if children or pets are about.' },
      { k: 'Light', v: 'A floor uplight behind, or one spot per panel from the ceiling once you settle its place.' },
      { k: 'Protect', v: 'Movement is the risk for glued kundan: fit paintings with corner-pocket supports so they can\'t shift in the tray.' },
      { k: 'Cost', v: '₹50k–1.5L. 4–6 weeks.' },
      { k: 'Why', v: 'It works in any home you ever live in and needs no wall at all.' },
    ],
  },
  {
    id: 'canopy',
    title: 'Chandarvo Canopy',
    hook: 'A cloth canopy over the paintings, like the chandarvo above the deity in a haveli, with tied-back curtains below it.',
    tags: ['heritage', 'renter', 'diy'],
    cost: [20, 60], level: 1, weeks: '1–3 weeks', wall: 240,
    points: [
      { k: 'Layout', v: 'A 240 cm wide, 35 cm deep fabric canopy at 230 cm with a scalloped, tasselled front, and side curtains tied back with gota cords. The paintings hang beneath in a straight line.' },
      { k: 'Make', v: 'Silk or cotton velvet in deep red or indigo, with gota-patti (gold ribbon) embroidery. Put the canopy on a 12 mm brass rod frame with two wall brackets; the curtains slide on a brass rail.' },
      { k: 'Who', v: 'A tailor or soft-furnishings shop; gota work from Jaipur or Ajmer embroiderers.' },
      { k: 'Hang', v: 'Two curtain-rod brackets. The paintings hang separately.' },
      { k: 'Light', v: 'A warm LED strip tucked inside the canopy\'s front valance lights the paintings like a lamp.' },
      { k: 'Protect', v: 'Keep curtains 10 cm clear of frames. Close them when you are away: free light protection.' },
      { k: 'Cost', v: '₹20–60k. 1–3 weeks.' },
      { k: 'Why', v: 'It suits festival decorating: change the cloth for Diwali, Holi and Janmashtami.' },
    ],
  },
  {
    id: 'ledges',
    title: 'Stepped Ledges',
    hook: 'Three walnut ledges at stepped heights, Shrinathji highest. Barely any drilling, and easy to rearrange.',
    tags: ['renter', 'diy', 'modern'],
    cost: [8, 25], level: 1, weeks: '1 week', wall: 220,
    points: [
      { k: 'Layout', v: 'Three ledges 60 cm long, 9 cm deep, with a 2 cm brass lip. Centre ledge at 140 cm, sides at 125 cm. Each painting stands on its ledge leaning 5°, held by a clear safety clip at the top.' },
      { k: 'Make', v: 'Solid walnut or teak, oiled, with a brass strip let into the lip. Set a small brass urli with floating flowers on one side ledge, in a tray so spills don\'t reach the paintings.' },
      { k: 'Who', v: 'A carpenter, or ready-made picture ledges with brass trim added.' },
      { k: 'Hang', v: 'Only 2–3 screws per ledge. A clear acrylic clip at the top of each frame keeps it from tipping forward.' },
      { k: 'Light', v: 'A slim under-cabinet LED under each ledge, shining down, lights the ledge below; ceiling spots for the faces.' },
      { k: 'Protect', v: 'Glazed frames are required: leaning art collects dust in the lip, so wipe weekly.' },
      { k: 'Cost', v: '₹8–25k. One week.' },
      { k: 'Why', v: 'It leaves the arrangement open: you can add a new painting or a seasonal flower without drilling.' },
    ],
  },
  {
    id: 'halo',
    title: 'Halo Float',
    hook: 'Black shadow boxes floating off the wall, with light spilling round their edges like an aura.',
    tags: ['modern', 'diy'],
    cost: [25, 60], level: 1, weeks: '1–2 weeks', wall: 200,
    points: [
      { k: 'Layout', v: 'Triptych at 150 cm with 10 cm gaps. Each painting in a 6 cm deep matte-black shadow box, floated 4 cm off the wall on a hidden cleat.' },
      { k: 'Make', v: 'Use a 4–5 W/m, 2700 K LED strip fixed around the back of each box, 3 cm in from the edge, with an aluminium channel and diffuser. One driver feeds all three through a hidden conduit to a single switch.' },
      { k: 'Who', v: 'A framer for the boxes and an electrician for the conduit. It is DIY-able if you\'re handy.' },
      { k: 'Hang', v: 'A cleat on a 4 cm spacer block, so the box floats and the glow can escape on all four sides.' },
      { k: 'Light', v: 'The halo is for mood, not for seeing the painting. Add a dimmed spot or picture light for the faces.' },
      { k: 'Protect', v: 'The strip runs cool, but keep it on the box, not on the painting\'s backing board.' },
      { k: 'Cost', v: '₹25–60k. 1–2 weeks.' },
      { k: 'Why', v: 'The halos in the paintings carry on as light round the frames.' },
    ],
  },
  {
    id: 'echo',
    title: 'Archive & Echo',
    hook: 'Museum-grade scans hang in the bright room; the originals live where light can\'t reach them.',
    tags: ['protective', 'modern'],
    cost: [15, 45], level: 1, weeks: '2 weeks', wall: 200,
    points: [
      { k: 'Layout', v: 'Hang full-size giclée reproductions, with a raised-gold effect if you want it, wherever the light is best: by a window, above a sofa that gets afternoon sun. Hang the originals in a north-facing hallway or bedroom, or keep them in archival storage.' },
      { k: 'Make', v: 'Scan at 600 ppi with raking-light capture so the embossing shows, and print with pigment inks on cotton rag. Keep the scan files as the family\'s digital archive too.' },
      { k: 'Who', v: 'Fine-art scanning studios in most metros; ask for a colour-calibrated scan and proof before the full print.' },
      { k: 'Hang', v: 'Use whichever of the other ideas you like for the copies; there\'s no conservation constraint.' },
      { k: 'Light', v: 'As bright as you like on the copies.' },
      { k: 'Protect', v: 'Nothing beats this for the originals. Combine it with the Seasonal Rotation to bring them out at festivals.' },
      { k: 'Cost', v: '₹15–45k for scans and three prints. 2 weeks.' },
      { k: 'Why', v: 'It keeps the actual heirloom safe for the next generation while the wall still gets its darshan.' },
    ],
  },
];

/** Fundamentals that apply to every idea. */
export const BASICS: { title: string; body: string }[] = [
  { title: 'Hang them so they look at each other', body: 'In your photos the acharya faces right and Krishna faces left, holding out his lotus garland. Put the acharya on the left and Krishna on the right, and both turn toward Shrinathji in the middle. Swap them and both look away out of the room.' },
  { title: 'Centre at 145–152 cm', body: 'Galleries put the centre of a picture at about 145–152 cm (57–60 in) from the floor. Above a sofa, leave 20–30 cm between the sofa back and the bottom of the frames. The whole group should span about 60–75% of the sofa\'s width.' },
  { title: 'Glass that never touches', body: 'The raised gold and kundan stones are higher than the paper, so glass resting on them will crush and rub them. Use spacers or a deep mat (10–15 mm), and UV-filtering anti-reflective glass or acrylic (for example Tru Vue Museum Glass or Optium Museum Acrylic, or a local equivalent).' },
  { title: 'Light: warm, dim, angled', body: 'Use LEDs at 2700–3000 K with CRI 95 or more. Aim them at about 30° from vertical so the reflection lands on the floor, not in your eyes. Museums light watercolour and gouache on paper at about 50 lux, and many homes go to 100–150. Use a dimmer and switch off when you\'re out. Never put the paintings in direct sun.' },
  { title: 'Steady air', body: 'Keep the humidity at 40–60% and steady. Not above a radiator, AC outlet or kitchen door, and not on an outside wall that sweats in the monsoon. A ₹500 hygrometer tells you in a week.' },
  { title: 'No flame under paper', body: 'A real diya or incense below the paintings deposits soot and heat on paper and gold within months. Keep the lamp at least 60 cm to the side, or use an LED diya on the ledge.' },
  { title: 'Fix to the wall, not the frame', body: 'Use French cleats or two-point security hangers, never a single wire on a nail. Use 8 mm plugs in brick and toggle anchors in drywall. A glazed 50 × 70 cm painting weighs 6–10 kg.' },
  { title: 'Check the stones first', body: 'Before you reframe, check every kundan stone with a soft brush. Loose ones need re-fixing with a reversible conservation adhesive. That is a job for a paper conservator (INTACH runs conservation centres), not superglue.' },
];
