import type { Face, Look, Who } from './mascot';
import type { Pose } from './poses';
import type { PropOpts } from './props';

/**
 * A hundred rounds of NaMo vs RaGa.
 *
 * Every line here is invented, written for the toys, and neither man said
 * any of it. The ground rules: both get teased about the things they are
 * famous for and both land their jabs; nobody gets a nickname; nothing about
 * religion, caste or anybody's family; nothing more violent than a pillow.
 * The winners come out even — 25 each — and the other fifty go to the chai,
 * the rain, the voter, ISRO, and so on.
 */

export type Setting =
  | 'street' | 'desert' | 'snow' | 'beach' | 'stadium' | 'hall' | 'kitchen' | 'rooftop' | 'space' | 'river'
  | 'mela' | 'garden' | 'studio' | 'gym' | 'station' | 'stage' | 'road' | 'rain' | 'night' | 'office' | 'farm';
export type Held = string | [string, PropOpts];
/** [prop, x, z, rotation, options, height] */
export type Spot = [string, number, number, number?, PropOpts?, number?];

export interface Side {
  pose: Pose;
  face: Face;
  look?: Look;
  hold?: Held;
  holdL?: Held;
  /** [x, z, facing] */
  at?: [number, number, number];
  lift?: number;
  phase?: number;
}
export interface Bout {
  n: number;
  title: string;
  set: Setting;
  m: Side;
  r: Side;
  props?: Spot[];
  lines: [Who, string][];
  /** 'm', 'r', 'Draw', or whoever else won. */
  win: Who | string;
  fly?: { from: Who | 'both'; prop: Held };
  tether?: 'rope' | 'kites';
}

const s = (pose: Pose, face: Face, more: Partial<Side> = {}): Side => ({ pose, face, ...more });
const L = (...lines: string[]): [Who, string][] => lines.map((l) => [l[0] as Who, l.slice(2)]);
const FACE_OFF_M: [number, number, number] = [-0.95, 0.3, Math.PI / 2];
const FACE_OFF_R: [number, number, number] = [0.95, 0.3, -Math.PI / 2];

const RAW: Omit<Bout, 'n'>[] = [
  { title: 'Chai Pe Charcha', set: 'street', props: [['stall', 0, -1.4, 0, { text: 'CHAI ₹10' }]],
    m: s('hold', 'smug', { hold: 'chai' }), r: s('hold', 'grin', { hold: 'chai' }),
    lines: L('m I sold chai before it was cool.', 'r And I have had chai at every dhaba from Kanyakumari to Kashmir.', 'm Paid for all of it?', 'r UPI. Your idea. I’ll allow it.'), win: 'Chai' },
  { title: 'Selfie-Off', set: 'garden',
    m: s('selfie', 'grin', { hold: 'selfie' }), r: s('selfie', 'wink', { hold: 'selfie' }),
    lines: L('m Two hundred world leaders in my camera roll.', 'r Four thousand kilometres of strangers in mine.', 'm Mine are verified.', 'r Mine are voters.'), win: 'r' },
  { title: 'Yatra vs Yoga', set: 'garden', props: [['mat', -1.15, 0.2, 0.75]],
    m: s('tree', 'calm'), r: s('march', 'grin'),
    lines: L('m I stood still and got the whole world doing yoga.', 'r I kept walking and got the whole country talking.', 'm Namaste.', 'r Thak gaye? Walk with me.'), win: 'm' },
  { title: 'The Winter T-Shirt', set: 'snow',
    m: s('hold', 'worried', { hold: 'chai', look: { hat: 'wool', acc: ['scarf'], outfit: 2 } }), r: s('flex', 'grin'),
    lines: L('m Beta, it’s minus four. Jacket pehno.', 'r The cold is a state of mind.', 'm So is the cough you’ll have tomorrow.'), win: 'The cold' },
  { title: 'Chest Day', set: 'gym', props: [['dumbbell', -2.2, -0.6, 0.4], ['dumbbell', 2.2, -0.5, -0.3]],
    m: s('flex', 'smug'), r: s('flex', 'determined', { look: { hat: 'headband' } }),
    lines: L('m Fifty-six inches. Measure it.', 'r Aikido black belt. Want a demo?', 'm I prefer yoga. Less falling.'), win: 'Draw' },
  { title: 'Mann Ki Baat', set: 'studio',
    m: s('mic', 'smile', { hold: 'mic', look: { outfit: 1 } }), r: s('hold', 'smug', { hold: ['placard', { text: 'TAKING\nCALLS?' }] }),
    lines: L('m Every month, on the radio, straight to the nation.', 'r Do you ever take calls?', 'm The lines are… very busy.'), win: 'r' },
  { title: 'Press Conference', set: 'studio', props: [['podium', 1.1, 0.5, -0.3, { text: 'PRESS' }]],
    m: s('cross', 'smug', { look: { outfit: 3 } }), r: s('mic', 'grin', { hold: 'mic', at: [1.15, -0.25, -0.3] }),
    lines: L('r I held a press conference today.', 'm I gave an interview today.', 'r To whom?', 'm A very well-prepared journalist.'), win: 'r' },
  { title: 'The Hug', set: 'hall',
    m: s('hips', 'shock', { look: { outfit: 1 } }), r: s('hug', 'love', { at: [0.75, 0.3, -1.1] }),
    lines: L('r Come here, you.', 'm Not in the House!', 'r Too late.'), win: 'Awkwardness' },
  { title: 'Kai Po Che!', set: 'rooftop', tether: 'kites',
    props: [['kite', -1.7, -1.4, 0.2, { color: '#e8392a' }, 3.3], ['kite', 1.6, -1.6, -0.2, { color: '#3ab8ff', alt: '#ffffff' }, 3.7]],
    m: s('kite', 'determined', { holdL: 'reel' }), r: s('kite', 'grin', { holdL: 'reel' }),
    lines: L('m Gujarat taught me kites. Kai po che!', 'r Then why is your manjha round my ankle?', 'm Strategy.'), win: 'm' },
  { title: 'The Yorker of Development', set: 'stadium', props: [['stumps', 1.6, -0.6]], fly: { from: 'm', prop: 'ball' },
    m: s('throw', 'determined'), r: s('swing', 'grin', { hold: 'bat', look: { hat: 'cap' } }),
    lines: L('m Here comes the yorker of development!', 'r And it’s… a wide.', 'm Third umpire!'), win: 'r' },
  { title: 'Home Ground', set: 'stadium', props: [['stumps', -1.6, -0.6]], fly: { from: 'r', prop: 'ball' },
    m: s('swing', 'smug', { hold: 'bat', look: { hat: 'cap', outfit: 4 } }), r: s('throw', 'grin'),
    lines: L('m This stadium has my name on it. I don’t get out here.', 'r Howzaat!', 'm Not out. The umpire agrees.', 'r The umpire is wearing your jacket.'), win: 'r' },
  { title: 'Arm Wrestle', set: 'hall', props: [['table', 0, 0.3, Math.PI / 2]],
    m: s('wrestle', 'angry', { at: FACE_OFF_M }), r: s('wrestle', 'determined', { at: FACE_OFF_R }),
    lines: L('m Double engine power!', 'r Four thousand kilometres of forearm!', 'm The table is cracking…', 'r Adjourn the House!'), win: 'Draw' },
  { title: 'Tug of War', set: 'road', tether: 'rope',
    m: s('tug', 'determined', { at: [-1.5, 0.35, Math.PI / 2] }), r: s('tug', 'angry', { at: [1.5, 0.35, -Math.PI / 2] }),
    lines: L('m Pull… for Viksit Bharat!', 'r Pull… for the Constitution!', 'm It’s the same rope!', 'r Then why are we pulling?'), win: 'The rope' },
  { title: 'Pillow Fight', set: 'night', props: [['charpai', 0, -1.3, Math.PI / 2]],
    m: s('swing', 'laugh', { hold: 'pillow' }), r: s('swing', 'grin', { hold: ['pillow', { color: '#ffe8a8' }] }),
    lines: L('m Eighteen-hour days. I haven’t slept since 2014!', 'r Then this pillow is a gift.', 'm Accepted — and returned!'), win: 'm' },
  { title: 'Bura Na Mano, Holi Hai', set: 'garden', fly: { from: 'both', prop: ['balloon', { color: '#ff3a9a' }] },
    m: s('throw', 'laugh', { look: { outfit: 1 } }), r: s('throw', 'shock'),
    lines: L('m Bura na mano, Holi hai!', 'r My white T-shirt!', 'm It’s saffron now. An upgrade.', 'r Yours is blue and green. Coalition colours!'), win: 'Everyone, in colour' },
  { title: 'Garba Night', set: 'mela',
    m: s('dance', 'grin', { hold: 'dandiya', holdL: 'dandiya', look: { outfit: 2, hat: 'pagdi' } }), r: s('dance', 'grin', { hold: 'dandiya', holdL: 'dandiya', look: { outfit: 1 }, phase: 0.3 }),
    lines: L('m Garba is my home turf, beta.', 'r I learned on the Yatra, uncle ji.', 'm You are off the beat.', 'r I am freestyle.'), win: 'm' },
  { title: 'MasterChef Mutton', set: 'kitchen', props: [['stove', 0.2, -1.0]],
    m: s('think', 'smug', { look: { outfit: 4 } }), r: s('stir', 'grin', { hold: 'ladle', look: { hat: 'chef', acc: ['apron'] }, at: [0.9, -0.3, -0.5] }),
    lines: L('r Mutton, the way Lalu ji taught me.', 'm Khichdi. Healthy, national, and nobody complains.', 'r Nobody dares.'), win: 'The dishwasher' },
  { title: 'The Jalebi Factory', set: 'mela', props: [['stall', 0, -1.4, 0, { text: 'JALEBI', color: '#e8a02a' }]],
    m: s('laugh', 'laugh'), r: s('hold', 'grin', { hold: 'jalebi' }),
    lines: L('r Imagine: jalebis, from a factory, exported worldwide!', 'm Beta, jalebis are made in a kadhai.', 'r Then a kadhai factory!', 'm Now you’re thinking like me.'), win: 'm' },
  { title: 'Mohabbat Ki Dukaan', set: 'street', props: [['stall', 0.1, -1.4, 0, { text: 'MOHABBAT KI DUKAAN', color: '#e87aa8', alt: '#ffffff' }]],
    m: s('hips', 'smug', { look: { outfit: 3 } }), r: s('wave', 'love'),
    lines: L('r Free hugs, fresh love, open 24×7.', 'm Registered for GST?', 'r Love is exempt.'), win: 'r' },
  { title: 'Swachh Bharat', set: 'street', props: [['crate', 0.3, -1.3, 0.3, { color: '#3a9a4a' }]],
    m: s('sweep', 'determined', { hold: 'broom' }), r: s('point', 'laugh'),
    lines: L('m Swachh Bharat! Pick up that wrapper.', 'r That’s one of your pamphlets.', 'm Then it’s recyclable.'), win: 'r' },
  { title: 'Masterstroke', set: 'hall', props: [['chess', 0, 0.1]],
    m: s('think', 'smug', { at: [-0.95, 0.25, 1.2] }), r: s('think', 'worried', { at: [0.95, 0.25, -1.2] }),
    lines: L('m Masterstroke!', 'r You can’t call every move a masterstroke.', 'm Watch me. Masterstroke!', 'r That was my pawn.'), win: 'm' },
  { title: 'Point Two Hundred and Six', set: 'stage', props: [['chair', 1.2, -0.15, -0.5, { color: '#2a6ad8' }]],
    m: s('scroll', 'grin', { hold: 'scroll', look: { outfit: 7 } }), r: s('sleep', 'sleepy', { at: [1.25, -0.3, -0.5] }),
    lines: L('m …and in conclusion, point two hundred and six—', 'r Zzz… wake me at achhe din.', 'm That was point one.'), win: 'The audience (asleep)' },
  { title: 'The Long Walk', set: 'road',
    m: s('run', 'worried', { look: { hat: 'headband', outfit: 3 }, at: [-1.2, 0.5, 0.35] }), r: s('run', 'grin', { at: [1.1, 0.2, 0.35], phase: 0.2 }),
    lines: L('r Only 3,970 km to go!', 'm I’ll take the Vande Bharat and meet you there.', 'r Save me a seat. I’ll still walk.'), win: 'Draw' },
  { title: 'Vande Bharat', set: 'station', props: [['train', 0, -1.6]],
    m: s('point', 'smile', { look: { outfit: 1 } }), r: s('shrug', 'smug'),
    lines: L('m Made in India. Semi-high speed!', 'r Does it stop at my constituency?', 'm Which one this time?'), win: 'm' },
  { title: 'One Small Step', set: 'space', props: [['rocket', -2.3, -1.3], ['flag', 0.1, -0.9]],
    m: s('cheer', 'grin', { look: { hat: 'astro' } }), r: s('salute', 'grin', { look: { hat: 'astro' } }),
    lines: L('m India on the Moon’s south pole!', 'r Take a bow, ISRO — since 1969.', 'm I was with the scientists that night.', 'r So was all of India.'), win: 'ISRO' },
  { title: 'Frequent Flyers', set: 'station', props: [['toyplane', 0, -1.4, 0.3, {}, 2.6], ['suitcase', -2.1, -0.6, 0.4], ['suitcase', 2.2, -0.4, -0.3]],
    m: s('hold', 'grin', { hold: 'globe' }), r: s('hold', 'smug', { hold: 'phone' }),
    lines: L('m Sixty-plus countries. Every leader hugs me.', 'r I just go and talk to students abroad.', 'm And the holidays?', 'r Field research.'), win: 'Draw' },
  { title: 'Ladakh on Two Wheels', set: 'road', props: [['bike', 1.1, -0.3, -0.5], ['sign', -2.4, -1.6, 0.2, { text: 'PANGONG 5 KM', color: '#1a6a3a', alt: '#ffffff' }]],
    m: s('wave', 'smile', { look: { outfit: 3 } }), r: s('ride', 'grin', { look: { hat: 'helmet', outfit: 4 }, at: [1.06, -0.47, -0.5], lift: 0.58 }),
    lines: L('r Pangong Lake on two wheels!', 'm Helmet, beta. Rules are rules.', 'r Already on. Rules are rules.'), win: 'Road safety' },
  { title: 'Railway Veterans', set: 'station',
    m: s('hold', 'smile', { hold: 'kettle' }), r: s('carry', 'grin', { hold: 'suitcase', look: { outfit: 2, acc: ['armband'] } }),
    lines: L('m I sold chai on platforms like this one.', 'r I carried bags on this one.', 'm So we’re both railway veterans.', 'r Station master, you decide.'), win: 'Indian Railways' },
  { title: 'The Karol Bagh Mechanic', set: 'road', props: [['bike', 0.1, -1.2, 1.2]],
    m: s('think', 'smug', { look: { outfit: 2 } }), r: s('hold', 'grin', { hold: 'wrench', look: { outfit: 5 } }),
    lines: L('r I learned to fix bikes in Karol Bagh.', 'm Good. Fix your party next.', 'r One cylinder at a time.'), win: 'm' },
  { title: 'Make in India Toys', set: 'garden', props: [['blocks', 0, -1.0]],
    m: s('hold', 'grin', { hold: ['placard', { text: 'MADE IN\nINDIA' }] }), r: s('think', 'smug', { hold: 'ball' }),
    lines: L('m Make in India toys!', 'r Lovely. Batteries included?', 'm Those too — next year.'), win: 'Draw' },
  { title: 'Scan and Pay', set: 'street', props: [['stall', 0, -1.4, 0, { text: 'SCAN & PAY', color: '#1a4aa8', alt: '#ffd23f' }]],
    m: s('hold', 'grin', { hold: 'phone', look: { outfit: 1 } }), r: s('hold', 'smile', { hold: 'phone' }),
    lines: L('m Scan and pay — even at the chai stall!', 'r My Mohabbat ki Dukaan takes UPI too.', 'm Then pay the rent.', 'r Payment failed. Server busy.'), win: 'Draw' },
  { title: 'Paint the Wall', set: 'street', props: [['wall', 0, -1.3]],
    m: s('hold', 'smug', { hold: 'roller' }), r: s('hold', 'grin', { hold: ['roller', { color: '#3a8ae8' }] }),
    lines: L('m Saffron looks lovely on this wall.', 'r Sky blue is the future.', 'm Where they meet, it’s gone green.', 'r Everybody wins?'), win: 'The wall (now green)' },
  { title: 'Mitron vs Doston', set: 'stage',
    m: s('mic', 'grin', { hold: 'megaphone' }), r: s('mic', 'grin', { hold: 'megaphone', look: { outfit: 4 } }),
    lines: L('m Mitron!', 'r Doston!', 'm That’s the same word.', 'r Branding matters.'), win: 'r' },
  { title: 'One Umbrella', set: 'rain',
    m: s('hold', 'smug', { hold: 'umbrella', look: { outfit: 3 } }), r: s('shiver', 'worried', { at: [1.0, 0.1, -0.8] }),
    lines: L('m Monsoon session: the government has the umbrella.', 'r The rain votes too, you know.', 'm Fine. Come under.'), win: 'The rain' },
  { title: 'Snowball Fight', set: 'snow', props: [['snowman', 0, -1.6]], fly: { from: 'both', prop: 'snowball' },
    m: s('throw', 'laugh', { look: { hat: 'wool', acc: ['scarf'] } }), r: s('throw', 'grin'),
    lines: L('m From Kedarnath, with love!', 'r From Gulmarg, with more love!'), win: 'Draw' },
  { title: 'Beach Volleyball', set: 'beach', props: [['net', 0, -0.3, 1.15]], fly: { from: 'both', prop: ['ball', { color: '#ffd23f' }] },
    m: s('jump', 'determined', { look: { hat: 'sunhat', outfit: 3 } }), r: s('jump', 'grin', { phase: 1.0 }),
    lines: L('m Spike for Sagarmala!', 'r Blocked by the Opposition!', 'm Landed on your side. Point to the government.'), win: 'm' },
  { title: 'Vow of Silence', set: 'night', props: [['mat', -1.15, 0.2, 0.75, { color: '#e8872b' }], ['mat', 1.15, 0.2, -0.75, { color: '#f4f0e6' }]],
    m: s('meditate', 'calm', { look: { outfit: 6 } }), r: s('meditate', 'calm', { look: { outfit: 1 } }),
    lines: L('m Forty-five hours of silence.', 'r …', 'm Is he meditating or sulking?', 'r Both.'), win: 'Silence' },
  { title: 'Exam Warriors', set: 'hall', props: [['desk', 0, -1.2, 0, { text: 'EXAM HALL' }]],
    m: s('talk', 'grin', { hold: ['book', { color: '#1a4aa8' }] }), r: s('hold', 'smug', { hold: 'pen' }),
    lines: L('m Treat your exams like a festival!', 'r Unless the paper leaks.', 'm Next question.'), win: 'r' },
  { title: 'Laddoo Diplomacy', set: 'garden',
    m: s('hold', 'grin', { hold: 'laddoo', look: { outfit: 4 } }), r: s('hold', 'laugh', { hold: 'laddoo' }),
    lines: L('m Laddoos for every victory!', 'r Keep some back — counting isn’t over.', 'm I made extra.'), win: 'm' },
  { title: 'Filter Kaapi', set: 'street',
    m: s('hold', 'smug', { hold: 'chai' }), r: s('hold', 'grin', { hold: 'coffee' }),
    lines: L('m Coffee? Very foreign, beta.', 'r Filter kaapi. The South says hello.', 'm The South says vanakkam to me too.'), win: 'Draw' },
  { title: 'Push-Up Challenge', set: 'gym', props: [['mat', 1.1, 0.2, Math.PI / 2, { color: '#2a6ad8' }]],
    m: s('clap', 'laugh'), r: s('plank', 'determined', { at: [1.3, 0.2, -1.4] }),
    lines: L('r Push-ups with the students — let’s go!', 'm I do 108 Surya Namaskars before breakfast.', 'r Then get down here.'), win: 'r' },
  { title: 'Aikido Demo', set: 'gym', props: [['mat', 0.9, 0.1, 0, { color: '#e8d8a8' }]],
    m: s('shrug', 'smug', { look: { outfit: 3 } }), r: s('guard', 'determined', { look: { outfit: 3, acc: ['belt'] } }),
    lines: L('r Aikido black belt. Watch this throw!', 'm Did you just throw yourself?', 'r That’s advanced aikido.'), win: 'm' },
  { title: 'The Wink', set: 'hall',
    m: s('facepalm', 'worried', { look: { outfit: 1 } }), r: s('thumbs', 'wink'),
    lines: L('r *wink*', 'm The cameras saw that.', 'r That was the point.'), win: 'r' },
  { title: 'The Pinstripe Suit', set: 'stage',
    m: s('hips', 'smug', { look: { outfit: 5 } }), r: s('point', 'laugh'),
    lines: L('r Nice suit. Is that your name in the stripes?', 'm It was auctioned for charity!', 'r Suit-boot ki sarkar!'), win: 'r' },
  { title: 'Naamdaar vs Kaamdaar', set: 'hall',
    m: s('point', 'determined', { look: { outfit: 2 } }), r: s('shrug', 'smug'),
    lines: L('m Naamdaar!', 'r Kaamdaar… is that a dance move?', 'm It’s a lifestyle.'), win: 'm' },
  { title: 'The Teleprompter', set: 'stage', props: [['tv', -0.4, -1.5, 0.2, { text: 'PAUSE FOR\nAPPLAUSE', color: '#1a2a4a' }]],
    m: s('talk', 'grin', { look: { outfit: 7 } }), r: s('point', 'laugh'),
    lines: L('r Who is that screen for?', 'm The audience.', 'r It says “pause for applause”.', 'm …'), win: 'r' },
  { title: 'Dhol Wars', set: 'mela', props: [['dhol', -1.0, -0.55, 0.7], ['dhol', 1.0, -0.55, -0.7]],
    m: s('drum', 'laugh', { hold: 'stick', holdL: 'stick', at: [-1.2, 0.3, 0.7] }), r: s('drum', 'grin', { hold: 'stick', holdL: 'stick', at: [1.2, 0.3, -0.7] }),
    lines: L('m Dhol for Navratri!', 'r Dhol for everything!', 'm LOUDER!'), win: 'The neighbours (awake)' },
  { title: 'Kabaddi', set: 'stadium',
    m: s('crouch', 'determined'), r: s('run', 'grin', { at: [1.0, 0.4, -1.3] }),
    lines: L('r Kabaddi-kabaddi-kabaddi…', 'm Caught you!', 'r I have breath for four thousand kilometres!', 'm And I had the tackle.'), win: 'm' },
  { title: 'Penalty Shoot-Out', set: 'stadium', props: [['goal', -1.4, -0.9, 0.6]], fly: { from: 'r', prop: ['ball', { color: '#ffffff' }] },
    m: s('guard', 'determined', { look: { outfit: 3 }, at: [-1.2, -0.3, 0.7] }), r: s('kick', 'grin'),
    lines: L('r Shoot!', 'm Saved! Opposition mein dum nahi!', 'r It went in.', 'm Offside.'), win: 'm' },
  { title: 'Badminton', set: 'rooftop', props: [['net', 0, -0.3, 1.15]], fly: { from: 'both', prop: ['ball', { color: '#ffffff' }] },
    m: s('throw', 'determined', { hold: 'racket' }), r: s('throw', 'grin', { hold: 'racket', phase: 1.0 }),
    lines: L('m Smash!', 'r Out!', 'm Third umpire!', 'r It’s badminton, uncle ji.'), win: 'r' },
  { title: 'The Heatwave Grand Prix', set: 'desert', props: [['kart', -1.1, 0.4, 0.25, { text: 'NAMO', color: '#ff7a1a' }], ['kart', 1.1, 0.4, -0.25, { text: 'RAGA', color: '#3a8ae8' }]],
    m: s('ride', 'determined', { look: { hat: 'cowboy' }, at: [-1.19, 0.08, 0.25], lift: 0.12 }), r: s('ride', 'grin', { look: { hat: 'helmet' }, at: [1.19, 0.08, -0.25], lift: 0.12 }),
    lines: L('m Double engine, beta!', 'r Single engine, no brakes, all heart!', 'm Sirens!', 'r Floor it!'), win: 'The cops' },
  { title: 'Every Vote Counts', set: 'hall', props: [['ballotbox', 0, -1.1]],
    m: s('hold', 'smile', { hold: 'ballot' }), r: s('hold', 'smile', { hold: 'ballot' }),
    lines: L('m Every vote counts.', 'r So count every vote.', 'm Agreed. Twice, if you like.'), win: 'The voter' },
  { title: 'Photobomb', set: 'garden', props: [['tripod', 1.9, 1.3, -2.2]],
    m: s('namaste', 'smile', { look: { outfit: 2 } }), r: s('jump', 'laugh', { at: [0.7, -0.4, -0.6] }),
    lines: L('m One clean shot, please—', 'r Surprise!', 'm Retake.'), win: 'r' },
  { title: 'Ek Ped Maa Ke Naam', set: 'garden',
    m: s('plant', 'smile', { hold: 'sapling' }), r: s('plant', 'smile', { hold: 'sapling', phase: 1.2 }),
    lines: L('m Ek Ped Maa Ke Naam.', 'r And one for Mother Earth.', 'm Then there will be shade at the next debate.'), win: 'The trees' },
  { title: 'Flat-on-the-Floor-Asana', set: 'garden', props: [['mat', -1.15, 0.2, 0.75, { color: '#f08a2a' }], ['mat', 1.15, 0.2, Math.PI / 2, { color: '#3ab8ff' }]],
    m: s('tree', 'calm'), r: s('plank', 'worried', { at: [1.3, 0.2, -1.5] }),
    lines: L('m Bhujangasana. Easy!', 'r I’m doing flat-on-the-floor-asana.', 'm Hold it for five breaths.'), win: 'm' },
  { title: 'Antakshari', set: 'night', props: [['diyas', 0, -1.2]],
    m: s('mic', 'grin', { hold: 'mic', look: { outfit: 2 } }), r: s('mic', 'grin', { hold: 'mic' }),
    lines: L('m Antakshari! Your letter: M.', 'r Mohabbat… ki… dukaan…', 'm That’s not a song.', 'r It’s a movement.'), win: 'r' },
  { title: 'Chai Stall Wars', set: 'street', props: [['stall', -1.7, -1.3, 0.35, { text: 'NAMO CHAI' }], ['stall', 1.7, -1.3, -0.35, { text: 'MOHABBAT CHAI', color: '#e87aa8', alt: '#ffffff' }]],
    m: s('hold', 'grin', { hold: 'kettle' }), r: s('hold', 'grin', { hold: 'chai' }),
    lines: L('m Special chai, ten rupees!', 'r Mohabbat chai — free!', 'm Free? Who pays?', 'r The taxpayer… wait.'), win: 'm' },
  { title: 'Digital India', set: 'office', props: [['desk', 0, -1.2, 0, { text: 'DIGITAL INDIA' }], ['laptop', 0, -1.2, 0, {}, 0.745]],
    m: s('point', 'grin', { look: { outfit: 1 } }), r: s('hold', 'worried', { hold: 'phone' }),
    lines: L('m Everything is online now!', 'r Then why does my phone say “network busy”?', 'm Switch to 5G, beta. Made in India.'), win: 'm' },
  { title: 'Weather Report', set: 'studio',
    m: s('talk', 'grin', { look: { outfit: 3 } }), r: s('point', 'smug'),
    lines: L('m Clear skies. Achhe din ahead.', 'r Scattered showers of jumlas.', 'm Carry an umbrella of development.'), win: 'Draw' },
  { title: 'Bullet Train', set: 'station', props: [['sign', 0, -1.6, 0, { text: 'BULLET TRAIN\nCOMING SOON', color: '#1a4aa8', alt: '#ffffff' }]],
    m: s('point', 'grin'), r: s('march', 'smug'),
    lines: L('m Bullet train, coming soon!', 'r How soon?', 'm Soon soon.', 'r I’ll walk. It’s quicker.'), win: 'r' },
  { title: 'Next Stop, the Sun', set: 'space', props: [['sign', 0, -1.5, 0, { text: 'SUN →', color: '#f08a2a', alt: '#ffffff' }]],
    m: s('point', 'grin', { look: { hat: 'astro' } }), r: s('shrug', 'smile', { look: { hat: 'astro' } }),
    lines: L('m Moon: done. Sun: next!', 'r Pack sunscreen.', 'm SPF 56.'), win: 'ISRO' },
  { title: 'Same Bench', set: 'hall', props: [['bench', 0, -0.2]],
    m: s('sit', 'smug', { at: [-0.5, -0.42, 0.6] }), r: s('sit', 'grin', { at: [0.5, -0.42, -0.6] }),
    lines: L('m This seat is taken.', 'r Leader of the Opposition. Right here.', 'm Same bench, different sides.', 'r That’s democracy.'), win: 'Draw' },
  { title: 'The Red Book', set: 'hall',
    m: s('hold', 'smile', { hold: 'book', look: { outfit: 1 } }), r: s('hold', 'grin', { hold: 'book' }),
    lines: L('r I carry the Constitution everywhere.', 'm I bowed my head to it in Parliament.', 'r Then we agree?', 'm Don’t tell anyone.'), win: 'The Constitution' },
  { title: 'Tiranga', set: 'road', props: [['flagpole', 0, -1.4]],
    m: s('salute', 'determined'), r: s('salute', 'determined', { phase: 0 }),
    lines: L('m On this one, no banter.', 'r Agreed. Jai Hind.'), win: 'India' },
  { title: 'Birthday Cake', set: 'garden', props: [['cake', 0, -1.1]],
    m: s('wave', 'smile', { look: { outfit: 4 } }), r: s('clap', 'grin'),
    lines: L('m Happy birthday, beta!', 'r Thank you, uncle ji. Cake?', 'm Sugar-free only.', 'r It’s made with mohabbat.'), win: 'The cake' },
  { title: 'Naam Toh Suna Hoga', set: 'stage',
    m: s('laugh', 'laugh', { look: { outfit: 2 } }), r: s('hug', 'grin', { look: { outfit: 4 } }),
    lines: L('r Rahul. Naam toh suna hoga.', 'm Every film hero is called Rahul.', 'r Exactly. Main character energy.'), win: 'r' },
  { title: 'Dangal', set: 'desert', props: [['mud', 0, 0.1]],
    m: s('guard', 'determined'), r: s('guard', 'shock'),
    lines: L('m Dangal!', 'r Mud on my white T-shirt again!', 'm Call it camouflage.'), win: 'm' },
  { title: 'Sandcastles', set: 'beach', props: [['sandcastle', -1.1, -1.0], ['bridge', 1.2, -1.0]],
    m: s('hips', 'grin', { look: { hat: 'sunhat' } }), r: s('thumbs', 'grin', { look: { acc: ['shades'] } }),
    lines: L('m Central Vista, sand edition.', 'r Bharat Jodo bridge. It connects things.', 'm High tide in five minutes.'), win: 'The sea' },
  { title: 'Deep Dive', set: 'river', props: [['boat', -1.9, -1.3, 0.4]],
    m: s('namaste', 'calm', { look: { outfit: 6 } }), r: s('splat', 'grin', { look: { outfit: 5 } }),
    lines: L('r I dived in with the fishermen in Kollam!', 'm I went scuba diving at Dwarka.', 'r Race you to the bottom?', 'm Of the river, I hope.'), win: 'The fish' },
  { title: 'Ice Cream Summit', set: 'beach',
    m: s('hold', 'smile', { hold: 'icecream', look: { hat: 'sunhat' } }), r: s('hold', 'grin', { hold: 'icecream', look: { acc: ['shades'] } }),
    lines: L('m Amul. Gujarat’s finest.', 'r Kulfi. Made with love.', 'm It’s melting.', 'r So is the ice between us.'), win: 'Summer' },
  { title: 'The Mango Question', set: 'garden', props: [['tree', 0, -1.7, 0, { color: '#3f9a4a' }]],
    m: s('hold', 'smile', { hold: 'mango' }), r: s('mic', 'smug', { hold: 'mic' }),
    lines: L('r Non-political question: how do you eat a mango?', 'm Cut, sucked, both. Next question.', 'r That was the whole interview?', 'm It went viral.'), win: 'm' },
  { title: 'Fitness Challenge', set: 'gym',
    m: s('march', 'determined', { look: { hat: 'headband', outfit: 3 } }), r: s('flex', 'grin'),
    lines: L('m I accepted the fitness challenge!', 'r Challenge: answer three questions live.', 'm That’s cardio I don’t need.'), win: 'r' },
  { title: 'The Pothole', set: 'road', props: [['mud', 0, -0.6]],
    m: s('point', 'smug'), r: s('facepalm', 'worried'),
    lines: L('m I built these roads!', 'r Then who put this pothole here?', 'm The monsoon. It’s in the Opposition.'), win: 'The pothole' },
  { title: 'Meter Se Chalo', set: 'road', props: [['auto', 0.2, -1.3, 0.5]],
    m: s('hold', 'grin', { hold: ['placard', { text: 'METER\nDOWN' }] }), r: s('point', 'smug'),
    lines: L('r Bhaiya, meter se chalo.', 'm The meter is digital now. Scan to pay.', 'r It says surge pricing.', 'm Peak hours, beta.'), win: 'm' },
  { title: 'Up at Four', set: 'office', props: [['chair', 1.2, -0.15, -0.5]],
    m: s('hold', 'grin', { hold: 'clock', look: { outfit: 1 } }), r: s('sleep', 'sleepy', { at: [1.25, -0.3, -0.5] }),
    lines: L('m Up at four, working till midnight!', 'r I’m up at four too. Jet lag.', 'm Nap, beta. I’ll run the country.'), win: 'm' },
  { title: 'Beard-Off', set: 'stage', props: [['mirror', 0, -1.4]],
    m: s('think', 'smug'), r: s('think', 'smug'),
    lines: L('m White, neat, statesmanlike.', 'r Salt and pepper. Grown over four thousand kilometres.', 'm A Yatra beard.', 'r A beard with a manifesto.'), win: 'The barber (unemployed)' },
  { title: 'Ramp Walk', set: 'stage',
    m: s('march', 'grin', { look: { outfit: 7 } }), r: s('march', 'smug', { look: { outfit: 4, acc: ['shades'] }, phase: 0.5 }),
    lines: L('m The Modi jacket: a global brand.', 'r The white tee: a lifestyle.', 'm Where’s your jacket?', 'r Jackets are for people who feel the cold.'), win: 'Draw' },
  { title: 'Pagdi vs Topi', set: 'hall',
    m: s('salute', 'grin', { look: { hat: 'pagdi', outfit: 4 } }), r: s('namaste', 'smile', { look: { hat: 'topi', outfit: 1 } }),
    lines: L('m Independence Day turban, number eleven.', 'r Gandhi topi. Classics never go out of style.', 'm Colour?', 'r White goes with everything.'), win: 'Draw' },
  { title: 'The Magic Show', set: 'stage', props: [['crate', 0, -1.2, 0, { color: '#2a1a4a' }]],
    m: s('hold', 'grin', { hold: 'wand', look: { outfit: 5, acc: ['cape'] } }), r: s('point', 'smug'),
    lines: L('m Watch — a rabbit from the hat!', 'r Now make petrol prices disappear.', 'm That’s a different trick.'), win: 'r' },
  { title: 'Ujjwala', set: 'kitchen', props: [['gascyl', 0, -1.2]],
    m: s('hold', 'grin', { hold: 'cylinder' }), r: s('think', 'smug'),
    lines: L('m Ujjwala! A gas connection in every home.', 'r And the refill price?', 'm Subsidised.', 'r For whom?'), win: 'Draw' },
  { title: 'Hide and Seek', set: 'garden', props: [['bush', 1.0, -0.1]],
    m: s('think', 'worried', { look: { outfit: 3 } }), r: s('crouch', 'grin', { at: [1.25, -0.8, -0.6] }),
    lines: L('m Where’s the Opposition?', 'r Right behind you, since 2024.', 'm Found you!'), win: 'r' },
  { title: 'Spelling Bee', set: 'hall', props: [['podium', 0, -1.3, 0, { text: 'SPELL IT' }]],
    m: s('point', 'smug', { look: { outfit: 2 } }), r: s('think', 'worried'),
    lines: L('m Spell “Aatmanirbhar”.', 'r A-A-T-M… lifeline?', 'm No lifelines in governance.'), win: 'm' },
  { title: 'Kaun Banega Crorepati', set: 'studio', props: [['desk', 0, -1.2, 0, { text: 'HOT SEAT', color: '#4a2a8a' }]],
    m: s('think', 'worried'), r: s('talk', 'grin', { look: { outfit: 4 } }),
    lines: L('r For one crore: what’s the unemployment rate?', 'm Audience poll.', 'r The audience wants to phone a friend.'), win: 'r' },
  { title: 'Stand-Up Night', set: 'stage',
    m: s('think', 'smug', { look: { outfit: 7 } }), r: s('mic', 'grin', { hold: 'mic' }),
    lines: L('r Why did the jumla cross the road?', 'm To reach the other side of 2029.', 'r …That was my punchline.'), win: 'Comedy' },
  { title: 'Rock, Paper, Scissors', set: 'garden',
    m: s('point', 'determined'), r: s('point', 'grin'),
    lines: L('m Rock!', 'r Paper. I win.', 'm Best of 543.'), win: 'r' },
  { title: 'Bullseye', set: 'stadium', props: [['target', 0, -1.6]], fly: { from: 'both', prop: 'pen' },
    m: s('throw', 'determined'), r: s('throw', 'determined', { phase: 1.0 }),
    lines: L('m Bullseye: a five-trillion-dollar economy!', 'r That’s my target.', 'm Same target. India first.'), win: 'Draw' },
  { title: 'Surf’s Up', set: 'beach',
    m: s('hold', 'smug', { hold: 'chai', look: { hat: 'sunhat', outfit: 3 } }), r: s('hold', 'grin', { hold: 'surfboard', look: { acc: ['shades'] } }),
    lines: L('m Riding the wave of development!', 'r I ride actual waves.', 'm Mine is bigger.'), win: 'Draw' },
  { title: 'Need a Push?', set: 'snow', props: [['sled', -0.3, 0.4, 0.3]],
    m: s('ride', 'worried', { look: { hat: 'wool', acc: ['scarf'] }, at: [-0.3, 0.35, 0.3], lift: -0.06 }), r: s('hug', 'grin', { at: [0.7, -0.4, -0.3] }),
    lines: L('r Need a push, uncle ji?', 'm A coalition partner, finally!', 'r Just this once.'), win: 'm' },
  { title: 'Float Like a Lotus', set: 'gym', props: [['ropes', 0, 0]],
    m: s('guard', 'determined', { look: { acc: ['gloves'], hat: 'headband' }, at: [-0.9, 0.3, 1.2] }), r: s('guard', 'determined', { look: { acc: ['gloves'] }, at: [0.9, 0.3, -1.2] }),
    lines: L('m Float like a lotus…', 'r …sting like a hand.', 'm A clean fight.', 'r Rules of the House.'), win: 'Draw' },
  { title: 'Pani Puri Challenge', set: 'street', props: [['stall', 0, -1.4, 0, { text: 'PANI PURI', color: '#3a9a4a', alt: '#ffd23f' }]],
    m: s('hold', 'grin', { hold: 'puri' }), r: s('hold', 'laugh', { hold: 'puri' }),
    lines: L('m Seven down!', 'r Twelve. The Yatra built my appetite.', 'm Bhaiya, one more round.'), win: 'r' },
  { title: 'Shubh Deepavali', set: 'night', props: [['diyas', 0, -1.1], ['fireworks', 0, 0]],
    m: s('hold', 'smile', { hold: 'diya', look: { outfit: 2 } }), r: s('hold', 'smile', { hold: 'diya', look: { outfit: 1 } }),
    lines: L('m Shubh Deepavali!', 'r Happy Diwali. Go easy on the crackers.', 'm Green crackers only.', 'r Check the AQI.'), win: 'Delhi’s air' },
  { title: 'Delhi Traffic', set: 'road', props: [['auto', -1.9, -1.3, 0.5], ['kart', 1.9, -1.2, -0.5, { color: '#ffd21a' }]],
    m: s('think', 'worried'), r: s('march', 'grin'),
    lines: L('m Clear the road — convoy coming!', 'r Delhi traffic doesn’t care whose convoy.', 'm …Want to walk?', 'r Welcome to the Yatra.'), win: 'r' },
  { title: 'World Champions', set: 'stadium',
    m: s('cheer', 'grin', { hold: 'trophy' }), r: s('clap', 'grin', { look: { hat: 'cap' } }),
    lines: L('m World champions!', 'r Hands off, that’s the team’s trophy.', 'm Just holding it for the photo.'), win: 'Team India' },
  { title: 'Surya Ghar', set: 'rooftop', props: [['solar', 0, -1.2]],
    m: s('point', 'grin'), r: s('shrug', 'smug'),
    lines: L('m Rooftop solar! Free electricity!', 'r Then why is my fan so slow?', 'm Clean your fan, beta.'), win: 'm' },
  { title: 'Snakes and Ladders', set: 'garden', props: [['snakes', 0, 0.3]],
    m: s('point', 'grin', { at: [-1.6, -0.3, 0.8] }), r: s('laugh', 'laugh', { at: [1.6, -0.3, -0.8] }),
    lines: L('m Ladder to four hundred paar!', 'r Snake on two-forty.', 'm Still the highest square on the board.'), win: 'Draw' },
  { title: 'Musical Chairs', set: 'hall', props: [['chair', 0, -0.5, 0, { color: '#1a4aa8' }]],
    m: s('run', 'determined', { at: [-1.1, 0.3, 1.2] }), r: s('run', 'grin', { at: [1.1, 0.0, -1.9] }),
    lines: L('m Third term — the chair is mine!', 'r The music is still playing.', 'm Then play it faster.'), win: 'm' },
  { title: 'UDAN', set: 'rooftop', fly: { from: 'both', prop: 'plane' },
    m: s('throw', 'grin'), r: s('throw', 'grin', { phase: 1.0 }),
    lines: L('m UDAN: flights for everyone!', 'r Mine landed in Raebareli.', 'm Mine landed in Varanasi.'), win: 'Draw' },
  { title: 'Tractor Rally', set: 'farm', props: [['tractor', 1.5, -1.3, -0.5]],
    m: s('wave', 'smile', { look: { outfit: 7, hat: 'pagdi' } }), r: s('thumbs', 'grin', { look: { outfit: 5 } }),
    lines: L('r Tractor rally for the farmers!', 'm Mind the crops, beta.', 'r The crops are the point.'), win: 'The farmers' },
  { title: 'Truce Over Chai', set: 'street', props: [['bench', 0, -0.2]],
    m: s('rest', 'smile', { hold: 'chai', at: [-0.5, -0.42, 0.6] }), r: s('rest', 'smile', { hold: 'chai', at: [0.5, -0.42, -0.6] }),
    lines: L('m Same time next session?', 'r Bring the chai. I’ll bring the mohabbat.'), win: 'Democracy' },
  { title: 'The Grand Finale', set: 'stage', props: [['confetti', 0, 0], ['banner', 0, -2.0, 0, { text: 'ROUND 100', color: '#f2c230', alt: '#2a1a10' }]],
    m: s('bow', 'smile', { look: { acc: ['garland'], outfit: 4 } }), r: s('bow', 'smile', { look: { acc: ['garland'] } }),
    lines: L('m Good fight, beta.', 'r Good fight, uncle ji. The people decide.'), win: 'The voter' },
];

export const BOUTS: Bout[] = RAW.map((b, i) => ({ ...b, n: i + 1 }));

export const NAMES: Record<Who, string> = { m: 'NaMo', r: 'RaGa' };
