/**
 * An English translation of the Bhagavad Gita, chapters 1–3, made for this
 * film from the Sanskrit. One string per verse, in order. Where a verse
 * has its speaker named in the Sanskrit, the film shows the speaker apart,
 * so the English begins with the words spoken.
 */
export const EN1: string[][] = [
  // 1 · Arjuna's despair
  [
    'On the field of dharma, the field of the Kurus, gathered together and eager to fight — what did my sons and the sons of Pandu do, Sanjaya?',
    'When he saw the army of the Pandavas drawn up for battle, King Duryodhana went to his teacher and spoke these words:',
    '“Look, teacher, at this vast army of the sons of Pandu, drawn up by the son of Drupada, your own gifted pupil.',
    'Here are heroes, great archers, equal in battle to Bhima and Arjuna: Yuyudhana, Virata, and Drupada, master of the great chariot;',
    'Dhrishtaketu, Chekitana and the valiant king of Kashi; Purujit, Kuntibhoja and Shaibya, a bull among men;',
    'bold Yudhamanyu and valiant Uttamaujas, the son of Subhadra and the sons of Draupadi — great chariot-warriors every one.',
    'Hear too, best of the twice-born, who are the foremost among us, the leaders of my army; I name them so you may know them:',
    'yourself and Bhishma, Karna and Kripa, victors in battle; Ashvatthama and Vikarna, and the son of Somadatta as well;',
    'and many other heroes who have given up their lives for my sake, armed with every kind of weapon, all of them skilled in war.',
    'Boundless is this strength of ours, guarded by Bhishma; but theirs, guarded by Bhima, has its measure.',
    'So hold your places, all of you, at every entry of the ranks, and above all keep Bhishma safe.”',
    'Then, to give him heart, the eldest of the Kurus, the mighty grandsire, roared out a lion’s roar and blew his conch.',
    'At once conches and kettledrums, tabors, drums and horns broke out together, and the sound was tremendous.',
    'Then, standing in their great chariot yoked to white horses, Madhava and the son of Pandu blew their divine conches.',
    'Hrishikesha blew Panchajanya, Dhananjaya blew Devadatta, and Bhima, wolf-bellied, terrible in deed, blew the great conch Paundra.',
    'King Yudhishthira, son of Kunti, blew Anantavijaya; Nakula and Sahadeva blew Sughosha and Manipushpaka.',
    'The king of Kashi, peerless archer, and Shikhandi of the great chariot, Dhrishtadyumna and Virata and Satyaki the unconquered,',
    'Drupada and the sons of Draupadi, O lord of the earth, and the strong-armed son of Subhadra — each on every side blew his own conch.',
    'That uproar, filling the sky and the earth with its echo, tore the hearts of the sons of Dhritarashtra.',
    'Then, seeing the sons of Dhritarashtra drawn up, as the weapons were about to fly, the son of Pandu whose banner bears the monkey raised his bow,',
    'and spoke these words to Hrishikesha, O lord of the earth. Arjuna said: Achyuta, set my chariot between the two armies,',
    'so that I may look at these men standing here hungry for battle, and see whom I must fight in this coming war.',
    'Let me see those who have gathered here to fight, to please in battle the wicked-minded son of Dhritarashtra.',
    'So addressed by Gudakesha, O Bharata, Hrishikesha set that finest of chariots between the two armies,',
    'before Bhishma and Drona and all the rulers of the earth, and said: “Partha, behold the Kurus gathered here.”',
    'And there Partha saw them standing: fathers and grandfathers, teachers, uncles, brothers, sons, grandsons and friends,',
    'fathers-in-law and companions, in both the armies. Seeing all these kinsmen standing there, the son of Kunti,',
    'filled with a great pity, said in sorrow: Krishna, when I see my own people here, eager to fight and drawn up for war,',
    'my limbs give way and my mouth is parched; my body trembles and my hair stands on end.',
    'Gandiva slips from my hand, my skin is burning; I cannot stand, and my mind seems to be whirling.',
    'I see evil omens, Keshava, and I see no good in killing my own people in battle.',
    'I do not want victory, Krishna, nor a kingdom, nor pleasures. What is a kingdom to us, Govinda, what are pleasures, or life itself?',
    'Those for whose sake we wanted a kingdom, pleasures and joys stand here in battle, having staked their lives and their wealth:',
    'teachers, fathers, sons and grandfathers, uncles, fathers-in-law, grandsons, brothers-in-law and other kin.',
    'I do not wish to kill them, Madhusudana, even if they kill me — not for the kingdom of the three worlds, let alone for the earth.',
    'What joy could be ours, Janardana, in killing the sons of Dhritarashtra? Only sin would cling to us for killing these aggressors.',
    'So we must not kill the sons of Dhritarashtra, our own kin. How could we be happy, Madhava, after killing our own people?',
    'Even if they, their minds overcome by greed, do not see the wrong in destroying a family and the crime in betraying a friend,',
    'why should we not know to turn away from this sin, Janardana — we who see clearly the wrong in destroying a family?',
    'When a family is destroyed, its age-old dharmas perish; when dharma is lost, lawlessness overwhelms the whole family.',
    'When lawlessness prevails, Krishna, the women of the family are corrupted; and when the women are corrupted, Varshneya, the orders of society are confounded.',
    'That confusion drags to hell the destroyers of the family and the family itself; their ancestors fall, deprived of the offerings of rice and water.',
    'By these wrongs of the family-destroyers, which confound the orders of society, the dharmas of caste and the lasting dharmas of the family are overthrown.',
    'For men whose family dharmas are overthrown, Janardana, a dwelling in hell without end awaits: so we have heard.',
    'Alas, what a great sin we were resolved to commit, ready to kill our own people out of greed for the pleasures of a kingdom!',
    'Better for me if the sons of Dhritarashtra, weapons in hand, should kill me in the battle unarmed and unresisting.',
    'Having spoken so on the battlefield, Arjuna sank down on the seat of his chariot, letting fall his bow and arrows, his mind overwhelmed with grief.',
  ],
  // 2 · The yoga of understanding
  [
    'To him, overcome with pity, his eyes troubled and full of tears, sinking in despair, Madhusudana spoke these words:',
    'Where has this faintness come upon you, Arjuna, at this hour of crisis? It is unworthy of a noble soul; it leads neither to heaven nor to honour.',
    'Do not give in to unmanliness, Partha; it does not become you. Cast off this petty weakness of heart and stand up, scorcher of foes!',
    'How can I fight Bhishma and Drona in battle with arrows, Madhusudana? They are worthy of worship, slayer of enemies.',
    'Better to live in this world on alms than to kill these teachers of great soul; for if I kill my teachers, however set on gain they are, every pleasure I enjoy here will be stained with blood.',
    'Nor do we know which is better for us — that we conquer them or that they conquer us. The very sons of Dhritarashtra stand before us, whom we would not wish to live after killing.',
    'My very nature is stricken with the weakness of pity; my mind is bewildered about dharma. I ask you: tell me for certain what is better. I am your disciple; teach me, for I have come to you for refuge.',
    'For I do not see what could drive away this grief that dries up my senses — not even an unrivalled, prosperous kingdom on earth, nor lordship over the gods themselves.',
    'Having spoken so to Hrishikesha, Gudakesha, scorcher of foes, said to Govinda, “I will not fight,” and fell silent.',
    'Then, O Bharata, between the two armies, Hrishikesha, as if smiling, spoke these words to him as he sat there in despair:',
    'You grieve for those who need no grief, and yet you speak words of wisdom. The wise grieve neither for the dead nor for the living.',
    'Never was there a time when I did not exist, nor you, nor these kings; and never will there be a time hereafter when we all shall cease to be.',
    'Just as the embodied self passes through childhood, youth and old age in this body, so it passes into another body; the steady are not deluded by this.',
    'The touches of the senses on their objects, son of Kunti, bring cold and heat, pleasure and pain; they come and go and do not last. Bear them patiently, Bharata.',
    'The one whom these do not trouble, best of men, who is the same in pain and pleasure, and steady — that one is fit for immortality.',
    'What is not, never comes to be; what is, never ceases to be. The seers of truth have seen the boundary between the two.',
    'Know that to be indestructible by which all this is pervaded. No one can bring about the destruction of the imperishable.',
    'These bodies have an end, it is said, but the embodied self within them is eternal, indestructible and beyond measure. Therefore fight, Bharata.',
    'Whoever thinks this self a slayer, and whoever thinks it slain — neither of them understands. It does not slay, nor is it slain.',
    'It is never born, nor does it ever die; it did not come into being, nor will it cease to be. Unborn, eternal, everlasting, ancient, it is not killed when the body is killed.',
    'Whoever knows it to be indestructible, eternal, unborn and unchanging — how can that person, Partha, kill anyone, or cause anyone to be killed?',
    'As a man casts off worn-out clothes and puts on others that are new, so the embodied self casts off worn-out bodies and enters others that are new.',
    'Weapons do not cut it, fire does not burn it, water does not wet it, the wind does not dry it.',
    'It cannot be cut, burned, wetted or dried. It is eternal, all-pervading, stable, unmoving, everlasting.',
    'It is called unmanifest, unthinkable, unchanging. So, knowing it to be such, you should not grieve.',
    'And even if you think of it as forever being born and forever dying, even then, strong-armed one, you should not grieve.',
    'For death is certain for whatever is born, and birth is certain for whatever dies. So you should not grieve over what cannot be avoided.',
    'Beings are unmanifest in their beginning, manifest in their middle, Bharata, and unmanifest again in their end. What is there to lament in this?',
    'One sees it as a wonder; another speaks of it as a wonder; another hears of it as a wonder; yet even having heard, no one truly knows it.',
    'The self that dwells in the body of every being is eternal and can never be slain, Bharata. So you should not grieve for any creature.',
    'And looking to your own dharma, you should not waver; for a warrior there is nothing better than a battle fought for what is right.',
    'Happy are the warriors, Partha, who find such a battle come to them unsought — an open door to heaven.',
    'But if you will not fight this righteous battle, you will abandon your own dharma and your honour, and incur sin.',
    'People will tell of your dishonour for ever; and for a man who has been honoured, dishonour is worse than death.',
    'The great chariot-warriors will think you have fled the battle out of fear; and those who held you in high esteem will think little of you.',
    'Your enemies will say many things that should not be said, scorning your strength. What could be more painful than that?',
    'If you are killed you will gain heaven; if you conquer you will enjoy the earth. So stand up, son of Kunti, resolved to fight.',
    'Holding pleasure and pain, gain and loss, victory and defeat as the same, make yourself ready for battle; so you will incur no sin.',
    'This is the understanding taught in Sankhya; now hear it in yoga. Joined to this understanding, Partha, you will cast off the bondage of action.',
    'Here no effort is lost, and no harm is done. Even a little of this dharma protects one from great fear.',
    'Here the understanding that is resolute is single, joy of the Kurus; the thoughts of the irresolute are many-branched and endless.',
    'The flowery words that the undiscerning proclaim, Partha — delighting in the letter of the Veda, saying there is nothing else —',
    'full of desire, intent on heaven, speaking of rites of many kinds that bring rebirth as the fruit of action and aim at pleasure and power:',
    'for those attached to pleasure and power, whose minds are carried away by such words, the resolute understanding does not settle in contemplation.',
    'The Vedas deal with the three qualities of nature; be free of the three, Arjuna — free of the pairs of opposites, ever established in goodness, free of getting and keeping, possessed of the self.',
    'As much use as there is in a well when water is flooding everywhere, so much is there in all the Vedas for a brahmin who knows.',
    'Your right is to action alone, never to its fruits. Let the fruit of action not be your motive, nor let your attachment be to inaction.',
    'Established in yoga, do your work, Dhananjaya, giving up attachment, the same in success and failure. Evenness of mind is called yoga.',
    'Mere action is far below the yoga of understanding, Dhananjaya. Seek refuge in understanding; pitiable are those whose motive is the fruit.',
    'One joined to understanding casts off here both good deeds and bad. So devote yourself to yoga: yoga is skill in action.',
    'The wise, joined to understanding, giving up the fruit born of action, freed from the bondage of birth, go to the place beyond all sorrow.',
    'When your understanding crosses the thicket of delusion, you will become indifferent to what has been heard and what is yet to be heard.',
    'When your understanding, bewildered by what it has heard, stands firm and unmoving in contemplation, then you will attain yoga.',
    'What is the mark of one whose wisdom is steady, Keshava, who is settled in contemplation? How does one steady in mind speak, how does he sit, how does he walk?',
    'When one gives up all the desires of the mind, Partha, and is content in the self by the self, then one is called steady in wisdom.',
    'One whose mind is not shaken in sorrow, who has no craving in pleasure, from whom passion, fear and anger have gone — that sage is called steady in mind.',
    'One who is without attachment anywhere, who neither rejoices nor recoils on meeting good or ill — that one’s wisdom is firmly set.',
    'When, like a tortoise drawing in its limbs on every side, one withdraws the senses from their objects, that one’s wisdom is firmly set.',
    'The objects of sense turn away from the one who abstains from them, but the taste for them remains; even the taste turns away when the supreme is seen.',
    'Even for a wise man who strives, son of Kunti, the turbulent senses carry off the mind by force.',
    'Restraining them all, one should sit in yoga, intent on me; for the one whose senses are under control — that one’s wisdom is firmly set.',
    'When a person dwells on the objects of sense, attachment to them arises; from attachment desire is born, and from desire, anger.',
    'From anger comes delusion; from delusion, the wandering of memory; from the loss of memory, the ruin of understanding; and with the ruin of understanding one perishes.',
    'But the self-governed, moving among the objects of sense with senses under control and free of attraction and aversion, attains clarity.',
    'In that clarity all sorrows come to an end; for the one whose mind is clear, understanding soon becomes steady.',
    'The undisciplined has no understanding and no contemplation; without contemplation there is no peace, and without peace, where is happiness?',
    'When the mind follows the wandering senses, it carries away one’s wisdom as the wind carries away a ship on the water.',
    'So, strong-armed one, the one whose senses are wholly withdrawn from their objects — that one’s wisdom is firmly set.',
    'What is night for all beings, in that the self-controlled is awake; that in which beings are awake is night for the sage who sees.',
    'As the waters enter the ocean, which is ever being filled and yet stands unmoved, so the one whom all desires enter in the same way attains peace — not the one who desires desires.',
    'The one who gives up all desires and moves about free of longing, without “mine”, without “I” — that one attains peace.',
    'This is the state of Brahman, Partha; having reached it one is no longer deluded. Established in it even at the hour of death, one attains the peace of Brahman.',
  ],
  // 3 · The yoga of action
  [
    'If you hold that understanding is better than action, Janardana, why then do you urge me to this terrible deed, Keshava?',
    'With words that seem to mix one thing with another you confuse my understanding. Tell me the one thing, for certain, by which I may reach the good.',
    'In this world, sinless one, a twofold path was taught by me of old: the yoga of knowledge for those of contemplation, the yoga of action for those of action.',
    'Not by abstaining from action does a person reach freedom from action, and not by renunciation alone does one attain perfection.',
    'No one can remain even for a moment without acting; everyone is made to act, helplessly, by the qualities born of nature.',
    'The one who restrains the organs of action but sits dwelling in the mind on the objects of sense is self-deluded, and is called a hypocrite.',
    'But the one who controls the senses by the mind, Arjuna, and without attachment undertakes the yoga of action with the organs of action — that one excels.',
    'Do the work that is yours to do, for action is better than inaction; without action even the life of your body could not be sustained.',
    'This world is bound by action, except for action done as sacrifice. Do your work for that sake, son of Kunti, free from attachment.',
    'In the beginning the Lord of creatures created beings together with sacrifice, and said: “By this you shall multiply; let this be the cow that gives you all you desire.',
    'Nourish the gods by this, and may the gods nourish you; nourishing one another, you will attain the highest good.',
    'For, nourished by sacrifice, the gods will give you the enjoyments you desire.” Whoever enjoys their gifts without giving to them in return is nothing but a thief.',
    'The good, who eat what is left from the sacrifice, are freed from all faults; but the wicked who cook only for themselves eat their own sin.',
    'From food beings come to be; from rain food is born; from sacrifice comes the rain; and sacrifice is born of action.',
    'Know that action arises from Brahman, and Brahman arises from the Imperishable. So the all-pervading Brahman is ever present in sacrifice.',
    'The one who does not here keep turning the wheel thus set in motion, living in sin and delighting in the senses, lives in vain, Partha.',
    'But for the one who delights only in the self, who is satisfied with the self and content in the self alone, there is nothing that must be done.',
    'For that one there is nothing to gain here by doing, and nothing by not doing; nor does that one depend on any being for anything.',
    'So, always without attachment, do the work that must be done; for by doing work without attachment a person reaches the supreme.',
    'It was by action alone that Janaka and others attained perfection. And you too should act, with an eye to holding the world together.',
    'Whatever the best person does, others do the same; whatever standard that one sets, the world follows.',
    'For me, Partha, there is nothing in the three worlds that I must do, nothing unattained that I must attain — and yet I go on acting.',
    'For if I did not go on tirelessly acting, Partha, people everywhere would follow my path.',
    'These worlds would fall into ruin if I did not act; I would be the cause of confusion and would destroy these creatures.',
    'As the unknowing act attached to their action, Bharata, so the knowing should act without attachment, wishing to hold the world together.',
    'Let the knowing not unsettle the understanding of the unknowing who are attached to action; acting in yoga, let them encourage all action.',
    'All actions are done by the qualities of nature; but the one deluded by the sense of “I” thinks, “I am the doer.”',
    'But the one who knows the truth of how the qualities and actions are divided, strong-armed one, knowing that qualities move among qualities, is not attached.',
    'Those deluded by the qualities of nature are attached to the works of the qualities. Let the one who knows the whole not unsettle the dull who know only in part.',
    'Laying all your actions on me, with your mind on the self, free of hope and of “mine”, fight, your fever gone.',
    'Those who always follow this teaching of mine, full of faith and without finding fault, are freed from the bondage of action.',
    'But those who find fault and do not follow my teaching, deluded in all knowledge — know them to be lost and without sense.',
    'Even the one who knows acts according to his own nature; beings follow nature. What can restraint achieve?',
    'Attraction and aversion lie in wait in every sense for its object. Do not fall under their power, for they are one’s enemies on the road.',
    'Better one’s own dharma, though imperfect, than another’s dharma well performed. Better death in one’s own dharma; another’s dharma is full of danger.',
    'Then by what is a person driven to do wrong, Varshneya, even against his will, as if forced?',
    'It is desire, it is anger, born of the quality of passion: all-devouring, the great evil. Know this to be the enemy here.',
    'As fire is covered by smoke, as a mirror by dust, as an unborn child by the womb, so is this world covered by it.',
    'Knowledge is covered by this constant enemy of the wise, son of Kunti, in the form of desire, an insatiable fire.',
    'The senses, the mind and the understanding are said to be its seat; through them it covers knowledge and deludes the embodied self.',
    'So first restrain the senses, best of the Bharatas, and then cast off this evil thing that destroys knowledge and wisdom.',
    'The senses are high, they say; above the senses is the mind; above the mind is the understanding; and above the understanding is he.',
    'So knowing what is above the understanding, steadying the self by the self, strong-armed one, slay the enemy in the form of desire, so hard to overcome.',
  ],
];
