/** An English translation of the Bhagavad Gita, chapters 4–6, made for this film. */
export const EN2: string[][] = [
  // 4 · The yoga of knowledge and the renunciation of action
  [
    'I taught this imperishable yoga to Vivasvan; Vivasvan taught it to Manu, and Manu told it to Ikshvaku.',
    'Handed down in this way from one to another, the royal sages knew it; but over a long stretch of time, scorcher of foes, that yoga was lost to the world.',
    'This same ancient yoga I have taught you today, for you are my devotee and my friend; it is the supreme secret.',
    'Your birth was later; the birth of Vivasvan was earlier. How am I to understand that you taught it in the beginning?',
    'Many are the births that have passed for me and for you, Arjuna. I know them all; you do not know them, scorcher of foes.',
    'Though I am unborn and my self does not perish, though I am the lord of all beings, I take my stand on my own nature and come into being by my own power.',
    'Whenever dharma declines, Bharata, and adharma rises, then I bring myself forth.',
    'To protect the good, to destroy the wicked and to set dharma firmly on its feet again, I come into being age after age.',
    'Whoever truly knows my divine birth and action, Arjuna, on leaving the body is not born again, but comes to me.',
    'Free of passion, fear and anger, absorbed in me, taking refuge in me, many, purified by the austerity of knowledge, have come to my being.',
    'As people come to me, so I receive them. Everywhere, Partha, people follow my path.',
    'Those who want success in their works here worship the gods; for in the world of men success comes quickly from action.',
    'The four orders were made by me according to the division of qualities and actions. Though I am their maker, know me as the non-doer, the unchanging.',
    'Actions do not stain me, nor do I long for their fruit. Whoever knows me in this way is not bound by actions.',
    'Knowing this, the seekers of freedom of old did their work. So you too do your work, as the ancients did in former times.',
    'What is action? What is inaction? Even the wise are bewildered here. I will tell you what action is; knowing it, you will be freed from evil.',
    'One must understand action, one must understand wrong action, and one must understand inaction: deep is the way of action.',
    'Whoever sees inaction in action and action in inaction is wise among people; that one is in yoga, and does all that is to be done.',
    'The one whose undertakings are all free of desire and its designs, whose actions are burned up in the fire of knowledge — the wise call that one learned.',
    'Giving up attachment to the fruit of action, ever content, depending on nothing, such a one does nothing at all, even while engaged in action.',
    'Hoping for nothing, mind and self restrained, giving up all possessions, doing only bodily action, such a one incurs no fault.',
    'Content with what comes unasked, beyond the pairs of opposites, free of envy, the same in success and failure, such a one is not bound even when acting.',
    'For the one free of attachment, liberated, whose mind is fixed in knowledge, who acts as sacrifice, all action melts away.',
    'Brahman is the offering, Brahman the oblation poured by Brahman into the fire of Brahman. Brahman is reached by the one who sees Brahman in every act.',
    'Some yogis offer sacrifice to the gods; others offer sacrifice itself as sacrifice in the fire of Brahman.',
    'Some offer the senses, hearing and the rest, in the fires of restraint; others offer sound and the other objects in the fires of the senses.',
    'Others offer all the actions of the senses and of the breath in the fire of the yoga of self-restraint, kindled by knowledge.',
    'Some offer their wealth, some their austerity, some their yoga; and ascetics of strict vows offer their study and their knowledge.',
    'Others offer the in-breath into the out-breath and the out-breath into the in-breath, stopping the course of both, intent on the control of breath.',
    'Others, restraining their food, offer the breaths into the breaths. All these know sacrifice, and their faults are destroyed by sacrifice.',
    'Eating the nectar left over from sacrifice, they go to the eternal Brahman. This world is not for one who does not sacrifice — how then the other, best of the Kurus?',
    'So, in many forms, sacrifices are spread out before the mouth of Brahman. Know them all to be born of action; knowing this, you will be free.',
    'Better than the sacrifice of things is the sacrifice of knowledge, scorcher of foes. All action without exception, Partha, comes to its fulfilment in knowledge.',
    'Learn it by bowing down, by asking, by serving. The wise who have seen the truth will teach you knowledge.',
    'Knowing it, you will not fall again into delusion like this, Pandava; by it you will see all beings in your self, and then in me.',
    'Even if you are the worst of all sinners, you will cross over all wrongdoing by the boat of knowledge alone.',
    'As a blazing fire turns its fuel to ashes, Arjuna, so the fire of knowledge turns all actions to ashes.',
    'Truly there is no purifier in this world like knowledge. One perfected in yoga finds it in time in oneself.',
    'One full of faith gains knowledge, devoted to it, with senses restrained; having gained knowledge, one soon reaches the supreme peace.',
    'The ignorant, without faith, full of doubt, perish. For the doubting self there is neither this world, nor the next, nor happiness.',
    'Action does not bind the one who has renounced action through yoga, whose doubts are cut away by knowledge, who is possessed of the self, Dhananjaya.',
    'So with the sword of knowledge cut away this doubt born of ignorance that lies in your heart. Take to yoga, and stand up, Bharata!',
  ],
  // 5 · The yoga of renunciation
  [
    'You praise the renunciation of action, Krishna, and then yoga again. Tell me for certain which one of these two is better.',
    'Renunciation and the yoga of action both lead to the highest good; but of the two, the yoga of action is better than the renunciation of action.',
    'Know the one who neither hates nor desires to be ever a renouncer; for, free of the pairs of opposites, strong-armed one, that one is easily freed from bondage.',
    'Children, not the learned, speak of Sankhya and yoga as different. Whoever is truly established in even one gains the fruit of both.',
    'The place reached by those of Sankhya is reached also by those of yoga. Whoever sees Sankhya and yoga as one, sees truly.',
    'But renunciation is hard to attain without yoga, strong-armed one; the sage joined in yoga soon comes to Brahman.',
    'Joined in yoga, pure in self, master of self, senses conquered, one whose self has become the self of all beings is not stained even when acting.',
    '“I do nothing at all,” thinks the one in yoga who knows the truth — seeing, hearing, touching, smelling, eating, walking, sleeping, breathing,',
    'speaking, letting go, taking hold, opening and closing the eyes — holding that the senses move among the objects of sense.',
    'The one who acts placing all actions in Brahman, giving up attachment, is not stained by evil, as a lotus leaf is not wet by water.',
    'With body, mind and understanding, even with the senses alone, yogis do their work without attachment, for the purifying of the self.',
    'The one joined in yoga, giving up the fruit of action, attains lasting peace; the one not joined, attached to the fruit through desire, is bound.',
    'Renouncing all actions with the mind, the embodied self sits happily, master of itself, in the city of nine gates, neither acting nor causing action.',
    'The Lord does not create the doing or the deeds of the world, nor the union of deed and fruit; it is nature that does this.',
    'The all-pervading one takes on no one’s sin, nor anyone’s good deeds. Knowledge is covered by ignorance; by this creatures are deluded.',
    'But for those in whom this ignorance is destroyed by knowledge of the self, that knowledge lights up the supreme like the sun.',
    'Their understanding in that, their self in that, established in that, devoted to that, they go to the place from which there is no return, their faults washed away by knowledge.',
    'The wise see the same in a brahmin rich in learning and humility, in a cow, an elephant, a dog and an outcaste.',
    'Here, in this very life, the round of birth is conquered by those whose mind rests in sameness. Brahman is flawless and the same in all; so they rest in Brahman.',
    'One should not rejoice on gaining the pleasant, nor be shaken on meeting the unpleasant: steady in understanding, undeluded, knowing Brahman, resting in Brahman.',
    'One not attached to outer contacts finds the happiness that is in the self; joined in yoga to Brahman, that one enjoys a happiness that does not decay.',
    'The pleasures born of contact are wombs of sorrow; they have a beginning and an end, son of Kunti. The wise take no delight in them.',
    'Whoever can bear here, before leaving the body, the force that springs from desire and anger, is joined in yoga; that person is happy.',
    'The one whose happiness is within, whose delight is within, whose light is within — that yogi, become Brahman, attains the peace of Brahman.',
    'The seers whose faults are destroyed, whose doubts are cut away, who are self-controlled and rejoice in the good of all beings, attain the peace of Brahman.',
    'For the ascetics who are free of desire and anger, who have restrained their minds and know the self, the peace of Brahman is near on every side.',
    'Shutting out the outer contacts, fixing the gaze between the brows, making even the in-breath and the out-breath that move within the nostrils,',
    'the sage whose senses, mind and understanding are restrained, intent on freedom, from whom desire, fear and anger have gone, is free for ever.',
    'Knowing me as the enjoyer of sacrifices and austerities, the great lord of all the worlds, the friend of all beings, one attains peace.',
  ],
  // 6 · The yoga of meditation
  [
    'Whoever does the work that is to be done without depending on its fruit is a renouncer and a yogi — not the one who merely keeps no fire and does no rites.',
    'Know that what they call renunciation is yoga, Pandava; for no one becomes a yogi without renouncing the designs of the mind.',
    'For the sage who wishes to climb to yoga, action is said to be the means; for the one who has climbed to yoga, stillness is said to be the means.',
    'When one is no longer attached to the objects of sense or to actions, and has renounced all designs, then one is said to have climbed to yoga.',
    'Lift up the self by the self; do not let the self sink down. For the self alone is the friend of the self, and the self alone is the enemy of the self.',
    'The self is the friend of the one who has conquered the self by the self; but for one who has not, the self stands in enmity like an enemy.',
    'The supreme self of the one who has conquered the self and is at peace is steady in cold and heat, pleasure and pain, honour and dishonour.',
    'The yogi content with knowledge and wisdom, unshaken, senses conquered, to whom a lump of earth, a stone and gold are the same, is called joined in yoga.',
    'Excellent is the one who is the same to well-wishers, friends and foes, to the indifferent and the neutral, to the hateful and to kin, to the good and to the wicked.',
    'The yogi should constantly steady the self, staying alone in a secluded place, mind and self restrained, without hope and without possessions.',
    'In a clean place, setting up a firm seat for oneself, neither too high nor too low, covered with cloth, deerskin and kusha grass,',
    'sitting there on that seat, making the mind one-pointed, restraining the workings of thought and sense, one should practise yoga for the purifying of the self.',
    'Holding body, head and neck erect and still, steady, gazing at the tip of one’s nose and not looking around,',
    'serene, fearless, firm in the vow of celibacy, the mind restrained, thinking of me, one should sit joined in yoga, intent on me.',
    'So ever steadying the self, the yogi with mind restrained attains the peace that ends in nirvana and rests in me.',
    'Yoga is not for the one who eats too much, nor for the one who does not eat at all; not for the one given to too much sleep, Arjuna, nor for the one who keeps awake.',
    'For the one who is measured in eating and recreation, measured in effort in action, measured in sleep and waking, yoga becomes the destroyer of sorrow.',
    'When the restrained mind rests in the self alone, free of longing for all desires, then one is said to be joined in yoga.',
    '“As a lamp in a windless place does not flicker”: that is the likeness given of the yogi whose mind is restrained, practising the yoga of the self.',
    'Where thought comes to rest, held still by the practice of yoga, where, seeing the self by the self, one is content in the self;',
    'where one knows that boundless happiness which is grasped by understanding and beyond the senses, and standing there does not move from the truth;',
    'having gained which, one thinks no other gain greater, and standing in which one is not shaken even by great sorrow —',
    'let that be known as yoga: the unyoking from union with sorrow. That yoga should be practised with resolve and an undespairing mind.',
    'Giving up without remainder all desires born of design, restraining the whole company of the senses on every side by the mind alone,',
    'little by little one should come to rest, with understanding held firm; making the mind dwell in the self, one should think of nothing at all.',
    'Wherever the restless, unsteady mind wanders, from there one should draw it back and bring it under the control of the self alone.',
    'Supreme happiness comes to the yogi whose mind is at peace, whose passion is stilled, who has become Brahman and is free of fault.',
    'So ever steadying the self, the yogi freed from fault easily touches the boundless happiness of contact with Brahman.',
    'The one whose self is joined in yoga, who sees the same everywhere, sees the self dwelling in all beings and all beings in the self.',
    'Whoever sees me everywhere and sees everything in me — I am not lost to that one, nor is that one lost to me.',
    'The yogi who, established in oneness, worships me as dwelling in all beings, lives in me, however he lives.',
    'The one who, by likeness to the self, sees the same everywhere, Arjuna, in pleasure or in pain, is held to be the highest yogi.',
    'This yoga of sameness that you have taught, Madhusudana — I do not see how it can stand firm, because of the restlessness of the mind.',
    'For the mind is restless, Krishna, turbulent, strong and stubborn. I think it as hard to restrain as the wind.',
    'Without doubt, strong-armed one, the mind is restless and hard to restrain; but by practice and by dispassion, son of Kunti, it can be held.',
    'For the one whose self is unrestrained, yoga is hard to attain, I agree; but the one who is self-governed and strives can reach it by the right means.',
    'One who has faith but does not strive, whose mind has strayed from yoga, who has not reached perfection in yoga — what way does that one go, Krishna?',
    'Fallen from both, does he not perish like a broken cloud, strong-armed one, without support, bewildered on the path to Brahman?',
    'Krishna, you must cut away this doubt of mine completely; for there is no one but you who can cut it away.',
    'Partha, there is no destruction for that one, neither here nor hereafter; for no one who does good, my friend, comes to a bad end.',
    'Reaching the worlds of the righteous and dwelling there for endless years, the one who fell from yoga is born in the house of the pure and the prosperous.',
    'Or else he is born in a family of wise yogis; but a birth like that is harder to gain in this world.',
    'There he regains the understanding of his former body, and strives again from there towards perfection, joy of the Kurus.',
    'By that same former practice he is carried on, even against his will. Even one who only wishes to know yoga goes beyond the letter of the Veda.',
    'But the yogi who strives with effort, cleansed of faults, perfected over many births, then reaches the highest goal.',
    'The yogi is greater than the ascetics, held greater even than the learned, greater than those who act for gain. So be a yogi, Arjuna.',
    'And of all yogis, the one who worships me with faith, the inmost self gone into me, I hold to be the most joined in yoga.',
  ],
];
