/** An English translation of the Bhagavad Gita, chapters 7–9, made for this film. */
export const EN3: string[][] = [
  // 7 · The yoga of knowledge and wisdom
  [
    'Hear, Partha, how, with your mind clinging to me, practising yoga, taking refuge in me, you will know me fully and without doubt.',
    'I will tell you in full this knowledge together with wisdom; knowing it, nothing more remains here to be known.',
    'Among thousands of people, scarcely one strives for perfection; and of those who strive and are perfected, scarcely one knows me truly.',
    'Earth, water, fire, air, space, mind, understanding and the sense of “I”: this is my nature, divided eightfold.',
    'This is my lower nature. But know my other, higher nature, strong-armed one: the life by which this world is upheld.',
    'Know that all beings have these two for their womb. I am the origin of the whole world, and its dissolution.',
    'There is nothing whatever higher than me, Dhananjaya. All this is strung on me like pearls on a thread.',
    'I am the taste in water, son of Kunti; I am the light in the moon and the sun; the Om in all the Vedas; the sound in space; the manhood in men.',
    'I am the pure fragrance in the earth and the brightness in fire; I am the life in all beings and the austerity in ascetics.',
    'Know me, Partha, as the eternal seed of all beings. I am the understanding of the understanding, the splendour of the splendid.',
    'Of the strong I am the strength that is free of desire and passion; in beings I am the desire that does not go against dharma, best of the Bharatas.',
    'And whatever states there are of goodness, passion and darkness, know that they come from me alone. But I am not in them; they are in me.',
    'Deluded by these three states made of the qualities, this whole world does not recognise me, who am beyond them and imperishable.',
    'For this divine illusion of mine, made of the qualities, is hard to cross; but those who come to me alone cross over this illusion.',
    'Evil-doers, the deluded, the lowest of people, whose knowledge is carried away by illusion and who have taken on a demonic nature, do not come to me.',
    'Four kinds of good people worship me, Arjuna: the afflicted, the seeker of knowledge, the seeker of gain, and the one who knows, best of the Bharatas.',
    'Of these the one who knows, ever joined, devoted to the One, excels. For I am dear beyond measure to the one who knows, and that one is dear to me.',
    'All these are noble; but the one who knows I hold to be my very self. For that one, steadfast, rests in me alone as the highest goal.',
    'At the end of many births the one who knows comes to me, knowing, “Vasudeva is everything.” Such a great soul is very hard to find.',
    'Those whose knowledge has been carried off by this desire or that turn to other gods, following this rule or that, led by their own nature.',
    'Whatever form any devotee wishes to worship with faith, I make that faith of theirs unshakeable.',
    'Joined to that faith, they seek to worship that form, and from it they gain their desires — desires granted, in truth, by me alone.',
    'But the fruit gained by those of little understanding has an end. Those who worship the gods go to the gods; my devotees come to me.',
    'Without understanding, people think of me, the unmanifest, as having become manifest, not knowing my higher being, imperishable and supreme.',
    'I am not revealed to all, veiled by my yogic illusion. This deluded world does not know me, the unborn, the imperishable.',
    'I know the beings that have been, that are, and that are yet to be, Arjuna; but no one knows me.',
    'Through the delusion of the pairs of opposites that arise from desire and aversion, Bharata, all beings fall into bewilderment at birth, scorcher of foes.',
    'But those of good deeds in whom sin has come to an end, freed from the delusion of the opposites, worship me, firm in their vows.',
    'Those who strive for freedom from old age and death, taking refuge in me, know that Brahman, all that concerns the self, and all of action.',
    'Those who know me with what concerns beings, with what concerns the gods and with what concerns sacrifice, know me even at the hour of departure, their minds joined in yoga.',
  ],
  // 8 · The yoga of the imperishable Brahman
  [
    'What is that Brahman? What is it that concerns the self? What is action, best of persons? What is said to concern beings, and what to concern the gods?',
    'Who, and how, is the one who concerns sacrifice here in this body, Madhusudana? And how are you to be known at the hour of departure by the self-controlled?',
    'The Imperishable is the supreme Brahman; its own being is called what concerns the self; the creative outpouring that brings beings into being is called action.',
    'What concerns beings is perishable existence; what concerns the gods is the cosmic person; and what concerns sacrifice is I myself, here in this body, best of the embodied.',
    'And whoever at the hour of death leaves the body remembering me alone goes to my being; of this there is no doubt.',
    'Whatever state one remembers at the end, on leaving the body, to that state one goes, son of Kunti, having always been shaped by it.',
    'So at all times remember me, and fight. With mind and understanding fixed on me, you will come to me without doubt.',
    'With a mind joined in the yoga of practice and not straying elsewhere, meditating on the supreme divine person, Partha, one goes to him.',
    'Whoever meditates on the ancient seer, the ruler, subtler than the subtle, the supporter of all, of unthinkable form, bright as the sun beyond the darkness,',
    'at the hour of departure, with an unmoving mind, joined in devotion and the strength of yoga, setting the breath rightly between the brows, goes to that supreme divine person.',
    'That which the knowers of the Veda call the Imperishable, which ascetics free from passion enter, desiring which they live the life of a student — that state I will tell you in brief.',
    'Closing all the gates of the body, holding the mind in the heart, setting the breath in the head, established in the steadiness of yoga,',
    'uttering the one syllable Om, which is Brahman, and remembering me, whoever goes forth leaving the body goes the highest way.',
    'For the yogi who is ever joined, who remembers me constantly, with no thought of anything else, I am easy to reach, Partha.',
    'Having come to me, the great souls do not take birth again, that impermanent home of sorrow; they have reached the highest perfection.',
    'All the worlds, up to the world of Brahma, return again, Arjuna; but for the one who comes to me, son of Kunti, there is no rebirth.',
    'Those who know that a day of Brahma lasts a thousand ages, and that his night ends after a thousand ages, are knowers of day and night.',
    'At the coming of that day all manifest things arise from the unmanifest; at the coming of that night they dissolve into that same unmanifest.',
    'This same multitude of beings, coming into being again and again, dissolves helplessly at the coming of night, Partha, and arises at the coming of day.',
    'But beyond that unmanifest there is another, eternal unmanifest being, which does not perish when all beings perish.',
    'That unmanifest is called the Imperishable, and they call it the highest goal; reaching it, none return. That is my supreme abode.',
    'That supreme person, Partha, in whom beings dwell and by whom all this is pervaded, is to be reached by devotion turned to nothing else.',
    'Now I will tell you, best of the Bharatas, the time at which yogis depart never to return, and the time at which they depart to return.',
    'Fire, light, day, the bright fortnight, the six months of the sun’s northern course: departing then, those who know Brahman go to Brahman.',
    'Smoke, night, the dark fortnight, the six months of the southern course: departing then, the yogi reaches the light of the moon and returns.',
    'These two paths, the bright and the dark, are held to be the world’s eternal ways; by the one a person goes not to return, by the other returns again.',
    'Knowing these two paths, Partha, no yogi is deluded. So at all times be joined in yoga, Arjuna.',
    'Whatever fruit of merit is declared for the Vedas, for sacrifices, austerities and gifts — the yogi who knows this goes beyond it all and reaches the supreme, primal abode.',
  ],
  // 9 · The yoga of the royal knowledge and the royal secret
  [
    'To you, who do not find fault, I will now declare this most secret knowledge together with wisdom; knowing it, you will be freed from evil.',
    'It is the king of knowledge, the king of secrets, the supreme purifier, known by direct experience, in keeping with dharma, easy to practise, imperishable.',
    'People without faith in this dharma, scorcher of foes, do not reach me, but return to the path of death and the round of rebirth.',
    'All this world is pervaded by me in my unmanifest form. All beings rest in me, but I do not rest in them.',
    'And yet beings do not rest in me: behold my divine yoga! My self, which brings beings into being, sustains them but does not rest in them.',
    'As the great wind, moving everywhere, rests always in space, so know that all beings rest in me.',
    'All beings, son of Kunti, go back into my nature at the end of an age; at the beginning of an age I send them forth again.',
    'Resting on my own nature, I send forth again and again this whole multitude of beings, helpless under the power of nature.',
    'Nor do these actions bind me, Dhananjaya; I sit as one indifferent, unattached to these actions.',
    'With me as the overseer, nature brings forth the moving and the unmoving; for this reason, son of Kunti, the world turns round.',
    'Fools despise me when I take a human body, not knowing my higher being as the great lord of beings.',
    'Vain in their hopes, vain in their actions, vain in their knowledge, senseless, they cling to the deluding nature of fiends and demons.',
    'But the great souls, Partha, who take refuge in the divine nature, worship me with a mind turned to nothing else, knowing me as the imperishable source of beings.',
    'Always singing my praise, striving, firm in their vows, bowing to me in devotion, ever joined, they worship me.',
    'Others, offering the sacrifice of knowledge, worship me as the One, as the many, and as the one facing everywhere in manifold forms.',
    'I am the rite, I am the sacrifice, I am the offering to the ancestors, I am the healing herb; I am the sacred verse, I am the clarified butter, I am the fire, I am the oblation.',
    'I am the father of this world, the mother, the giver of its order, the grandsire; the one thing to be known, the purifier, the syllable Om, the Rig, the Sama and the Yajur Veda.',
    'I am the goal, the support, the lord, the witness, the dwelling, the refuge, the friend; the origin and the dissolution, the ground, the treasure-house, the imperishable seed.',
    'I give heat; I hold back the rain and send it forth. I am immortality and death, being and non-being, Arjuna.',
    'Knowers of the three Vedas, drinking the soma, cleansed of sin, worship me with sacrifices and pray for the way to heaven. Reaching the holy world of the lord of the gods, they enjoy in heaven the divine pleasures of the gods.',
    'Having enjoyed that wide world of heaven, their merit exhausted, they enter the world of mortals. So, following the dharma of the three Vedas, desiring desires, they gain what comes and goes.',
    'But those who worship me thinking of nothing else, who are ever joined — to them I bring what they lack and keep safe what they have.',
    'Even those devotees who worship other gods with faith worship me alone, son of Kunti, though not according to the rule.',
    'For I am the enjoyer and the lord of all sacrifices; but they do not know me in truth, and so they fall.',
    'Those devoted to the gods go to the gods; those devoted to the ancestors go to the ancestors; those who sacrifice to spirits go to the spirits; but those who sacrifice to me come to me.',
    'Whoever offers me with devotion a leaf, a flower, a fruit or water — that offering of devotion from one whose self is pure, I accept.',
    'Whatever you do, whatever you eat, whatever you offer, whatever you give, whatever austerity you practise, son of Kunti, do it as an offering to me.',
    'So you will be freed from the bonds of action, with their good and evil fruits; your self joined in the yoga of renunciation, freed, you will come to me.',
    'I am the same to all beings; none is hateful to me and none is dear. But those who worship me with devotion are in me, and I am in them.',
    'Even if one of very evil conduct worships me with undivided devotion, that one must be counted good, for that one has rightly resolved.',
    'Quickly that one becomes righteous and goes to lasting peace. Know this for certain, son of Kunti: my devotee never perishes.',
    'For those who take refuge in me, Partha, even those of humble birth — women, vaishyas and shudras — reach the highest goal.',
    'How much more, then, holy brahmins and devoted royal sages! Having come into this impermanent, joyless world, worship me.',
    'Fix your mind on me, be devoted to me, sacrifice to me, bow down to me. Joining yourself to me in this way, with me as your goal, you will come to me.',
  ],
];
