/** An English translation of the Bhagavad Gita, chapters 10–12, made for this film. */
export const EN4: string[][] = [
  // 10 · The yoga of the divine glories
  [
    'Hear once more, strong-armed one, my supreme word, which I will speak to you, who delight in it, wishing your good.',
    'Neither the hosts of the gods nor the great seers know my origin; for I am the source of the gods and of the great seers in every way.',
    'Whoever knows me as unborn and without beginning, the great lord of the worlds, is undeluded among mortals and freed from all sins.',
    'Understanding, knowledge, freedom from delusion, patience, truth, self-restraint and calm; pleasure and pain, being and non-being, fear and fearlessness,',
    'non-violence, evenness, contentment, austerity, giving, fame and disgrace: these different states of beings arise from me alone.',
    'The seven great seers of old and the four Manus, from whom these creatures in the world have come, were born of my mind and share my nature.',
    'Whoever knows in truth this glory and this yoga of mine is joined to me in unshaken yoga; of this there is no doubt.',
    'I am the origin of all; from me everything comes forth. Knowing this, the wise worship me, filled with feeling.',
    'Their thoughts on me, their lives given to me, enlightening one another and always speaking of me, they are content and they rejoice.',
    'To those who are ever joined and worship me with love, I give the yoga of understanding by which they come to me.',
    'Out of compassion for them, dwelling in their hearts, I destroy the darkness born of ignorance with the shining lamp of knowledge.',
    'You are the supreme Brahman, the supreme abode, the supreme purifier, the eternal divine person, the first of the gods, unborn and all-pervading.',
    'So all the seers call you — the divine seer Narada, Asita Devala, Vyasa — and now you yourself tell me so.',
    'All that you tell me I hold to be true, Keshava. Neither the gods nor the demons, Lord, know your manifestation.',
    'You alone know yourself by yourself, supreme person, source of beings, lord of beings, god of gods, lord of the world.',
    'Tell me in full, for you can, of your divine glories, by which you pervade these worlds and abide in them.',
    'How may I know you, yogi, by always meditating on you? In which of your many forms, Lord, am I to think of you?',
    'Tell me again in detail, Janardana, of your yoga and your glory; for I am never sated with hearing this nectar.',
    'Very well: I will tell you of my divine glories, best of the Kurus, the chief ones; for there is no end to my expanse.',
    'I am the self, Gudakesha, seated in the heart of all beings. I am the beginning, the middle and the end of beings.',
    'Of the Adityas I am Vishnu; of lights, the radiant sun; of the Maruts I am Marichi; of the stars I am the moon.',
    'Of the Vedas I am the Sama Veda; of the gods I am Indra; of the senses I am the mind; in beings I am consciousness.',
    'Of the Rudras I am Shankara; of yakshas and rakshasas, the lord of wealth; of the Vasus I am fire; of mountains, Meru.',
    'Of household priests, Partha, know me to be the chief, Brihaspati; of generals I am Skanda; of waters I am the ocean.',
    'Of the great seers I am Bhrigu; of words I am the one syllable; of sacrifices I am the sacrifice of silent prayer; of things unmoving, the Himalaya.',
    'Of all trees I am the ashvattha; of divine seers, Narada; of the gandharvas, Chitraratha; of the perfected, the sage Kapila.',
    'Of horses know me to be Uchchaihshravas, born of the nectar; of lordly elephants, Airavata; and of men, the king.',
    'Of weapons I am the thunderbolt; of cows I am Kamadhuk, the cow of wishes; I am Kandarpa, the begetter; of serpents I am Vasuki.',
    'Of the nagas I am Ananta; of water-dwellers I am Varuna; of the ancestors I am Aryaman; of those who govern, I am Yama.',
    'Of the daityas I am Prahlada; of reckoners I am time; of beasts I am the lion; and of birds, the son of Vinata.',
    'Of purifiers I am the wind; of those who bear arms I am Rama; of fishes I am the makara; of rivers I am the Ganga.',
    'Of creations I am the beginning, the end and the middle, Arjuna; of knowledge, the knowledge of the self; of those who argue, I am the reasoning.',
    'Of letters I am the letter A; of compounds, the joining of equals; I alone am time without end; I am the giver, facing every way.',
    'I am death that carries off all, and the source of what is to be; of feminine things I am fame, fortune, speech, memory, intelligence, steadfastness and patience.',
    'Of the Sama chants I am the Brihat Saman; of metres I am the Gayatri; of months I am Margashirsha; of seasons, the season of flowers.',
    'Of the deceitful I am the dice; I am the splendour of the splendid; I am victory, I am resolve, I am the goodness of the good.',
    'Of the Vrishnis I am Vasudeva; of the Pandavas, Dhananjaya; of sages I am Vyasa; of poets, the poet Ushanas.',
    'Of those who chastise I am the rod; of those who seek victory I am statecraft; of secrets I am silence; of the knowing I am knowledge.',
    'And whatever is the seed of all beings, that I am, Arjuna. There is no being, moving or unmoving, that could exist without me.',
    'There is no end to my divine glories, scorcher of foes. What I have told is only a glimpse of the expanse of my glory.',
    'Whatever is glorious, lovely or mighty, know that it springs from a spark of my splendour.',
    'But what need have you, Arjuna, of knowing all this in detail? I stand supporting this whole world with a single fraction of myself.',
  ],
  // 11 · The vision of the universal form
  [
    'Out of kindness to me you have spoken the supreme secret called the self; by your words my delusion is gone.',
    'I have heard from you in full of the coming and passing of beings, lotus-eyed one, and of your own imperishable greatness.',
    'As you have declared yourself, supreme lord, so it is. Yet I wish to see your sovereign form, supreme person.',
    'If you think it possible for me to see it, Lord, master of yoga, then show me your imperishable self.',
    'Behold, Partha, my forms by hundreds and by thousands, manifold and divine, of many colours and shapes.',
    'Behold the Adityas, the Vasus, the Rudras, the two Ashvins and the Maruts; behold many wonders never seen before, Bharata.',
    'See here today, Gudakesha, the whole world, moving and unmoving, gathered as one in my body, and whatever else you wish to see.',
    'But you cannot see me with these eyes of yours. I give you a divine eye: behold my sovereign yoga.',
    'Having spoken so, O king, Hari, the great lord of yoga, then showed Partha his supreme, sovereign form:',
    'with many mouths and eyes, with many wondrous sights, with many divine ornaments, with many divine weapons raised;',
    'wearing divine garlands and garments, anointed with divine perfumes, all-wonderful, the infinite god facing every way.',
    'If the light of a thousand suns were to blaze up at once in the sky, that might be like the splendour of that great soul.',
    'There the son of Pandu saw the whole world, divided in many ways, gathered as one in the body of the god of gods.',
    'Then, overcome with wonder, his hair standing on end, Dhananjaya bowed his head to the god, joined his palms and said:',
    'I see the gods in your body, Lord, and all the hosts of beings; Brahma the lord seated on the lotus, all the seers and the divine serpents.',
    'With many arms, bellies, mouths and eyes, I see you everywhere, infinite in form; I see no end, no middle and no beginning of you, lord of all, whose form is all.',
    'Crowned, with mace and discus, a mass of radiance shining everywhere, I see you, so hard to look at, blazing all round like fire and sun, immeasurable.',
    'You are the Imperishable, the supreme thing to be known; you are the final resting-place of this world; you are the undying guardian of eternal dharma; you are, I think, the everlasting person.',
    'Without beginning, middle or end, of infinite power, with countless arms, the moon and the sun your eyes, I see you, your mouth a blazing fire, burning this world with your radiance.',
    'This space between heaven and earth and all the quarters are filled by you alone. Seeing this wondrous and terrible form of yours, great soul, the three worlds tremble.',
    'These hosts of gods are entering you; some, afraid, praise you with joined palms; crying “Hail!”, the hosts of great seers and the perfected praise you with abundant hymns.',
    'The Rudras, Adityas, Vasus and Sadhyas, the Vishvedevas, the Ashvins, the Maruts and the ancestors, the hosts of gandharvas, yakshas, demons and the perfected all gaze at you in wonder.',
    'Seeing your great form, strong-armed one, with its many mouths and eyes, many arms, thighs and feet, many bellies, terrible with many tusks, the worlds tremble, and so do I.',
    'Seeing you touching the sky, blazing, many-coloured, mouths gaping, with huge fiery eyes, my inmost self trembles, and I find no steadiness or peace, Vishnu.',
    'Seeing your mouths, terrible with tusks, like the fires of the end of time, I lose all sense of direction and find no shelter. Be gracious, lord of gods, dwelling of the world.',
    'And all these sons of Dhritarashtra, together with the hosts of kings, Bhishma, Drona and that charioteer’s son, and with the chief warriors on our side as well,',
    'are rushing into your terrible mouths, fearful with tusks; some are seen caught between your teeth, their heads crushed.',
    'As the many rushing waters of rivers run towards the ocean, so these heroes of the world of men enter your flaming mouths.',
    'As moths rush headlong into a blazing flame to their destruction, so these worlds rush headlong into your mouths to their destruction.',
    'Devouring all the worlds on every side, you lick them up with your flaming mouths. Your fierce rays fill the whole world with radiance and scorch it, Vishnu.',
    'Tell me who you are, so terrible in form. Salutation to you, best of gods; be gracious. I wish to know you, the primal one, for I do not understand what you are doing.',
    'I am Time, the destroyer of worlds, grown mighty, come here to sweep away the worlds. Even without you, all these warriors drawn up in the opposing armies shall cease to be.',
    'So stand up and win glory! Conquer your enemies and enjoy a prosperous kingdom. They have already been slain by me; be only the instrument, ambidextrous archer.',
    'Drona and Bhishma, Jayadratha and Karna and the other heroic warriors are already slain by me; slay them, do not falter. Fight! You will conquer your rivals in battle.',
    'Hearing these words of Keshava, the crowned one, trembling, joined his palms and bowed, and, bowing again in great fear, spoke to Krishna in a faltering voice:',
    'Rightly, Hrishikesha, the world rejoices and delights in praising you; the demons flee in fear in every direction, and all the hosts of the perfected bow down to you.',
    'And why should they not bow to you, great soul, greater even than Brahma, the first creator? Infinite one, lord of gods, dwelling of the world, you are the Imperishable, being and non-being, and what is beyond both.',
    'You are the first of the gods, the ancient person; you are the supreme resting-place of this world; the knower and what is to be known, and the highest abode. By you, infinite form, the world is pervaded.',
    'You are Vayu, Yama, Agni, Varuna, the moon, Prajapati and the great-grandsire. Salutation, salutation to you a thousand times, and again and again salutation to you!',
    'Salutation to you in front and behind, salutation to you on every side, you who are all. Infinite in strength, boundless in might, you encompass all, and so you are all.',
    'Whatever I said rashly, thinking you a friend — “Krishna! Yadava! Friend!” — not knowing this greatness of yours, through carelessness or affection,',
    'and whatever disrespect I showed you in jest, at play, in bed, at a seat or at a meal, alone or before others, Achyuta — for that I ask forgiveness of you, the immeasurable.',
    'You are the father of the world, of the moving and the unmoving; you are its worthiest object of worship, its greatest teacher. There is none equal to you; how could there be one greater, even in the three worlds, you of matchless power?',
    'So, bowing down and prostrating my body, I ask your grace, Lord, worthy of praise. As a father with a son, a friend with a friend, a lover with the beloved, bear with me, Lord.',
    'I rejoice to have seen what was never seen before, yet my mind is shaken with fear. Show me that form of yours, Lord; be gracious, lord of gods, dwelling of the world.',
    'I wish to see you as before, crowned, with mace and discus in hand. Take that four-armed form again, thousand-armed one of universal form.',
    'By my grace, Arjuna, through my own yoga, this supreme form has been shown to you — radiant, universal, infinite, primal — which none but you has seen before.',
    'Not by the Vedas, nor by sacrifices, nor by study, nor by gifts, nor by rites, nor by fierce austerities can I be seen in this form in the world of men by any but you, hero of the Kurus.',
    'Do not be afraid, do not be bewildered at seeing this terrible form of mine. Free from fear and glad at heart, behold again this form of mine.',
    'Having spoken so to Arjuna, Vasudeva showed his own form again; and the great soul, taking again his gentle form, comforted him in his fear.',
    'Seeing this gentle human form of yours, Janardana, I have come to myself, and my mind is restored to its own nature.',
    'This form of mine that you have seen is very hard to see; even the gods long always to behold it.',
    'Not by the Vedas, nor by austerity, nor by gifts, nor by sacrifice can I be seen in the way that you have seen me.',
    'But by devotion turned to nothing else, Arjuna, I can be known in this way, and seen in truth, and entered, scorcher of foes.',
    'Whoever does my work, with me as the goal, devoted to me, free of attachment, without enmity towards any being, comes to me, Pandava.',
  ],
  // 12 · The yoga of devotion
  [
    'Of those devotees who, ever joined, worship you in this way, and those who worship the Imperishable, the unmanifest — which know yoga best?',
    'Those who fix their minds on me and worship me, ever joined, endowed with supreme faith, I hold to be the most joined in yoga.',
    'But those who worship the Imperishable — the indefinable, the unmanifest, the all-pervading and unthinkable, unchanging, unmoving, constant —',
    'restraining all the senses, even-minded everywhere, rejoicing in the good of all beings, they too reach me.',
    'Greater is the toil of those whose minds are set on the unmanifest; for the unmanifest goal is hard for the embodied to reach.',
    'But those who lay all their actions on me, intent on me, who worship me meditating on me with a yoga turned to nothing else,',
    'for them, whose thoughts have entered into me, I become before long the deliverer from the ocean of the round of death, Partha.',
    'Fix your mind on me alone; let your understanding enter into me. Then you will dwell in me hereafter; of this there is no doubt.',
    'If you cannot keep your thought steadily on me, then seek to reach me by the yoga of practice, Dhananjaya.',
    'If you are not able even to practise, be intent on work for me; even doing actions for my sake, you will reach perfection.',
    'If you cannot do even this, then, taking refuge in my yoga, give up the fruit of all action, with the self restrained.',
    'Knowledge is better than practice; meditation is better than knowledge; giving up the fruit of action is better than meditation; and peace follows immediately on giving up.',
    'The one who hates no being, who is friendly and compassionate, free of “mine” and of “I”, the same in pain and pleasure, patient,',
    'the yogi who is always content, self-controlled, firm in resolve, whose mind and understanding are given to me — that devotee is dear to me.',
    'The one from whom the world does not shrink, and who does not shrink from the world, who is free of elation, impatience, fear and agitation, is dear to me.',
    'The one who wants nothing, who is pure, capable, unconcerned, untroubled, who has given up every undertaking — that devotee is dear to me.',
    'The one who neither rejoices nor hates, neither grieves nor desires, who has given up good and evil, and is full of devotion, is dear to me.',
    'The same to enemy and friend, the same in honour and dishonour, the same in cold and heat, pleasure and pain, free of attachment,',
    'the same in blame and praise, silent, content with whatever comes, without a home, steady in mind, full of devotion — that person is dear to me.',
    'But those who honour this nectar of dharma as I have told it, full of faith, with me as their highest goal — those devotees are dear to me beyond measure.',
  ],
];
