/** An English translation of the Bhagavad Gita, chapters 13–15, made for this film. */
export const EN5: string[][] = [
  // 13 · The yoga of the field and its knower
  [
    'Nature and the person, the field and the knower of the field, knowledge and what is to be known — these I wish to learn, Keshava.',
    'This body, son of Kunti, is called the field; the one who knows it is called the knower of the field by those who know of them.',
    'Know me too as the knower of the field in all fields, Bharata. The knowledge of the field and its knower is, I hold, true knowledge.',
    'Hear from me in brief what the field is, what it is like, what changes it has, from what it arises; and who the knower is, and what its powers are.',
    'It has been sung by the seers in many ways, in many distinct hymns, and in the reasoned and certain words of the Brahma Sutras.',
    'The great elements, the sense of “I”, understanding and the unmanifest; the ten senses and the one mind, and the five fields of the senses;',
    'desire and aversion, pleasure and pain, the body, consciousness and steadfastness: this, in brief, is the field with its changes.',
    'Humility, freedom from pretence, non-violence, patience, uprightness, service of the teacher, purity, steadiness, self-restraint;',
    'dispassion towards the objects of sense, absence of the sense of “I”, seeing the evil of the sorrow of birth, death, old age and sickness;',
    'freedom from attachment, not clinging to son, wife, home and the rest, constant evenness of mind in the coming of what is wished and unwished;',
    'unwavering devotion to me in a yoga turned to nothing else, resorting to solitary places, no delight in the company of the crowd;',
    'constancy in the knowledge of the self, seeing the purpose of the knowledge of truth: this is called knowledge, and all that is otherwise is ignorance.',
    'I will tell you what is to be known, knowing which one gains immortality: the beginningless supreme Brahman, which is said to be neither being nor non-being.',
    'With hands and feet everywhere, with eyes, heads and faces everywhere, with ears everywhere, it dwells in the world, enveloping all.',
    'Shining with the qualities of all the senses, yet free of all the senses; unattached, yet supporting all; free of the qualities, yet enjoying the qualities;',
    'outside and inside beings, unmoving and moving; too subtle to be known; far away and yet near is that.',
    'Undivided, yet it stands as if divided among beings; it is to be known as the supporter of beings, their devourer and their creator.',
    'It is the light of lights, said to be beyond darkness; knowledge, what is to be known, and what is reached by knowledge, seated in the heart of all.',
    'So the field, knowledge and what is to be known have been told in brief. My devotee, understanding this, comes to my being.',
    'Know that nature and the person are both without beginning; and know that the changes and the qualities are born of nature.',
    'Nature is said to be the cause in the making of effects and instruments; the person is said to be the cause in the experience of pleasure and pain.',
    'For the person, seated in nature, experiences the qualities born of nature; attachment to the qualities is the cause of its births in good and evil wombs.',
    'The supreme person in this body is called the witness, the one who consents, the supporter, the enjoyer, the great lord and the supreme self.',
    'Whoever knows the person and nature with its qualities in this way is not born again, however that one may live.',
    'Some see the self in the self by the self through meditation; others by the yoga of Sankhya; and others by the yoga of action.',
    'Others, not knowing this, worship having heard it from others; they too, devoted to what they have heard, cross beyond death.',
    'Whatever being is born, moving or unmoving, know that it comes from the union of the field and the knower of the field, best of the Bharatas.',
    'Whoever sees the supreme lord abiding equally in all beings, not perishing when they perish, sees truly.',
    'For, seeing the same lord abiding equally everywhere, one does not harm the self by the self, and so goes to the highest goal.',
    'Whoever sees that all actions are done by nature alone, and that the self is not the doer, sees truly.',
    'When one sees the separate existence of beings as resting in the One, and spreading out from it alone, then one attains Brahman.',
    'Being without beginning and without qualities, this supreme self, imperishable, though dwelling in the body, son of Kunti, neither acts nor is stained.',
    'As space, which is everywhere, is not stained because of its subtlety, so the self, dwelling everywhere in the body, is not stained.',
    'As the one sun lights up this whole world, so the lord of the field lights up the whole field, Bharata.',
    'Those who know with the eye of knowledge the difference between the field and its knower, and the freeing of beings from nature, go to the supreme.',
  ],
  // 14 · The yoga of the three qualities
  [
    'Again I will tell you the supreme knowledge, the highest of all knowledge, knowing which all the sages have gone from here to the highest perfection.',
    'Taking refuge in this knowledge and coming to share my nature, they are not born at the time of creation, nor troubled at the time of dissolution.',
    'My womb is the great Brahman; in it I place the seed, and from it comes the birth of all beings, Bharata.',
    'Whatever forms are born in all wombs, son of Kunti, the great Brahman is their womb, and I am the father who gives the seed.',
    'Goodness, passion and darkness, the qualities born of nature, bind the imperishable embodied self in the body, strong-armed one.',
    'Of these, goodness, being stainless, is luminous and free from ill; it binds by attachment to happiness and attachment to knowledge, sinless one.',
    'Know passion to be of the nature of desire, the source of thirst and attachment; it binds the embodied self, son of Kunti, by attachment to action.',
    'But know darkness to be born of ignorance, deluding all the embodied; it binds by heedlessness, sloth and sleep, Bharata.',
    'Goodness binds one to happiness, passion to action, Bharata; but darkness, veiling knowledge, binds one to heedlessness.',
    'Goodness prevails, overpowering passion and darkness, Bharata; passion, overpowering goodness and darkness; and darkness, overpowering goodness and passion.',
    'When the light of knowledge shines through all the gates of this body, then know that goodness has grown strong.',
    'Greed, activity, the undertaking of works, restlessness and longing arise when passion has grown strong, best of the Bharatas.',
    'Darkness, inertia, heedlessness and delusion arise when darkness has grown strong, joy of the Kurus.',
    'When the embodied self meets death while goodness prevails, it goes to the stainless worlds of those who know the highest.',
    'Meeting death in passion, one is born among those attached to action; dying in darkness, one is born in the wombs of the deluded.',
    'The fruit of good action, they say, is pure and of the nature of goodness; the fruit of passion is sorrow, and the fruit of darkness is ignorance.',
    'From goodness knowledge arises, from passion greed, and from darkness heedlessness, delusion and ignorance.',
    'Those established in goodness go upward; those of passion stay in the middle; those of darkness, abiding in the lowest quality, go downward.',
    'When the seer sees no doer other than the qualities, and knows what is beyond the qualities, that one comes to my being.',
    'Going beyond these three qualities from which the body springs, the embodied self, freed from birth, death, old age and sorrow, attains immortality.',
    'What are the marks of one who has gone beyond these three qualities, Lord? How does that one behave, and how does that one go beyond them?',
    'The one who does not hate light, activity or delusion when they arise, Pandava, nor long for them when they cease;',
    'who sits as one indifferent, unshaken by the qualities, knowing “it is only the qualities moving”, who stands firm and does not waver;',
    'the same in pain and pleasure, resting in the self, to whom a lump of earth, a stone and gold are alike, the same to the dear and the unwelcome, steadfast, the same in blame and praise of oneself;',
    'the same in honour and dishonour, the same to friend and foe, who has given up every undertaking — that one is said to have gone beyond the qualities.',
    'And the one who serves me with the yoga of unswerving devotion, going beyond these qualities, is fit to become Brahman.',
    'For I am the foundation of Brahman, of the immortal and imperishable, of eternal dharma and of perfect happiness.',
  ],
  // 15 · The yoga of the supreme person
  [
    'They speak of the imperishable ashvattha tree with its roots above and its branches below; its leaves are the Vedic hymns. Whoever knows it knows the Veda.',
    'Its branches spread below and above, nourished by the qualities, with the objects of sense for shoots; and below its roots stretch down, binding to action in the world of men.',
    'Its form is not seen here, nor its end, nor its beginning, nor its foundation. Cutting down this firmly rooted ashvattha with the strong axe of non-attachment,',
    'one should then seek that place from which, once reached, there is no return, saying: “I take refuge in that primal person from whom the ancient stream of the world flowed forth.”',
    'Free of pride and delusion, the fault of attachment conquered, ever dwelling in the self, desires turned away, freed from the opposites known as pleasure and pain, the undeluded go to that imperishable place.',
    'The sun does not light it, nor the moon, nor fire. Having gone there, none return: that is my supreme abode.',
    'An eternal part of me, become a living self in the world of the living, draws to itself the senses with the mind as the sixth, which rest in nature.',
    'When the lord takes on a body and when he leaves it, he takes these with him and goes, as the wind carries scents from their source.',
    'Presiding over the ear, the eye, touch, taste and smell, and the mind, he enjoys the objects of sense.',
    'The deluded do not see him departing or staying, or enjoying, joined with the qualities; those with the eye of knowledge see.',
    'Yogis who strive see him dwelling in the self; but those who strive without having perfected the self, without sense, do not see him.',
    'The light of the sun that lights up the whole world, the light in the moon and the light in fire — know that light to be mine.',
    'Entering the earth, I support all beings by my strength; and becoming soma, the juice of life, I nourish all the plants.',
    'Becoming the fire of life, I dwell in the body of living beings, and joined with the in-breath and the out-breath I digest the fourfold food.',
    'I am seated in the heart of all; from me come memory, knowledge and their loss. I am what is to be known in all the Vedas; I am the maker of the Vedanta and the knower of the Veda.',
    'There are two persons in this world, the perishable and the imperishable. The perishable is all beings; the unchanging is called the imperishable.',
    'But there is another, the highest person, called the supreme self, the undying lord, who enters the three worlds and upholds them.',
    'Since I am beyond the perishable and higher even than the imperishable, in the world and in the Veda I am celebrated as the supreme person.',
    'Whoever, undeluded, knows me thus as the supreme person knows all, and worships me with all their being, Bharata.',
    'So I have taught this most secret teaching, sinless one. Understanding it, one becomes wise and has done all there is to do, Bharata.',
  ],
];
