/** An English translation of the Bhagavad Gita, chapters 16–18, made for this film. */
export const EN6: string[][] = [
  // 16 · The yoga of the divine and the demonic
  [
    'Fearlessness, purity of heart, steadfastness in knowledge and yoga, giving, self-restraint, sacrifice, study of scripture, austerity, uprightness;',
    'non-violence, truth, freedom from anger, renunciation, peace, freedom from slander, compassion for beings, freedom from greed, gentleness, modesty, steadiness;',
    'vigour, patience, fortitude, purity, freedom from malice and from pride: these belong to one born to the divine nature, Bharata.',
    'Hypocrisy, arrogance, conceit, anger, harshness and ignorance belong to one born to the demonic nature, Partha.',
    'The divine nature leads to freedom, the demonic to bondage. Do not grieve, Pandava: you are born to the divine nature.',
    'There are two kinds of beings in this world, the divine and the demonic. The divine has been told at length; hear from me now of the demonic, Partha.',
    'The demonic do not know when to act and when to refrain; there is no purity in them, no good conduct, no truth.',
    'They say the world is without truth, without foundation, without a lord, not brought about by any order of causes — caused by desire, and by nothing else.',
    'Holding this view, these lost souls of little understanding and cruel deeds rise up as enemies for the destruction of the world.',
    'Clinging to insatiable desire, full of hypocrisy, pride and arrogance, taking up false ideas through delusion, they act with impure resolves.',
    'Beset by endless cares that end only with death, holding the gratification of desire as the highest aim, convinced that this is all,',
    'bound by hundreds of ties of hope, given over to desire and anger, they strive to heap up wealth by unjust means for the gratification of desire.',
    '“This I have gained today; this desire I shall fulfil. This is mine, and this wealth too shall be mine.',
    'That enemy I have slain, and others too I shall slay. I am the lord, I am the enjoyer; I am successful, strong and happy.',
    'I am rich and high-born; who else is like me? I shall sacrifice, I shall give, I shall rejoice” — so they speak, deluded by ignorance.',
    'Bewildered by many thoughts, caught in the net of delusion, attached to the gratification of desire, they fall into a foul hell.',
    'Self-conceited, stubborn, full of the pride and intoxication of wealth, they perform sacrifices in name only, with hypocrisy and not according to the rule.',
    'Given over to the sense of “I”, to force, arrogance, desire and anger, these envious ones hate me in their own bodies and in the bodies of others.',
    'These cruel haters, the worst of people, the impure, I hurl again and again into the round of births, into demonic wombs.',
    'Falling into demonic wombs, deluded birth after birth, never reaching me, son of Kunti, they go to the lowest state.',
    'Threefold is this gate of hell, destroyer of the self: desire, anger and greed. So one should give up these three.',
    'The one who is freed from these three gates of darkness, son of Kunti, does what is good for the self and so goes to the highest goal.',
    'The one who casts aside the rule of scripture and acts on the impulse of desire attains neither perfection, nor happiness, nor the highest goal.',
    'So let scripture be your authority in deciding what should be done and what should not. Knowing what the rule of scripture declares, you should do your work here.',
  ],
  // 17 · The yoga of the three kinds of faith
  [
    'Those who set aside the rule of scripture but sacrifice full of faith — what is their standing, Krishna? Is it goodness, passion or darkness?',
    'The faith of the embodied is of three kinds, born of their own nature: of goodness, of passion and of darkness. Hear of it.',
    'The faith of everyone follows their inner nature, Bharata. A person is made of faith; whatever one’s faith is, that one is.',
    'The people of goodness worship the gods; the people of passion worship yakshas and rakshasas; the others, the people of darkness, worship ghosts and the hosts of spirits.',
    'People who practise terrible austerities not ordained by scripture, given to hypocrisy and the sense of “I”, driven by desire, passion and force,',
    'senseless, tormenting the elements gathered in the body, and me too who dwell within the body — know them to be of demonic resolve.',
    'Even the food that is dear to each is of three kinds, and so are sacrifice, austerity and giving. Hear how they differ.',
    'Foods that increase life, vitality, strength, health, happiness and cheer — savoury, rich, nourishing and pleasing — are dear to the people of goodness.',
    'Foods that are bitter, sour, salty, too hot, pungent, harsh and burning, which bring pain, grief and sickness, are wanted by the people of passion.',
    'Food that is stale, tasteless, putrid and spoiled, left over and unclean, is dear to the people of darkness.',
    'The sacrifice offered according to the rule by those who seek no fruit, with the mind fixed on the thought “this ought to be offered”, is of goodness.',
    'But the sacrifice offered with an eye to its fruit, or for show, know that to be of passion, best of the Bharatas.',
    'The sacrifice without rule, without food given, without sacred verse, without gifts to the priests and without faith, is said to be of darkness.',
    'Worship of the gods, the twice-born, teachers and the wise; purity, uprightness, continence and non-violence: this is called the austerity of the body.',
    'Speech that causes no distress, that is truthful, pleasant and beneficial, and the regular recitation of scripture: this is called the austerity of speech.',
    'Serenity of mind, gentleness, silence, self-control and purity of heart: this is called the austerity of the mind.',
    'This threefold austerity, practised with supreme faith by people joined in yoga who seek no fruit, is said to be of goodness.',
    'Austerity practised for respect, honour and reverence, or for show, is said here to be of passion; it is unstable and does not last.',
    'Austerity practised from a deluded notion, with torment of oneself, or in order to destroy another, is said to be of darkness.',
    'The gift given because it ought to be given, to one who can do nothing in return, at the right place and time, to a worthy person — that gift is held to be of goodness.',
    'But the gift given in expectation of a return, or with an eye to its fruit, or given grudgingly, is held to be of passion.',
    'The gift given at the wrong place and time, to the unworthy, without respect or with contempt, is said to be of darkness.',
    '“Om Tat Sat”: this is held to be the threefold naming of Brahman. By it the brahmins, the Vedas and sacrifices were ordained of old.',
    'So, with the utterance of “Om”, the acts of sacrifice, giving and austerity enjoined by the rule are always begun by those who speak of Brahman.',
    'With the word “Tat”, and without aiming at the fruit, the various acts of sacrifice, austerity and giving are performed by those who seek freedom.',
    '“Sat” is used in the sense of reality and of goodness; and the word “Sat” is used for a praiseworthy deed, Partha.',
    'Steadfastness in sacrifice, austerity and giving is also called “Sat”, and so is any action done for that purpose.',
    'Whatever is offered, given or done as austerity without faith is called “asat”, Partha; it is nothing, here or hereafter.',
  ],
  // 18 · The yoga of freedom through renunciation
  [
    'I wish to know the truth of renunciation, strong-armed one, and of relinquishment, Hrishikesha, each apart, slayer of Keshi.',
    'The setting aside of actions done from desire the poets call renunciation; the giving up of the fruit of all actions the wise call relinquishment.',
    'Some thinkers say that action should be given up as an evil; others that acts of sacrifice, giving and austerity should not be given up.',
    'Hear my conclusion about relinquishment, best of the Bharatas; for relinquishment, tiger among men, is declared to be of three kinds.',
    'Acts of sacrifice, giving and austerity should not be given up but performed; sacrifice, giving and austerity purify the wise.',
    'But even these actions should be done giving up attachment and fruit. This, Partha, is my certain and highest view.',
    'Renunciation of an action that is ordained is not right; giving it up out of delusion is declared to be of darkness.',
    'Whoever gives up an action because it is painful, out of fear of bodily hardship, makes a relinquishment of passion and does not gain its fruit.',
    'When an ordained action is done only because it ought to be done, Arjuna, giving up attachment and fruit, that relinquishment is held to be of goodness.',
    'The relinquisher pervaded by goodness, wise, with doubts cut away, neither hates unpleasant work nor clings to pleasant work.',
    'It is not possible for an embodied being to give up actions entirely; but whoever gives up the fruit of action is called a relinquisher.',
    'The fruit of action — unwanted, wanted or mixed — comes threefold after death to those who have not relinquished, but never to those who have renounced.',
    'Learn from me, strong-armed one, these five causes for the accomplishment of all actions, as declared in the Sankhya teaching:',
    'the seat of action, the doer, the various instruments, the many and distinct movements, and, fifth, the divine.',
    'Whatever action a person undertakes with body, speech or mind, right or wrong, these five are its causes.',
    'That being so, whoever sees the self alone as the doer, through an understanding untrained, does not see, being of poor sense.',
    'The one who is free of the sense of “I”, whose understanding is not stained, does not slay even in slaying these people, and is not bound.',
    'Knowledge, what is known and the knower are the threefold impulse to action; the instrument, the action and the doer are the threefold basis of action.',
    'Knowledge, action and the doer are said in the teaching of the qualities to be of three kinds, according to the qualities. Hear of these too, as they are.',
    'The knowledge by which one sees one imperishable being in all beings, undivided in the divided — know that knowledge to be of goodness.',
    'But the knowledge that sees in all beings various beings of different kinds, each apart — know that knowledge to be of passion.',
    'And the knowledge that clings to one single effect as if it were the whole, without reason, without grasp of the truth, and narrow — that is declared to be of darkness.',
    'The ordained action done without attachment, without desire or aversion, by one who seeks no fruit, is said to be of goodness.',
    'But the action done with great strain by one who longs for desires, or by one with the sense of “I”, is said to be of passion.',
    'The action undertaken through delusion, without regard to consequence, loss, harm to others or one’s own capacity, is said to be of darkness.',
    'The doer free of attachment, not given to talk of “I”, full of steadiness and zeal, unchanged in success and failure, is said to be of goodness.',
    'The doer who is passionate, longing for the fruit of action, greedy, violent, impure, given to elation and grief, is declared to be of passion.',
    'The doer who is undisciplined, vulgar, stubborn, deceitful, malicious, lazy, despondent and procrastinating is said to be of darkness.',
    'Hear now, Dhananjaya, the threefold division of understanding and of steadfastness according to the qualities, told fully and each apart.',
    'The understanding that knows action and withdrawal, what should be done and what should not, fear and fearlessness, bondage and freedom — that understanding, Partha, is of goodness.',
    'The understanding by which one knows wrongly dharma and adharma, what should be done and what should not — that understanding, Partha, is of passion.',
    'The understanding which, covered by darkness, takes adharma for dharma and sees all things upside down — that understanding, Partha, is of darkness.',
    'The unwavering steadfastness by which, through yoga, one holds the workings of the mind, the breath and the senses — that steadfastness, Partha, is of goodness.',
    'But the steadfastness by which one holds to dharma, pleasure and wealth, wanting their fruit through attachment — that steadfastness, Partha, is of passion.',
    'The steadfastness by which the foolish do not let go of sleep, fear, grief, despair and arrogance — that steadfastness, Partha, is of darkness.',
    'And now hear from me, best of the Bharatas, of the three kinds of happiness: that in which one delights through practice and in which one comes to the end of sorrow;',
    'that which is like poison at first and like nectar in the end, born of the clarity of one’s own understanding of the self, is said to be the happiness of goodness.',
    'That which comes from the contact of the senses with their objects, like nectar at first and like poison in the end, is held to be the happiness of passion.',
    'That which deludes the self at the beginning and in the end, arising from sleep, sloth and heedlessness, is declared to be the happiness of darkness.',
    'There is no being on earth, nor again among the gods in heaven, that is free of these three qualities born of nature.',
    'The duties of brahmins, kshatriyas and vaishyas, and of shudras, scorcher of foes, are divided according to the qualities born of their own nature.',
    'Calm, self-restraint, austerity, purity, patience and uprightness, knowledge, wisdom and faith are the work of the brahmin, born of his nature.',
    'Valour, vigour, steadfastness, skill, not fleeing in battle, generosity and lordliness are the work of the kshatriya, born of his nature.',
    'Ploughing, the keeping of cattle and trade are the work of the vaishya, born of his nature; work in the form of service is the work of the shudra, born of his nature.',
    'Devoted each to his own work, a person attains perfection. Hear how one devoted to one’s own work finds perfection.',
    'By worshipping with one’s own work the one from whom beings arise, by whom all this is pervaded, a person finds perfection.',
    'Better one’s own dharma, though imperfect, than another’s dharma well performed. Doing the work set by one’s own nature, one incurs no sin.',
    'One should not give up the work one is born to, son of Kunti, even if it has its flaws; for all undertakings are clouded by flaws, as fire is by smoke.',
    'The one whose understanding is unattached everywhere, who has conquered the self, from whom longing has gone, attains through renunciation the supreme perfection of freedom from action.',
    'Learn from me in brief, son of Kunti, how one who has reached perfection reaches Brahman, the highest culmination of knowledge.',
    'Joined to a pure understanding, steadying the self with firmness, turning away from sound and the other objects of sense, casting off attraction and aversion,',
    'dwelling in solitude, eating little, with speech, body and mind restrained, ever devoted to the yoga of meditation, taking refuge in dispassion,',
    'casting off the sense of “I”, force, arrogance, desire, anger and possession, free of “mine” and at peace, one is fit to become Brahman.',
    'Become Brahman, serene in self, one neither grieves nor desires; the same to all beings, one attains supreme devotion to me.',
    'By devotion one comes to know me in truth, what and who I am; then, knowing me in truth, one enters into me at once.',
    'Doing all actions always, taking refuge in me, by my grace one reaches the eternal, imperishable abode.',
    'Laying all actions on me in your mind, intent on me, resorting to the yoga of understanding, keep your thought always on me.',
    'With your thought on me, you will cross over every difficulty by my grace; but if, from the sense of “I”, you will not listen, you will perish.',
    'If, clinging to the sense of “I”, you think “I will not fight”, that resolve of yours is in vain; your nature will compel you.',
    'Bound by your own work, born of your nature, son of Kunti, what you do not wish to do through delusion you will do even against your will.',
    'The Lord dwells in the heart of all beings, Arjuna, making all beings turn by his power, as if mounted on a machine.',
    'Take refuge in him alone with all your being, Bharata. By his grace you will reach supreme peace, the eternal abode.',
    'So I have declared to you this knowledge, more secret than all that is secret. Reflect on it fully, and then do as you wish.',
    'Hear again my supreme word, the most secret of all. You are dearly loved by me; so I will tell you what is for your good.',
    'Fix your mind on me, be devoted to me, sacrifice to me, bow down to me, and you will come to me. I promise you truly, for you are dear to me.',
    'Leaving all dharmas, come to me alone for refuge. I will free you from all sins; do not grieve.',
    'This is never to be spoken to one without austerity, nor to one without devotion, nor to one who does not wish to hear, nor to one who finds fault with me.',
    'Whoever, with supreme devotion to me, declares this supreme secret among my devotees will come to me without doubt.',
    'No one among people does anything dearer to me than that one, nor will there be anyone on earth dearer to me.',
    'And whoever studies this sacred dialogue of ours, by that one I shall be worshipped with the sacrifice of knowledge: such is my thought.',
    'And the one who hears it with faith and without finding fault will also be freed, and will reach the happy worlds of the righteous.',
    'Have you heard this, Partha, with a mind fixed on one point? Has your delusion born of ignorance been destroyed, Dhananjaya?',
    'My delusion is destroyed, and I have regained my memory by your grace, Achyuta. I stand firm, my doubts gone. I will do as you say.',
    'So I heard this wondrous dialogue between Vasudeva and the great-souled Partha, and my hair stands on end.',
    'By the grace of Vyasa I heard this supreme secret, this yoga, from Krishna, the lord of yoga himself, as he spoke it.',
    'O king, as I remember again and again this wondrous and holy dialogue between Keshava and Arjuna, I rejoice again and again.',
    'And as I remember again and again that most wondrous form of Hari, great is my amazement, O king, and I rejoice again and again.',
    'Wherever there is Krishna, the lord of yoga, wherever there is Partha, the archer, there are fortune, victory, prosperity and steadfast justice: that is my conviction.',
  ],
];
