/**
 * A short meaning for each of the thousand names, in order: the name in the
 * nominative (the archana lines in data.ts are dative) and what it means.
 * Written for this page after Shankara's commentary on the Sahasranama and the
 * common readings of it; where a name carries several meanings, the one given
 * is the plainest, sometimes with a second. They are glosses to open a door,
 * not a translation. Generated from source/meanings.txt (number|name|meaning) — edit there.
 */
export const MEANINGS: [string, string][] = [
  ["Viśvam", "The universe itself — the whole of it is He."],
  ["Viṣṇuḥ", "The all-pervading one, who enters and fills everything."],
  ["Vaṣaṭkāraḥ", "The one to whom the sacrificial call “vaṣaṭ” is offered."],
  ["Bhūta-bhavya-bhavat-prabhuḥ", "Lord of the past, the future and the present."],
  ["Bhūtakṛt", "The maker of all beings."],
  ["Bhūtabhṛt", "The sustainer of all beings."],
  ["Bhāvaḥ", "Pure existence; the one who becomes all things."],
  ["Bhūtātmā", "The Self within every being."],
  ["Bhūtabhāvanaḥ", "The one who brings beings forth and nourishes them."],
  ["Pūtātmā", "The one whose nature is utterly pure."],
  ["Paramātmā", "The Supreme Self."],
  ["Muktānāṃ Paramā Gatiḥ", "The final goal of the liberated."],
  ["Avyayaḥ", "The imperishable, who never diminishes."],
  ["Puruṣaḥ", "The Person who dwells in the city of the body."],
  ["Sākṣī", "The witness, who sees all and is touched by none of it."],
  ["Kṣetrajñaḥ", "The knower of the field — of body and mind."],
  ["Akṣaraḥ", "The indestructible."],
  ["Yogaḥ", "The one reached through yoga; union itself."],
  ["Yogavidāṃ Netā", "The guide of those who know yoga."],
  ["Pradhāna-puruṣeśvaraḥ", "Lord of both matter and spirit."],
  ["Nārasiṃhavapuḥ", "Whose body is the Man-Lion."],
  ["Śrīmān", "The one on whose breast Śrī, Lakṣmī, always dwells."],
  ["Keśavaḥ", "Of beautiful locks; the slayer of Keśī."],
  ["Puruṣottamaḥ", "The Highest Person."],
  ["Sarvaḥ", "All that is — the whole."],
  ["Śarvaḥ", "The one who dissolves all things at the end."],
  ["Śivaḥ", "The auspicious, beyond the three qualities."],
  ["Sthāṇuḥ", "The unmoving, firm as a pillar."],
  ["Bhūtādiḥ", "The origin of the elements."],
  ["Nidhir Avyayaḥ", "The treasure that never runs out."],
  ["Sambhavaḥ", "The one who takes birth by His own will."],
  ["Bhāvanaḥ", "The giver of the fruits of action."],
  ["Bhartā", "The supporter of the universe."],
  ["Prabhavaḥ", "The source from which all arises."],
  ["Prabhuḥ", "The almighty master."],
  ["Īśvaraḥ", "The sovereign ruler."],
  ["Svayambhūḥ", "The self-existent, born of none."],
  ["Śambhuḥ", "The bringer of happiness."],
  ["Ādityaḥ", "The golden person in the sun; son of Aditi."],
  ["Puṣkarākṣaḥ", "Lotus-eyed."],
  ["Mahāsvanaḥ", "Whose voice is the thunder of the Vedas."],
  ["Anādinidhanaḥ", "Without beginning and without end."],
  ["Dhātā", "The one who holds all things up."],
  ["Vidhātā", "The one who ordains actions and their fruits."],
  ["Dhātur Uttamaḥ", "The highest ground of all things."],
  ["Aprameyaḥ", "Beyond all measure and proof."],
  ["Hṛṣīkeśaḥ", "Lord of the senses."],
  ["Padmanābhaḥ", "From whose navel the lotus of creation rises."],
  ["Amaraprabhuḥ", "Lord of the immortals."],
  ["Viśvakarmā", "Whose work is the whole universe."],
  ["Manuḥ", "The thinker; the one who is mantra itself."],
  ["Tvaṣṭā", "The one who shapes and thins all forms at the end."],
  ["Sthaviṣṭhaḥ", "The most massive — the vast cosmic form."],
  ["Sthaviro Dhruvaḥ", "The ancient one, forever fixed."],
  ["Agrāhyaḥ", "Beyond the grasp of the senses."],
  ["Śāśvataḥ", "The eternal."],
  ["Kṛṣṇaḥ", "The dark one; existence and bliss together."],
  ["Lohitākṣaḥ", "Red-eyed."],
  ["Pratardanaḥ", "The destroyer at the dissolution."],
  ["Prabhūtaḥ", "Full of every perfection."],
  ["Trikakub-dhāma", "The support of the three worlds."],
  ["Pavitram", "The purifier."],
  ["Maṅgalaṃ Param", "The highest good fortune."],
  ["Īśānaḥ", "The controller of all beings."],
  ["Prāṇadaḥ", "The giver of life breath."],
  ["Prāṇaḥ", "Life itself."],
  ["Jyeṣṭhaḥ", "The eldest, before all things."],
  ["Śreṣṭhaḥ", "The most praiseworthy."],
  ["Prajāpatiḥ", "Lord of all creatures."],
  ["Hiraṇyagarbhaḥ", "The golden womb of the universe."],
  ["Bhūgarbhaḥ", "The one who holds the earth within Him."],
  ["Mādhavaḥ", "Lord of Mā, Lakṣmī; known through silence and meditation."],
  ["Madhusūdanaḥ", "Slayer of the demon Madhu."],
  ["Īśvaraḥ", "The omnipotent."],
  ["Vikramī", "The valiant."],
  ["Dhanvī", "The bowman — Rāma with his bow."],
  ["Medhāvī", "Of vast intelligence."],
  ["Vikramaḥ", "The one who strode across the worlds."],
  ["Kramaḥ", "The all-pervading step."],
  ["Anuttamaḥ", "The one with none higher."],
  ["Durādharṣaḥ", "The one none can overcome."],
  ["Kṛtajñaḥ", "The one who knows every deed and remembers the smallest offering."],
  ["Kṛtiḥ", "Action itself; the effort in every effort."],
  ["Ātmavān", "Established in His own glory."],
  ["Sureśaḥ", "Lord of the gods."],
  ["Śaraṇam", "The refuge."],
  ["Śarma", "Infinite bliss."],
  ["Viśvaretāḥ", "The seed of the universe."],
  ["Prajābhavaḥ", "The source of all creatures."],
  ["Ahaḥ", "The day — luminous."],
  ["Saṃvatsaraḥ", "The year: time itself."],
  ["Vyālaḥ", "Hard to grasp, like a great serpent."],
  ["Pratyayaḥ", "Consciousness itself; the one to be trusted."],
  ["Sarvadarśanaḥ", "The all-seeing."],
  ["Ajaḥ", "The unborn."],
  ["Sarveśvaraḥ", "Lord of all."],
  ["Siddhaḥ", "The ever-perfect."],
  ["Siddhiḥ", "The fulfilment; the fruit of every effort."],
  ["Sarvādiḥ", "The beginning of all."],
  ["Acyutaḥ", "The one who never falls from His nature."],
  ["Vṛṣākapiḥ", "Dharma raising up the earth, as the Boar."],
  ["Ameyātmā", "Whose being is immeasurable."],
  ["Sarvayoga-viniḥsṛtaḥ", "Free of all attachment; known by every discipline."],
  ["Vasuḥ", "The one who dwells in all, and in whom all dwell."],
  ["Vasumanāḥ", "Of a mind rich and pure."],
  ["Satyaḥ", "Truth."],
  ["Samātmā", "The same Self in all; equal-minded."],
  ["Sammitaḥ", "The one grasped by the scriptures."],
  ["Samaḥ", "Always the same, unchanging."],
  ["Amoghaḥ", "Whose every act bears fruit; never in vain."],
  ["Puṇḍarīkākṣaḥ", "Lotus-eyed; seen in the lotus of the heart."],
  ["Vṛṣakarmā", "Whose every act is dharma."],
  ["Vṛṣākṛtiḥ", "Who takes form to uphold dharma."],
  ["Rudraḥ", "The one who makes the world weep at the end; remover of sorrow."],
  ["Bahuśirāḥ", "Many-headed."],
  ["Babhruḥ", "The bearer of the worlds."],
  ["Viśvayoniḥ", "The womb of the universe."],
  ["Śuciśravāḥ", "Whose names are pure to hear."],
  ["Amṛtaḥ", "The immortal."],
  ["Śāśvata-sthāṇuḥ", "Eternal and unmoving."],
  ["Varārohaḥ", "The highest goal to rise to."],
  ["Mahātapāḥ", "Of great austerity — His thought is creation."],
  ["Sarvagaḥ", "The one who goes everywhere."],
  ["Sarvavid-bhānuḥ", "All-knowing and radiant."],
  ["Viṣvaksenaḥ", "Before whom armies scatter."],
  ["Janārdanaḥ", "The one people pray to; who troubles the wicked."],
  ["Vedaḥ", "The Veda itself."],
  ["Vedavit", "The knower of the Veda."],
  ["Avyaṅgaḥ", "Complete, without any lack."],
  ["Vedāṅgaḥ", "Whose limbs are the Vedas."],
  ["Vedavit", "The one who knows what the Veda means."],
  ["Kaviḥ", "The seer."],
  ["Lokādhyakṣaḥ", "The one who presides over the worlds."],
  ["Surādhyakṣaḥ", "The one who presides over the gods."],
  ["Dharmādhyakṣaḥ", "The judge of right and wrong."],
  ["Kṛtākṛtaḥ", "Both the made and the unmade."],
  ["Caturātmā", "Fourfold in creation, preservation, dissolution and beyond."],
  ["Caturvyūhaḥ", "Of four emanations: Vāsudeva, Saṅkarṣaṇa, Pradyumna, Aniruddha."],
  ["Caturdaṃṣṭraḥ", "Four-tusked, as the Man-Lion."],
  ["Caturbhujaḥ", "Four-armed."],
  ["Bhrājiṣṇuḥ", "Pure radiance."],
  ["Bhojanam", "What is enjoyed — nature itself."],
  ["Bhoktā", "The enjoyer."],
  ["Sahiṣṇuḥ", "The patient, who endures and forgives."],
  ["Jagad-ādijaḥ", "The first-born at the dawn of the world."],
  ["Anaghaḥ", "The sinless."],
  ["Vijayaḥ", "Victory."],
  ["Jetā", "The ever-victorious."],
  ["Viśvayoniḥ", "The source of the universe."],
  ["Punarvasuḥ", "The one who dwells again and again in bodies."],
  ["Upendraḥ", "The younger brother of Indra — Vāmana."],
  ["Vāmanaḥ", "The dwarf who asked Bali for three steps."],
  ["Prāṃśuḥ", "The towering one, whose steps covered the worlds."],
  ["Amoghaḥ", "Never failing."],
  ["Śuciḥ", "The pure, who purifies those who remember Him."],
  ["Ūrjitaḥ", "Of mighty strength."],
  ["Atīndraḥ", "Surpassing Indra."],
  ["Saṅgrahaḥ", "The one who gathers all at the dissolution."],
  ["Sargaḥ", "Creation itself."],
  ["Dhṛtātmā", "Established in Himself."],
  ["Niyamaḥ", "The appointer of all to their places."],
  ["Yamaḥ", "The inner controller."],
  ["Vedyaḥ", "The one to be known."],
  ["Vaidyaḥ", "The physician; the knower of all knowledge."],
  ["Sadāyogī", "Ever in yoga."],
  ["Vīrahā", "Slayer of mighty demons."],
  ["Mādhavaḥ", "Lord of knowledge (mā)."],
  ["Madhuḥ", "Sweet as honey."],
  ["Atīndriyaḥ", "Beyond the senses."],
  ["Mahāmāyaḥ", "The great magician, whose power no one sees through."],
  ["Mahotsāhaḥ", "Of great zeal."],
  ["Mahābalaḥ", "Of great strength."],
  ["Mahābuddhiḥ", "Of great wisdom."],
  ["Mahāvīryaḥ", "Of great valour."],
  ["Mahāśaktiḥ", "Of great power."],
  ["Mahādyutiḥ", "Of great splendour."],
  ["Anirdeśyavapuḥ", "Whose form cannot be pointed out."],
  ["Śrīmān", "Full of glory."],
  ["Ameyātmā", "Of immeasurable intelligence."],
  ["Mahādridhṛk", "The one who lifted the great mountain — Govardhana, Mandara."],
  ["Maheṣvāsaḥ", "The great archer."],
  ["Mahībhartā", "The one who bore the earth up out of the waters."],
  ["Śrīnivāsaḥ", "The abode of Śrī."],
  ["Satāṃ Gatiḥ", "The refuge of the good."],
  ["Aniruddhaḥ", "The unobstructed; one of the four emanations."],
  ["Surānandaḥ", "The joy of the gods."],
  ["Govindaḥ", "The one who finds the cows; known through the Veda; protector of the earth."],
  ["Govidāṃ Patiḥ", "Lord of those who know speech and the Veda."],
  ["Marīciḥ", "Radiance itself."],
  ["Damanaḥ", "The one who subdues the wicked."],
  ["Haṃsaḥ", "The swan — the Self that removes fear."],
  ["Suparṇaḥ", "Of beautiful wings — the Veda's wings."],
  ["Bhujagottamaḥ", "The best of serpents — Śeṣa."],
  ["Hiraṇyanābhaḥ", "Of the golden navel."],
  ["Sutapāḥ", "Of great austerity, as Nara-Nārāyaṇa at Badarī."],
  ["Padmanābhaḥ", "Lotus-naveled."],
  ["Prajāpatiḥ", "Father of all beings."],
  ["Amṛtyuḥ", "The deathless."],
  ["Sarvadṛk", "The one who sees all."],
  ["Siṃhaḥ", "The lion."],
  ["Sandhātā", "The one who joins actions to their fruits."],
  ["Sandhimān", "The one who is Himself the enjoyer of fruits."],
  ["Sthiraḥ", "The steady."],
  ["Ajaḥ", "The one who moves in hearts; unborn."],
  ["Durmarṣaṇaḥ", "The one demons cannot bear."],
  ["Śāstā", "The teacher who rules through scripture."],
  ["Viśrutātmā", "Of famed nature."],
  ["Surārihā", "Destroyer of the enemies of the gods."],
  ["Guruḥ", "The teacher."],
  ["Gurutamaḥ", "The greatest teacher."],
  ["Dhāma", "The abode; the supreme light."],
  ["Satyaḥ", "The true."],
  ["Satyaparākramaḥ", "Whose valour never fails."],
  ["Nimiṣaḥ", "Whose eyes close in yogic sleep."],
  ["Animiṣaḥ", "The ever-watchful, who never blinks."],
  ["Sragvī", "Wearing the Vaijayantī garland."],
  ["Vācaspatir Udāradhīḥ", "Lord of speech, of generous intellect."],
  ["Agraṇīḥ", "The one who leads to the highest."],
  ["Grāmaṇīḥ", "The leader of all beings."],
  ["Śrīmān", "The radiant."],
  ["Nyāyaḥ", "Justice; the logic of truth."],
  ["Netā", "The guide."],
  ["Samīraṇaḥ", "The one who moves as the breath of life."],
  ["Sahasramūrdhā", "Thousand-headed."],
  ["Viśvātmā", "The Self of the universe."],
  ["Sahasrākṣaḥ", "Thousand-eyed."],
  ["Sahasrapāt", "Thousand-footed."],
  ["Āvartanaḥ", "The one who turns the wheel of the world."],
  ["Nivṛttātmā", "The one untouched by worldliness."],
  ["Saṃvṛtaḥ", "Veiled by ignorance from those who do not seek."],
  ["Sampramardanaḥ", "The crusher of the wicked."],
  ["Ahaḥ-saṃvartakaḥ", "The sun who brings on the day."],
  ["Vahniḥ", "Fire, carrier of offerings."],
  ["Anilaḥ", "Wind; the one without a dwelling."],
  ["Dharaṇīdharaḥ", "The bearer of the earth."],
  ["Suprasādaḥ", "Gracious even to those who harm Him."],
  ["Prasannātmā", "Of serene nature."],
  ["Viśvadhṛk", "The upholder of the world."],
  ["Viśvabhuk", "The enjoyer and protector of the world."],
  ["Vibhuḥ", "The manifold, all-pervading lord."],
  ["Satkartā", "The one who honours the good."],
  ["Satkṛtaḥ", "Honoured by the honoured."],
  ["Sādhuḥ", "The righteous."],
  ["Jahnuḥ", "The one who draws beings into Himself at the end."],
  ["Nārāyaṇaḥ", "The refuge of all beings; resting on the waters."],
  ["Naraḥ", "The eternal person; the guide."],
  ["Asaṅkhyeyaḥ", "Of countless names and forms."],
  ["Aprameyātmā", "Whose nature is beyond measure."],
  ["Viśiṣṭaḥ", "The most excellent."],
  ["Śiṣṭakṛt", "The one who commands and protects the good."],
  ["Śuciḥ", "The spotless."],
  ["Siddhārthaḥ", "Whose every aim is already fulfilled."],
  ["Siddhasaṅkalpaḥ", "Whose every resolve comes true."],
  ["Siddhidaḥ", "The giver of attainment."],
  ["Siddhisādhanaḥ", "The means to every attainment."],
  ["Vṛṣāhī", "Lord of the sacred rites; whose days are dharma."],
  ["Vṛṣabhaḥ", "The one who showers blessings like rain."],
  ["Viṣṇuḥ", "The one who pervades all, striding across the worlds."],
  ["Vṛṣaparvā", "The stairway of dharma that leads to Him."],
  ["Vṛṣodaraḥ", "From whose belly beings pour like rain."],
  ["Vardhanaḥ", "The one who makes all grow."],
  ["Vardhamānaḥ", "The one who grows into the universe."],
  ["Viviktaḥ", "Solitary, apart from all."],
  ["Śrutisāgaraḥ", "The ocean of the Vedas."],
  ["Subhujaḥ", "Of mighty, beautiful arms."],
  ["Durdharaḥ", "The one who bears what none else can."],
  ["Vāgmī", "The eloquent, from whom the Veda came."],
  ["Mahendraḥ", "Lord of Indra himself."],
  ["Vasudaḥ", "The giver of wealth."],
  ["Vasuḥ", "Wealth itself."],
  ["Naikarūpaḥ", "Of many forms."],
  ["Bṛhadrūpaḥ", "Of vast form, as the Boar."],
  ["Śipiviṣṭaḥ", "The one who dwells in the rays of light."],
  ["Prakāśanaḥ", "The illuminator."],
  ["Ojas-tejo-dyutidharaḥ", "Bearer of vitality, brilliance and splendour."],
  ["Prakāśātmā", "Whose nature is light."],
  ["Pratāpanaḥ", "The one who scorches, as the sun."],
  ["Ṛddhaḥ", "Full of prosperity and dharma."],
  ["Spaṣṭākṣaraḥ", "The one clearly declared by the syllable Om."],
  ["Mantraḥ", "The sacred word; the one known through mantra."],
  ["Candrāṃśuḥ", "Cooling as moonlight to those scorched by the world."],
  ["Bhāskaradyutiḥ", "Brilliant as the sun."],
  ["Amṛtāṃśūdbhavaḥ", "From whom the moon was born at the churning of the ocean."],
  ["Bhānuḥ", "The shining one."],
  ["Śaśabinduḥ", "The moon, who nourishes the plants."],
  ["Sureśvaraḥ", "Lord of the gods."],
  ["Auṣadham", "The medicine for the disease of worldly life."],
  ["Jagataḥ Setuḥ", "The bridge across the world's ocean."],
  ["Satya-dharma-parākramaḥ", "Whose truth, dharma and valour are real."],
  ["Bhūta-bhavya-bhavan-nāthaḥ", "Master of past, future and present beings."],
  ["Pavanaḥ", "The purifying wind."],
  ["Pāvanaḥ", "The one who makes the wind blow."],
  ["Analaḥ", "Fire; the one who is never satisfied."],
  ["Kāmahā", "The destroyer of desire in seekers."],
  ["Kāmakṛt", "The fulfiller of wishes."],
  ["Kāntaḥ", "The beautiful, the beloved."],
  ["Kāmaḥ", "The one desired by all."],
  ["Kāmapradaḥ", "The giver of what is longed for."],
  ["Prabhuḥ", "The lord."],
  ["Yugādikṛt", "The maker of the ages' beginnings."],
  ["Yugāvartaḥ", "The one who turns the cycle of ages."],
  ["Naikamāyaḥ", "Of many wondrous powers."],
  ["Mahāśanaḥ", "The great devourer at the end."],
  ["Adṛśyaḥ", "The invisible."],
  ["Vyaktarūpaḥ", "Whose form is manifest to the wise."],
  ["Sahasrajit", "Conqueror of thousands."],
  ["Anantajit", "Of endless victory."],
  ["Iṣṭaḥ", "The beloved; the one worshipped in sacrifice."],
  ["Aviśiṣṭaḥ", "The one without distinction, the same in all."],
  ["Śiṣṭeṣṭaḥ", "Dear to the wise."],
  ["Śikhaṇḍī", "Wearing a peacock feather — Kṛṣṇa the cowherd."],
  ["Nahuṣaḥ", "The one who binds beings by māyā."],
  ["Vṛṣaḥ", "Dharma itself."],
  ["Krodhahā", "The destroyer of anger."],
  ["Krodhakṛt-kartā", "The one who acts against those who act in anger."],
  ["Viśvabāhuḥ", "Whose arms are everywhere."],
  ["Mahīdharaḥ", "The upholder of the earth."],
  ["Acyutaḥ", "The one who never slips."],
  ["Prathitaḥ", "The famous."],
  ["Prāṇaḥ", "The life-breath of all."],
  ["Prāṇadaḥ", "The giver of strength."],
  ["Vāsavānujaḥ", "The younger brother of Indra."],
  ["Apāṃ Nidhiḥ", "The ocean, treasure-house of waters."],
  ["Adhiṣṭhānam", "The ground on which everything rests."],
  ["Apramattaḥ", "The ever-vigilant."],
  ["Pratiṣṭhitaḥ", "Established in His own glory."],
  ["Skandaḥ", "The one who flows as nectar; Skanda."],
  ["Skandadharaḥ", "The upholder of righteousness."],
  ["Dhuryaḥ", "The one who carries the weight of the world."],
  ["Varadaḥ", "The giver of boons."],
  ["Vāyuvāhanaḥ", "The one who moves the winds."],
  ["Vāsudevaḥ", "The one who dwells in all, and in whom all dwell; son of Vasudeva."],
  ["Bṛhadbhānuḥ", "Of vast light."],
  ["Ādidevaḥ", "The first god."],
  ["Purandaraḥ", "The destroyer of the demons' cities."],
  ["Aśokaḥ", "Beyond sorrow."],
  ["Tāraṇaḥ", "The one who carries across."],
  ["Tāraḥ", "The saviour."],
  ["Śūraḥ", "The valiant."],
  ["Śauriḥ", "Descendant of Śūra — Kṛṣṇa."],
  ["Janeśvaraḥ", "Lord of the people."],
  ["Anukūlaḥ", "The well-wisher of all."],
  ["Śatāvartaḥ", "Who has come again and again, in countless descents."],
  ["Padmī", "The one who holds a lotus."],
  ["Padmanibhekṣaṇaḥ", "Whose eyes are like lotuses."],
  ["Padmanābhaḥ", "Seated in the lotus of the heart."],
  ["Aravindākṣaḥ", "Lotus-eyed."],
  ["Padmagarbhaḥ", "Worshipped in the heart-lotus."],
  ["Śarīrabhṛt", "The sustainer of bodies."],
  ["Maharddhiḥ", "Of great abundance."],
  ["Ṛddhaḥ", "The one who has become the universe."],
  ["Vṛddhātmā", "The ancient Self."],
  ["Mahākṣaḥ", "The great-eyed."],
  ["Garuḍadhvajaḥ", "Whose banner bears Garuḍa."],
  ["Atulaḥ", "The incomparable."],
  ["Śarabhaḥ", "The one who shines through bodies."],
  ["Bhīmaḥ", "The terrible, before whom all tremble."],
  ["Samayajñaḥ", "The one who knows the right time for everything."],
  ["Havirhariḥ", "The receiver of offerings."],
  ["Sarva-lakṣaṇa-lakṣaṇyaḥ", "Known by every true means of knowing."],
  ["Lakṣmīvān", "The one with whom Lakṣmī always dwells."],
  ["Samitiñjayaḥ", "Victorious in battle."],
  ["Vikṣaraḥ", "The one who never decays."],
  ["Rohitaḥ", "The red one; the great Fish."],
  ["Mārgaḥ", "The path."],
  ["Hetuḥ", "The cause."],
  ["Dāmodaraḥ", "Bound at the waist with a rope by Yaśodā."],
  ["Sahaḥ", "The one who overcomes all."],
  ["Mahīdharaḥ", "The bearer of the earth."],
  ["Mahābhāgaḥ", "The most fortunate."],
  ["Vegavān", "The swift."],
  ["Amitāśanaḥ", "Of boundless appetite at the dissolution."],
  ["Udbhavaḥ", "The origin."],
  ["Kṣobhaṇaḥ", "The one who stirs nature into creation."],
  ["Devaḥ", "The shining one who plays."],
  ["Śrīgarbhaḥ", "Who holds all glory within."],
  ["Parameśvaraḥ", "The supreme lord."],
  ["Karaṇam", "The instrument of creation."],
  ["Kāraṇam", "The cause."],
  ["Kartā", "The doer."],
  ["Vikartā", "The maker of variety."],
  ["Gahanaḥ", "The unfathomable."],
  ["Guhaḥ", "The one hidden in the cave of the heart."],
  ["Vyavasāyaḥ", "Resolute; pure knowledge."],
  ["Vyavasthānaḥ", "The ground of all order."],
  ["Saṃsthānaḥ", "The final resting place."],
  ["Sthānadaḥ", "The giver of rightful places — as to Dhruva."],
  ["Dhruvaḥ", "The fixed and eternal."],
  ["Pararddhiḥ", "Of supreme glories."],
  ["Paramaspaṣṭaḥ", "Supremely clear."],
  ["Tuṣṭaḥ", "Ever content."],
  ["Puṣṭaḥ", "Ever full."],
  ["Śubhekṣaṇaḥ", "Whose glance is auspicious."],
  ["Rāmaḥ", "The one in whom yogis delight; Rāma."],
  ["Virāmaḥ", "The end in which all come to rest."],
  ["Virajaḥ", "Free from passion."],
  ["Mārgaḥ", "The way to immortality."],
  ["Neyaḥ", "The one led by love."],
  ["Nayaḥ", "The leader."],
  ["Anayaḥ", "The one who has no leader."],
  ["Vīraḥ", "The heroic."],
  ["Śaktimatāṃ Śreṣṭhaḥ", "Mightiest of the mighty."],
  ["Dharmaḥ", "The one who upholds all; dharma itself."],
  ["Dharmaviduttamaḥ", "Highest of the knowers of dharma."],
  ["Vaikuṇṭhaḥ", "The one who joins the elements; Lord of Vaikuṇṭha."],
  ["Puruṣaḥ", "The one who dwells in all bodies."],
  ["Prāṇaḥ", "The breath of life."],
  ["Prāṇadaḥ", "The giver of life."],
  ["Praṇavaḥ", "Om, the sacred syllable."],
  ["Pṛthuḥ", "The expansive."],
  ["Hiraṇyagarbhaḥ", "The golden embryo of creation."],
  ["Śatrughnaḥ", "The slayer of foes."],
  ["Vyāptaḥ", "The one who pervades all."],
  ["Vāyuḥ", "The wind."],
  ["Adhokṣajaḥ", "The one who never falls from His nature."],
  ["Ṛtuḥ", "The season; time in its turning."],
  ["Sudarśanaḥ", "Of auspicious sight; bearer of the Sudarśana discus."],
  ["Kālaḥ", "Time."],
  ["Parameṣṭhī", "Established in the highest place."],
  ["Parigrahaḥ", "The one grasped from every side by seekers."],
  ["Ugraḥ", "The fierce."],
  ["Saṃvatsaraḥ", "The year, in which all dwell."],
  ["Dakṣaḥ", "The capable, who acts swiftly."],
  ["Viśrāmaḥ", "Rest; the resting place."],
  ["Viśvadakṣiṇaḥ", "The most skilful; the most generous."],
  ["Vistāraḥ", "The one in whom the worlds spread out."],
  ["Sthāvara-sthāṇuḥ", "Firm and immovable."],
  ["Pramāṇam", "The proof; pure consciousness."],
  ["Bījam Avyayam", "The imperishable seed."],
  ["Arthaḥ", "The one all seek."],
  ["Anarthaḥ", "The one who needs nothing."],
  ["Mahākośaḥ", "Covered by the great sheaths."],
  ["Mahābhogaḥ", "Of great enjoyment."],
  ["Mahādhanaḥ", "Of great wealth."],
  ["Anirviṇṇaḥ", "Never discontented."],
  ["Sthaviṣṭhaḥ", "The immense."],
  ["Abhūḥ", "The unborn."],
  ["Dharmayūpaḥ", "The sacrificial post to which dharma is tied."],
  ["Mahāmakhaḥ", "The great sacrifice."],
  ["Nakṣatranemiḥ", "The hub round which the stars turn."],
  ["Nakṣatrī", "The moon among the stars."],
  ["Kṣamaḥ", "The capable; the forbearing."],
  ["Kṣāmaḥ", "The one who remains when all has dwindled."],
  ["Samīhanaḥ", "The one whose desire is for the good of all."],
  ["Yajñaḥ", "Sacrifice itself."],
  ["Ijyaḥ", "The one to be worshipped."],
  ["Mahejyaḥ", "The most worthy of worship."],
  ["Kratuḥ", "The sacrificial rite."],
  ["Satram", "The protector of the good."],
  ["Satāṃ Gatiḥ", "The goal of the good."],
  ["Sarvadarśī", "The all-seeing."],
  ["Vimuktātmā", "The ever-free Self."],
  ["Sarvajñaḥ", "The all-knowing."],
  ["Jñānam Uttamam", "Supreme knowledge."],
  ["Suvrataḥ", "Of perfect vows."],
  ["Sumukhaḥ", "Of a lovely, gracious face."],
  ["Sūkṣmaḥ", "The subtlest."],
  ["Sughoṣaḥ", "Of auspicious sound — the Veda."],
  ["Sukhadaḥ", "The giver of happiness."],
  ["Suhṛt", "The friend of all."],
  ["Manoharaḥ", "The stealer of hearts."],
  ["Jitakrodhaḥ", "The one who has conquered anger."],
  ["Vīrabāhuḥ", "Of mighty arms."],
  ["Vidāraṇaḥ", "The one who splits the wicked asunder."],
  ["Svāpanaḥ", "The one who lulls beings into the sleep of ignorance."],
  ["Svavaśaḥ", "Independent, under His own control."],
  ["Vyāpī", "The all-pervading."],
  ["Naikātmā", "The one who is many."],
  ["Naikakarmakṛt", "The doer of many deeds."],
  ["Vatsaraḥ", "The abode of all."],
  ["Vatsalaḥ", "Tender, loving to His devotees."],
  ["Vatsī", "The protector of calves — the cowherd."],
  ["Ratnagarbhaḥ", "The ocean, holding the jewels."],
  ["Dhaneśvaraḥ", "Lord of wealth."],
  ["Dharmagup", "The protector of dharma."],
  ["Dharmakṛt", "The one who acts by dharma."],
  ["Dharmī", "The support of dharma."],
  ["Sat", "Being; the real."],
  ["Asat", "The unmanifest."],
  ["Kṣaram", "The perishable world."],
  ["Akṣaram", "The imperishable."],
  ["Avijñātā", "The one who is not a limited knower."],
  ["Sahasrāṃśuḥ", "Thousand-rayed."],
  ["Vidhātā", "The one who supports all."],
  ["Kṛtalakṣaṇaḥ", "The author of the scriptures."],
  ["Gabhastinemiḥ", "The hub of the wheel of rays."],
  ["Sattvasthaḥ", "The one who dwells in goodness."],
  ["Siṃhaḥ", "The lion among beings."],
  ["Bhūtamaheśvaraḥ", "Great lord of beings."],
  ["Ādidevaḥ", "The first deity."],
  ["Mahādevaḥ", "The great god."],
  ["Deveśaḥ", "Lord of the gods."],
  ["Devabhṛd-guruḥ", "The teacher of Indra, who upholds the gods."],
  ["Uttaraḥ", "The one who lifts us out of the ocean of saṃsāra."],
  ["Gopatiḥ", "Lord of the cows; lord of the earth."],
  ["Goptā", "The protector."],
  ["Jñānagamyaḥ", "The one reached by knowledge."],
  ["Purātanaḥ", "The ancient."],
  ["Śarīra-bhūta-bhṛt", "The sustainer of the elements that make the body."],
  ["Bhoktā", "The enjoyer."],
  ["Kapīndraḥ", "Lord of the monkeys — Rāma, master of Hanumān's host."],
  ["Bhūridakṣiṇaḥ", "The one who gives abundant gifts in sacrifice."],
  ["Somapaḥ", "The drinker of soma in every rite."],
  ["Amṛtapaḥ", "The one who drinks the nectar of His own bliss."],
  ["Somaḥ", "The moon, who nourishes the plants."],
  ["Purujit", "The conqueror of many."],
  ["Purusattamaḥ", "The best of the great."],
  ["Vinayaḥ", "The one who disciplines the wicked."],
  ["Jayaḥ", "Victory over all beings."],
  ["Satyasandhaḥ", "Whose word always comes true."],
  ["Dāśārhaḥ", "Born in the Daśārha clan."],
  ["Sātvatāṃ Patiḥ", "Lord of the Sātvatas — His devotees."],
  ["Jīvaḥ", "The living one, the knower of the field."],
  ["Vinayitā-sākṣī", "The witness of humility in His devotees."],
  ["Mukundaḥ", "The giver of liberation."],
  ["Amitavikramaḥ", "Of immeasurable strides."],
  ["Ambhonidhiḥ", "The ocean in which the gods dwell."],
  ["Anantātmā", "The infinite Self."],
  ["Mahodadhiśayaḥ", "The one who lies on the great ocean."],
  ["Antakaḥ", "The one who ends all things."],
  ["Ajaḥ", "The unborn."],
  ["Mahārhaḥ", "Worthy of the highest worship."],
  ["Svābhāvyaḥ", "The one who is Himself by His own nature."],
  ["Jitāmitraḥ", "The conqueror of enemies within and without."],
  ["Pramodanaḥ", "The ever-joyful, who gladdens those who meditate on Him."],
  ["Ānandaḥ", "Bliss."],
  ["Nandanaḥ", "The one who makes others glad."],
  ["Nandaḥ", "Full of every joy."],
  ["Satyadharmā", "Whose dharma is true."],
  ["Trivikramaḥ", "The one who measured the worlds in three strides."],
  ["Maharṣiḥ Kapilācāryaḥ", "The great sage Kapila, teacher of Sāṅkhya."],
  ["Kṛtajñaḥ", "The knower of creation."],
  ["Medinīpatiḥ", "Lord of the earth."],
  ["Tripadaḥ", "Of three steps."],
  ["Tridaśādhyakṣaḥ", "Lord of the gods; witness of the three states of mind."],
  ["Mahāśṛṅgaḥ", "The great-horned Fish, to whose horn the ark was tied."],
  ["Kṛtāntakṛt", "The one who ends death itself."],
  ["Mahāvarāhaḥ", "The great Boar who lifted the earth."],
  ["Govindaḥ", "Reached through the Vedas; protector of cows and earth."],
  ["Suṣeṇaḥ", "The one with a glorious army."],
  ["Kanakāṅgadī", "Wearing golden armlets."],
  ["Guhyaḥ", "The secret, known in the heart's cave."],
  ["Gabhīraḥ", "The profound."],
  ["Gahanaḥ", "The impenetrable."],
  ["Guptaḥ", "The hidden."],
  ["Cakragadādharaḥ", "Bearer of the discus and the mace."],
  ["Vedhāḥ", "The creator."],
  ["Svāṅgaḥ", "The one who is His own instrument."],
  ["Ajitaḥ", "The unconquered."],
  ["Kṛṣṇaḥ", "Dark as a raincloud; Kṛṣṇa-Dvaipāyana Vyāsa."],
  ["Dṛḍhaḥ", "The firm."],
  ["Saṅkarṣaṇo 'cyutaḥ", "The one who draws all in at the end, yet never falls."],
  ["Varuṇaḥ", "The setting sun who gathers his rays."],
  ["Vāruṇaḥ", "Son of Varuṇa — the sage Vasiṣṭha."],
  ["Vṛkṣaḥ", "The tree, firm and giving shelter."],
  ["Puṣkarākṣaḥ", "Lotus-eyed."],
  ["Mahāmanāḥ", "Great-minded."],
  ["Bhagavān", "The one with the six glories: sovereignty, dharma, fame, fortune, wisdom, detachment."],
  ["Bhagahā", "The one who takes those glories back at the end."],
  ["Ānandī", "The blissful."],
  ["Vanamālī", "Wearing the garland of forest flowers."],
  ["Halāyudhaḥ", "Whose weapon is the plough — Balarāma."],
  ["Ādityaḥ", "Son of Aditi — Vāmana."],
  ["Jyotirādityaḥ", "The light in the sun."],
  ["Sahiṣṇuḥ", "The one who endures the pairs of opposites."],
  ["Gatisattamaḥ", "The best refuge."],
  ["Sudhanvā", "Of the beautiful bow, Śārṅga."],
  ["Khaṇḍaparaśuḥ", "Wielder of the axe — Paraśurāma."],
  ["Dāruṇaḥ", "Merciless to the wicked."],
  ["Draviṇapradaḥ", "The giver of wealth."],
  ["Divispṛk", "The one who touches the sky."],
  ["Sarvadṛg-vyāsaḥ", "The all-seeing one who divided the Veda — Vyāsa."],
  ["Vācaspatir Ayonijaḥ", "Lord of speech, not born of a womb."],
  ["Trisāmā", "Praised by the three Sāman chants."],
  ["Sāmagaḥ", "The singer of the Sāma Veda."],
  ["Sāma", "The Sāma Veda itself."],
  ["Nirvāṇam", "Final peace, beyond all."],
  ["Bheṣajam", "The medicine."],
  ["Bhiṣak", "The physician who taught the Gītā."],
  ["Saṃnyāsakṛt", "The one who set out the path of renunciation."],
  ["Śamaḥ", "Calm."],
  ["Śāntaḥ", "The peaceful."],
  ["Niṣṭhā", "The one in whom all come to rest."],
  ["Śāntiḥ", "Peace itself."],
  ["Parāyaṇam", "The highest goal."],
  ["Śubhāṅgaḥ", "Of beautiful form."],
  ["Śāntidaḥ", "The giver of peace."],
  ["Sraṣṭā", "The creator."],
  ["Kumudaḥ", "The one who delights in the earth."],
  ["Kuvaleśayaḥ", "The one who lies on the waters."],
  ["Gohitaḥ", "The friend of cows."],
  ["Gopatiḥ", "Lord of the cows."],
  ["Goptā", "The protector of the world."],
  ["Vṛṣabhākṣaḥ", "Whose eyes shower blessings."],
  ["Vṛṣapriyaḥ", "The one who loves dharma."],
  ["Anivartī", "The one who never turns back from battle or from dharma."],
  ["Nivṛttātmā", "Whose mind is turned away from the senses."],
  ["Saṅkṣeptā", "The one who contracts the universe at the end."],
  ["Kṣemakṛt", "The one who keeps what has been gained."],
  ["Śivaḥ", "The auspicious; the purifier."],
  ["Śrīvatsavakṣāḥ", "Bearing the Śrīvatsa mark on His chest."],
  ["Śrīvāsaḥ", "The dwelling of Śrī."],
  ["Śrīpatiḥ", "Husband of Śrī."],
  ["Śrīmatāṃ Varaḥ", "The best of the glorious."],
  ["Śrīdaḥ", "The giver of fortune."],
  ["Śrīśaḥ", "Lord of Śrī."],
  ["Śrīnivāsaḥ", "The one in whom Śrī dwells."],
  ["Śrīnidhiḥ", "The treasure of all glories."],
  ["Śrīvibhāvanaḥ", "The one who gives each their fortune."],
  ["Śrīdharaḥ", "The one who holds Śrī on His breast."],
  ["Śrīkaraḥ", "The one who makes His devotees prosper."],
  ["Śreyaḥ", "The highest good."],
  ["Śrīmān", "The glorious."],
  ["Lokatrayāśrayaḥ", "The refuge of the three worlds."],
  ["Svakṣaḥ", "Of beautiful eyes."],
  ["Svaṅgaḥ", "Of beautiful limbs."],
  ["Śatānandaḥ", "Of a hundredfold bliss."],
  ["Nandiḥ", "Supreme bliss."],
  ["Jyotirgaṇeśvaraḥ", "Lord of the luminaries."],
  ["Vijitātmā", "The master of His own mind."],
  ["Avidheyātmā", "The one whose nature no one can command."],
  ["Satkīrtiḥ", "Of true fame."],
  ["Chinnasaṃśayaḥ", "The one who cuts every doubt."],
  ["Udīrṇaḥ", "The one who stands above all."],
  ["Sarvataścakṣuḥ", "Whose eyes are everywhere."],
  ["Anīśaḥ", "The one who has no lord."],
  ["Śāśvata-sthiraḥ", "Eternal and steady."],
  ["Bhūśayaḥ", "The one who lay on the ground by the sea — Rāma on the shore."],
  ["Bhūṣaṇaḥ", "The one who adorns the world."],
  ["Bhūtiḥ", "Glory; existence itself."],
  ["Viśokaḥ", "Free of sorrow."],
  ["Śokanāśanaḥ", "The destroyer of grief."],
  ["Arciṣmān", "The radiant, from whom the sun and moon borrow light."],
  ["Arcitaḥ", "The one worshipped by all."],
  ["Kumbhaḥ", "The pot in which everything is held."],
  ["Viśuddhātmā", "Of pure nature."],
  ["Viśodhanaḥ", "The purifier."],
  ["Aniruddhaḥ", "The unobstructed."],
  ["Apratirathaḥ", "The one with no rival."],
  ["Pradyumnaḥ", "Of great wealth; the one of the four emanations."],
  ["Amitavikramaḥ", "Of boundless valour."],
  ["Kālanemi-nihā", "Slayer of the demon Kālanemi."],
  ["Vīraḥ", "The hero."],
  ["Śauriḥ", "Born of the Śūra clan."],
  ["Śūrajaneśvaraḥ", "Lord of heroes."],
  ["Trilokātmā", "The Self of the three worlds."],
  ["Trilokeśaḥ", "Lord of the three worlds."],
  ["Keśavaḥ", "The one whose rays are His locks."],
  ["Keśihā", "Slayer of the horse-demon Keśī."],
  ["Hariḥ", "The one who takes away — sin, sorrow, the world."],
  ["Kāmadevaḥ", "The god who is desired."],
  ["Kāmapālaḥ", "The guardian of rightful desires."],
  ["Kāmī", "The one whose desires are fulfilled."],
  ["Kāntaḥ", "Of enchanting beauty."],
  ["Kṛtāgamaḥ", "The author of the scriptures."],
  ["Anirdeśyavapuḥ", "Whose form cannot be described."],
  ["Viṣṇuḥ", "The one whose light fills heaven and earth."],
  ["Vīraḥ", "The one who moves swiftly."],
  ["Anantaḥ", "The endless."],
  ["Dhanañjayaḥ", "Winner of wealth — Arjuna, as His own glory."],
  ["Brahmaṇyaḥ", "The friend of the Veda and of austerity."],
  ["Brahmakṛt", "The maker of Brahman — of the Veda and of tapas."],
  ["Brahmā", "Brahmā the creator."],
  ["Brahma", "Brahman, the absolute."],
  ["Brahmavivardhanaḥ", "The one who increases tapas and truth."],
  ["Brahmavit", "The knower of Brahman."],
  ["Brāhmaṇaḥ", "The one who teaches the Veda."],
  ["Brahmī", "The one in whom Brahman is."],
  ["Brahmajñaḥ", "The knower of the Veda."],
  ["Brāhmaṇapriyaḥ", "Dear to the knowers of Brahman."],
  ["Mahākramaḥ", "Of great strides."],
  ["Mahākarmā", "Of great deeds."],
  ["Mahātejāḥ", "Of great radiance."],
  ["Mahoragaḥ", "The great serpent."],
  ["Mahākratuḥ", "The great sacrifice."],
  ["Mahāyajvā", "The great performer of sacrifice."],
  ["Mahāyajñaḥ", "The greatest sacrifice — the sacrifice of repeating the name."],
  ["Mahāhaviḥ", "The great offering."],
  ["Stavyaḥ", "The one worthy of praise."],
  ["Stavapriyaḥ", "The one who loves praise."],
  ["Stotram", "The hymn itself."],
  ["Stutiḥ", "Praise."],
  ["Stotā", "The one who praises."],
  ["Raṇapriyaḥ", "The lover of battle against evil."],
  ["Pūrṇaḥ", "The full, the complete."],
  ["Pūrayitā", "The fulfiller."],
  ["Puṇyaḥ", "The holy."],
  ["Puṇyakīrtiḥ", "Of holy fame."],
  ["Anāmayaḥ", "Free from all illness."],
  ["Manojavaḥ", "Swift as thought."],
  ["Tīrthakaraḥ", "The maker of the fords of learning."],
  ["Vasuretāḥ", "Whose seed is gold."],
  ["Vasupradaḥ", "The giver of wealth."],
  ["Vasupradaḥ", "The giver of liberation, the highest wealth."],
  ["Vāsudevaḥ", "The son of Vasudeva."],
  ["Vasuḥ", "The one in whom all dwell."],
  ["Vasumanāḥ", "Whose mind dwells in all."],
  ["Haviḥ", "The oblation itself."],
  ["Sadgatiḥ", "The goal of the good."],
  ["Satkṛtiḥ", "Of good deeds."],
  ["Sattā", "Pure existence."],
  ["Sadbhūtiḥ", "Existence beyond all change."],
  ["Satparāyaṇaḥ", "The highest end of the wise."],
  ["Śūrasenaḥ", "With a heroic army."],
  ["Yaduśreṣṭhaḥ", "The best of the Yādavas."],
  ["Sannivāsaḥ", "The abode of the good."],
  ["Suyāmunaḥ", "Surrounded by the people of the Yamunā."],
  ["Bhūtāvāsaḥ", "The dwelling of all beings."],
  ["Vāsudevaḥ", "The one who covers the world with māyā."],
  ["Sarvāsunilayaḥ", "The home of all life."],
  ["Analaḥ", "Of limitless power."],
  ["Darpahā", "The destroyer of pride."],
  ["Darpadaḥ", "The one who gives pride in dharma."],
  ["Dṛptaḥ", "Ever joyful."],
  ["Durdharaḥ", "Hard to hold in the mind."],
  ["Aparājitaḥ", "The undefeated."],
  ["Viśvamūrtiḥ", "Whose body is the universe."],
  ["Mahāmūrtiḥ", "Of vast form."],
  ["Dīptamūrtiḥ", "Of blazing form."],
  ["Amūrtimān", "Formless."],
  ["Anekamūrtiḥ", "Of many forms."],
  ["Avyaktaḥ", "The unmanifest."],
  ["Śatamūrtiḥ", "Of a hundred forms."],
  ["Śatānanaḥ", "Of a hundred faces."],
  ["Ekaḥ", "The One."],
  ["Naikaḥ", "The many."],
  ["Savaḥ", "The soma sacrifice."],
  ["Kaḥ", "Bliss (“ka”)."],
  ["Kim", "The one to be inquired into."],
  ["Yat", "The one from whom all come."],
  ["Tat", "That."],
  ["Padam Anuttamam", "The highest state."],
  ["Lokabandhuḥ", "The kinsman of the world."],
  ["Lokanāthaḥ", "Lord of the world."],
  ["Mādhavaḥ", "Born in the Madhu clan."],
  ["Bhaktavatsalaḥ", "Tender towards His devotees."],
  ["Suvarṇavarṇaḥ", "Golden in colour."],
  ["Hemāṅgaḥ", "Golden-limbed."],
  ["Varāṅgaḥ", "Of beautiful limbs."],
  ["Candanāṅgadī", "Adorned with sandal and armlets."],
  ["Vīrahā", "Slayer of the mighty wicked."],
  ["Viṣamaḥ", "The unequalled."],
  ["Śūnyaḥ", "The empty, free of all qualities."],
  ["Ghṛtāśīḥ", "Free of all longing."],
  ["Acalaḥ", "The unmoving."],
  ["Calaḥ", "The moving, as the wind."],
  ["Amānī", "Without pride."],
  ["Mānadaḥ", "The one who gives honour to others."],
  ["Mānyaḥ", "The one to be honoured."],
  ["Lokasvāmī", "Master of the worlds."],
  ["Trilokadhṛk", "The upholder of the three worlds."],
  ["Sumedhāḥ", "Of perfect understanding."],
  ["Medhajaḥ", "Born of the sacrifice."],
  ["Dhanyaḥ", "The blessed, whose every end is met."],
  ["Satyamedhāḥ", "Whose wisdom is true."],
  ["Dharādharaḥ", "The one who bears the earth."],
  ["Tejovṛṣaḥ", "The one who rains light, as the sun."],
  ["Dyutidharaḥ", "The bearer of splendour."],
  ["Sarva-śastra-bhṛtāṃ Varaḥ", "The best of all who bear arms."],
  ["Pragrahaḥ", "The one who takes what devotees offer."],
  ["Nigrahaḥ", "The one who restrains all."],
  ["Vyagraḥ", "The one who has no end."],
  ["Naikaśṛṅgaḥ", "Many-horned — the four horns of the Veda."],
  ["Gadāgrajaḥ", "Elder brother of Gada."],
  ["Caturmūrtiḥ", "Of four forms."],
  ["Caturbāhuḥ", "Four-armed."],
  ["Caturvyūhaḥ", "Of four emanations."],
  ["Caturgatiḥ", "The goal of all four stages of life."],
  ["Caturātmā", "Whose mind is clear and free."],
  ["Caturbhāvaḥ", "The source of the four aims of life."],
  ["Caturvedavit", "Knower of the four Vedas."],
  ["Ekapāt", "The one of whom the whole universe is a single quarter."],
  ["Samāvartaḥ", "The one who turns the wheel of saṃsāra."],
  ["Anivṛttātmā", "The one who is present everywhere."],
  ["Durjayaḥ", "The unconquerable."],
  ["Duratikramaḥ", "The one whose command cannot be crossed."],
  ["Durlabhaḥ", "Hard to attain without devotion."],
  ["Durgamaḥ", "Hard to reach."],
  ["Durgaḥ", "The fortress, reached through many obstacles."],
  ["Durāvāsaḥ", "Hard to hold in the heart."],
  ["Durārihā", "The slayer of wicked foes."],
  ["Śubhāṅgaḥ", "Of beautiful limbs; the eight-limbed yoga."],
  ["Lokasāraṅgaḥ", "The one who takes the essence of the world."],
  ["Sutantuḥ", "The beautiful thread on which the world is strung."],
  ["Tantuvardhanaḥ", "The one who spins out that thread, and draws it back."],
  ["Indrakarmā", "Whose deeds are like Indra's."],
  ["Mahākarmā", "The doer of great deeds."],
  ["Kṛtakarmā", "The one who has done all there is to do."],
  ["Kṛtāgamaḥ", "The author of the Āgamas."],
  ["Udbhavaḥ", "The one who takes birth at will."],
  ["Sundaraḥ", "The beautiful."],
  ["Sundaḥ", "The compassionate."],
  ["Ratnanābhaḥ", "Of the jewelled navel."],
  ["Sulocanaḥ", "Of beautiful eyes."],
  ["Arkaḥ", "The one worshipped by the worshipful — the sun."],
  ["Vājasanaḥ", "The giver of food."],
  ["Śṛṅgī", "The horned Fish in the flood."],
  ["Jayantaḥ", "The conqueror."],
  ["Sarvavij-jayī", "All-knowing and all-conquering."],
  ["Suvarṇabinduḥ", "Golden-limbed; the syllable Om."],
  ["Akṣobhyaḥ", "The imperturbable."],
  ["Sarva-vāgīśvareśvaraḥ", "Lord of the lords of speech."],
  ["Mahāhradaḥ", "The great lake of bliss where yogis bathe."],
  ["Mahāgartaḥ", "The great abyss of māyā."],
  ["Mahābhūtaḥ", "The great being, beyond time."],
  ["Mahānidhiḥ", "The great treasure-house."],
  ["Kumudaḥ", "The one who delights the earth."],
  ["Kundaraḥ", "The one who lifted the earth, as the Boar."],
  ["Kundaḥ", "Pure as the jasmine flower."],
  ["Parjanyaḥ", "The rain-cloud, who quenches the three fevers."],
  ["Pāvanaḥ", "The purifier."],
  ["Anilaḥ", "The one who is never idle."],
  ["Amṛtāśaḥ", "The one who feeds on nectar."],
  ["Amṛtavapuḥ", "Of immortal body."],
  ["Sarvajñaḥ", "The omniscient."],
  ["Sarvatomukhaḥ", "With faces on every side."],
  ["Sulabhaḥ", "Easily reached — by a leaf, a flower, a drop of water."],
  ["Suvrataḥ", "Of the great vow."],
  ["Siddhaḥ", "The perfect."],
  ["Śatrujit", "The conqueror of foes."],
  ["Śatrutāpanaḥ", "The one who scorches the enemies of the gods."],
  ["Nyagrodhaḥ", "The banyan, rising above all."],
  ["Udumbaraḥ", "Above the sky; the fig tree that feeds."],
  ["Aśvatthaḥ", "The fig tree of the world, whose roots are above."],
  ["Cāṇūrāndhra-niṣūdanaḥ", "Slayer of the wrestler Cāṇūra."],
  ["Sahasrārciḥ", "Thousand-rayed."],
  ["Saptajihvaḥ", "Fire with seven tongues."],
  ["Saptaidhāḥ", "Of seven flames."],
  ["Saptavāhanaḥ", "Drawn by seven horses — the sun."],
  ["Amūrtiḥ", "Without form."],
  ["Anaghaḥ", "Without sin."],
  ["Acintyaḥ", "Beyond thought."],
  ["Bhayakṛt", "The one who puts fear in the wicked."],
  ["Bhayanāśanaḥ", "The destroyer of fear."],
  ["Aṇuḥ", "The subtlest."],
  ["Bṛhat", "The vast."],
  ["Kṛśaḥ", "The slender, the subtle."],
  ["Sthūlaḥ", "The gross — the universe."],
  ["Guṇabhṛt", "The bearer of qualities."],
  ["Nirguṇaḥ", "Beyond all qualities."],
  ["Mahān", "The great."],
  ["Adhṛtaḥ", "The one held up by nothing."],
  ["Svadhṛtaḥ", "Held up by Himself."],
  ["Svāsyaḥ", "Of beautiful face, from which the Veda came."],
  ["Prāgvaṃśaḥ", "Of the first lineage."],
  ["Vaṃśavardhanaḥ", "The one who makes the lineage grow."],
  ["Bhārabhṛt", "The one who carries the burden of the universe."],
  ["Kathitaḥ", "The one spoken of in all the scriptures."],
  ["Yogī", "The yogi."],
  ["Yogīśaḥ", "Lord of yogis."],
  ["Sarvakāmadaḥ", "The giver of all wishes."],
  ["Āśramaḥ", "The hermitage, the resting place of the weary."],
  ["Śramaṇaḥ", "The one who troubles the thoughtless."],
  ["Kṣāmaḥ", "The one who wastes all away at the end."],
  ["Suparṇaḥ", "The tree of the world, with the Vedas for leaves."],
  ["Vāyuvāhanaḥ", "The one who makes the wind move."],
  ["Dhanurdharaḥ", "The bearer of the bow — Rāma."],
  ["Dhanurvedaḥ", "The master of archery."],
  ["Daṇḍaḥ", "The rod of justice."],
  ["Damayitā", "The one who restrains."],
  ["Damaḥ", "Self-restraint itself."],
  ["Aparājitaḥ", "The unvanquished."],
  ["Sarvasahaḥ", "The one who bears all."],
  ["Niyantā", "The one who sets all to their duties."],
  ["Niyamaḥ", "The one who is subject to no rule."],
  ["Yamaḥ", "The one beyond death."],
  ["Sattvavān", "Full of strength and courage."],
  ["Sāttvikaḥ", "Established in goodness."],
  ["Satyaḥ", "The true."],
  ["Satya-dharma-parāyaṇaḥ", "Devoted to truth and dharma."],
  ["Abhiprāyaḥ", "The one all seek."],
  ["Priyārhaḥ", "Worthy of all we hold dear."],
  ["Arhaḥ", "The one worthy of worship."],
  ["Priyakṛt", "The one who does what pleases His devotees."],
  ["Prītivardhanaḥ", "The one who increases their love."],
  ["Vihāyasagatiḥ", "The one who moves through the sky."],
  ["Jyotiḥ", "Light."],
  ["Suruciḥ", "Of beautiful radiance."],
  ["Hutabhuk", "The one who eats the offerings in the fire."],
  ["Vibhuḥ", "The all-pervading."],
  ["Raviḥ", "The sun, who draws up the waters."],
  ["Virocanaḥ", "The one who shines in many ways."],
  ["Sūryaḥ", "The sun, the begetter."],
  ["Savitā", "The one who brings the world forth."],
  ["Ravilocanaḥ", "Whose eye is the sun."],
  ["Anantaḥ", "Endless."],
  ["Hutabhuk", "The receiver of oblations."],
  ["Bhoktā", "The enjoyer."],
  ["Sukhadaḥ", "The giver of joy."],
  ["Naikajaḥ", "Born many times."],
  ["Agrajaḥ", "The first-born."],
  ["Anirviṇṇaḥ", "Never weary."],
  ["Sadāmarṣī", "The one who forgives the good."],
  ["Lokādhiṣṭhānam", "The ground of the worlds."],
  ["Adbhutaḥ", "The wonderful."],
  ["Sanāt", "The eternal; time."],
  ["Sanātanatamaḥ", "The most ancient."],
  ["Kapilaḥ", "The tawny one; the sage Kapila."],
  ["Kapiḥ", "The sun; the Boar."],
  ["Apyayaḥ", "The one into whom all dissolve."],
  ["Svastidaḥ", "The giver of well-being."],
  ["Svastikṛt", "The maker of auspiciousness."],
  ["Svasti", "Auspiciousness itself."],
  ["Svastibhuk", "The one who enjoys and protects the good."],
  ["Svastidakṣiṇaḥ", "The one who swiftly grants well-being."],
  ["Araudraḥ", "Never cruel."],
  ["Kuṇḍalī", "Wearing earrings; the serpent Śeṣa."],
  ["Cakrī", "The bearer of the discus."],
  ["Vikramī", "The valiant."],
  ["Ūrjitaśāsanaḥ", "Whose command is mighty."],
  ["Śabdātigaḥ", "Beyond all words."],
  ["Śabdasahaḥ", "The one all the scriptures speak of."],
  ["Śiśiraḥ", "Cool, as the dewy season, to the troubled."],
  ["Śarvarīkaraḥ", "The maker of the night."],
  ["Akrūraḥ", "Never cruel."],
  ["Peśalaḥ", "Gentle and beautiful."],
  ["Dakṣaḥ", "Swift and able."],
  ["Dakṣiṇaḥ", "The liberal."],
  ["Kṣamiṇāṃ Varaḥ", "The best of the forgiving."],
  ["Vidvattamaḥ", "The wisest."],
  ["Vītabhayaḥ", "Beyond fear."],
  ["Puṇya-śravaṇa-kīrtanaḥ", "Hearing and singing of whom is holy."],
  ["Uttāraṇaḥ", "The one who lifts us across the ocean of saṃsāra."],
  ["Duṣkṛtihā", "The destroyer of evil deeds."],
  ["Puṇyaḥ", "The one who makes holy."],
  ["Duḥsvapna-nāśanaḥ", "The destroyer of bad dreams."],
  ["Vīrahā", "The one who ends our wandering on many paths."],
  ["Rakṣaṇaḥ", "The protector."],
  ["Santaḥ", "The good; the saints are His form."],
  ["Jīvanaḥ", "The life of all beings."],
  ["Paryavasthitaḥ", "The one who pervades on every side."],
  ["Anantarūpaḥ", "Of endless forms."],
  ["Anantaśrīḥ", "Of endless glory."],
  ["Jitamanyuḥ", "The one who has conquered anger."],
  ["Bhayāpahaḥ", "The remover of fear."],
  ["Caturasraḥ", "The just, who deals squarely."],
  ["Gabhīrātmā", "Of unfathomable nature."],
  ["Vidiśaḥ", "The one who gives in many ways."],
  ["Vyādiśaḥ", "The one who commands the gods."],
  ["Diśaḥ", "The one who teaches through the Vedas."],
  ["Anādiḥ", "Without beginning."],
  ["Bhūr Bhuvaḥ", "The earth and the ground of the earth."],
  ["Lakṣmīḥ", "The glory of the earth."],
  ["Suvīraḥ", "Of splendid ways."],
  ["Rucirāṅgadaḥ", "Wearing shining armlets."],
  ["Jananaḥ", "The one who brings beings to birth."],
  ["Jana-janmādiḥ", "The source of the births of beings."],
  ["Bhīmaḥ", "The fearsome."],
  ["Bhīmaparākramaḥ", "Of fearsome valour."],
  ["Ādhāranilayaḥ", "The foundation of the foundations."],
  ["Adhātā", "The one who has no support."],
  ["Puṣpahāsaḥ", "Who blossoms like a flower into the world."],
  ["Prajāgaraḥ", "The ever-wakeful."],
  ["Ūrdhvagaḥ", "The one who is above all."],
  ["Satpathācāraḥ", "The one who walks the path of the good."],
  ["Prāṇadaḥ", "The one who gives life back — as to Parīkṣit."],
  ["Praṇavaḥ", "Om."],
  ["Paṇaḥ", "The one who deals with each according to their deeds."],
  ["Pramāṇam", "The measure of all knowledge."],
  ["Prāṇanilayaḥ", "The home of life-breath."],
  ["Prāṇabhṛt", "The sustainer of life."],
  ["Prāṇajīvanaḥ", "The one who keeps beings alive through breath."],
  ["Tattvam", "Reality."],
  ["Tattvavit", "The knower of reality."],
  ["Ekātmā", "The one Self."],
  ["Janma-mṛtyu-jarātigaḥ", "Beyond birth, death and old age."],
  ["Bhūr-bhuvaḥ-svas-taruḥ", "The tree whose branches are the three worlds."],
  ["Tāraḥ", "The one who carries across."],
  ["Savitā", "The father of all."],
  ["Prapitāmahaḥ", "The great-grandfather — father of Brahmā."],
  ["Yajñaḥ", "Sacrifice."],
  ["Yajñapatiḥ", "Lord of sacrifice."],
  ["Yajvā", "The one who performs the sacrifice."],
  ["Yajñāṅgaḥ", "Whose limbs are the sacrifice — the Boar."],
  ["Yajñavāhanaḥ", "The one who carries the sacrifice to its fruit."],
  ["Yajñabhṛt", "The upholder of sacrifice."],
  ["Yajñakṛt", "The maker of sacrifice."],
  ["Yajñī", "The master of sacrifice."],
  ["Yajñabhuk", "The enjoyer of sacrifice."],
  ["Yajñasādhanaḥ", "The one reached through sacrifice."],
  ["Yajñāntakṛt", "The one who brings the sacrifice to its end."],
  ["Yajñaguhyam", "The secret of sacrifice."],
  ["Annam", "Food."],
  ["Annādaḥ", "The eater of food."],
  ["Ātmayoniḥ", "The one who is His own source."],
  ["Svayañjātaḥ", "Self-born."],
  ["Vaikhānaḥ", "The one who dug through the earth, as the Boar."],
  ["Sāmagāyanaḥ", "The singer of the Sāma chants."],
  ["Devakīnandanaḥ", "The son of Devakī."],
  ["Sraṣṭā", "The creator."],
  ["Kṣitīśaḥ", "Lord of the earth."],
  ["Pāpanāśanaḥ", "The destroyer of sin."],
  ["Śaṅkhabhṛt", "Bearer of the conch Pāñcajanya."],
  ["Nandakī", "Bearer of the sword Nandaka."],
  ["Cakrī", "Bearer of the discus Sudarśana."],
  ["Śārṅgadhanvā", "Bearer of the bow Śārṅga."],
  ["Gadādharaḥ", "Bearer of the mace Kaumodakī."],
  ["Rathāṅgapāṇiḥ", "Whose hand holds the chariot-wheel."],
  ["Akṣobhyaḥ", "The one who cannot be shaken."],
  ["Sarva-praharaṇāyudhaḥ", "Whose weapons are everything that strikes."],
];
