import type { Site } from './types';

/**
 * The twelve Jyotirlingas and the famous Shivalingas.
 *
 * The Jyotirlinga stories are retold, in our own words, from the Koti Rudra
 * Samhita of the Shiva Purana (chapter numbers differ a little between
 * editions; those given follow the common Sanskrit recension). Where a
 * well-known telling comes from elsewhere — a sthala purana, the Skanda
 * Purana, temple tradition — the source line says so. Temple histories give
 * the dates most historians accept; where a date is traditional it is marked.
 */

export const JYOTIRLINGAS: Site[] = [
  {
    id: 'somnath', kind: 'jyotirlinga', name: 'Somnath', sa: 'सोमनाथ', place: 'Prabhas Patan, Gujarat', lat: 20.89, lon: 70.4,
    story: 'The Moon married the twenty-seven daughters of Daksha, the stars of the lunar mansions, but loved only Rohini. Daksha, angry for the others, cursed him to waste away. The fading Moon came to Prabhasa, where the Saraswati meets the sea, and worshipped Shiva for six months. Shiva could not undo a curse, but he softened it: the Moon would wane for a fortnight and wax for a fortnight, for ever. Shiva stayed there as Somanatha, Lord of the Moon.',
    source: 'Shiva Purana, Koti Rudra Samhita 14',
    timeline: [['by tradition', 'The Moon raises the first shrine, of gold'], ['1026', 'Mahmud of Ghazni sacks the temple'], ['c. 1169', 'Kumarapala rebuilds it in stone'], ['1299 · 1395 · 1706', 'Destroyed, rebuilt, destroyed again'], ['1783', 'Ahilyabai Holkar builds a temple beside the ruins'], ['1951', 'The present temple is consecrated, facing the open sea']],
    biome: 'coast', style: 'nagara', difficulty: 1,
    task: { kind: 'lamps', title: 'Fifteen nights of the Moon', detail: 'Light a lamp for each night of the waxing moon, in order, before the tide turns.', count: 15, item: 'lamp' },
  },
  {
    id: 'mallikarjuna', kind: 'jyotirlinga', name: 'Mallikarjuna', sa: 'मल्लिकार्जुन', place: 'Srisailam, Andhra Pradesh', lat: 16.07, lon: 78.87,
    story: 'Shiva and Parvati set their sons a race: whoever circled the world first would marry first. Kartikeya flew off on his peacock; Ganesha simply walked round his parents, saying they were his whole world, and won. Hurt, Kartikeya went away south to the Krauncha mountain. His parents followed him there and stayed near him — Parvati as Mallika, the jasmine, and Shiva as Arjuna — and the place became Mallikarjuna. The Shakti Peetha of Bhramaramba shares the hill.',
    source: 'Shiva Purana, Koti Rudra Samhita 15',
    timeline: [['by tradition', 'Shiva and Parvati come to the Krauncha hill'], ['1st–2nd c. CE', 'Srisailam is named in Satavahana records'], ['14th c.', 'Reddi kings build the mandapa and the steps'], ['1677', 'Shivaji builds the gopuram on the north']],
    biome: 'hills', style: 'dravida', difficulty: 2,
    task: { kind: 'offer', title: 'Jasmine for Mallika', detail: 'Gather jasmine on the forest paths of the Nallamala hills and bring it to the shrine.', count: 12, item: 'jasmine' },
  },
  {
    id: 'mahakaleshwar', kind: 'jyotirlinga', name: 'Mahakaleshwar', sa: 'महाकालेश्वर', place: 'Ujjain, Madhya Pradesh', lat: 23.18, lon: 75.77,
    story: 'In Avanti lived the Brahmin Vedapriya and his four sons, all devoted to Shiva. The demon Dushana, made mighty by a boon, came to stamp out their worship. As he raised his weapons, the earth where they prayed split open and Shiva rose out of it as Mahakala, Great Time, and burned Dushana to ash with a single sound. The sons asked him to stay and protect the city, and he did. His linga faces south, towards death, and is worshipped at dawn with sacred ash.',
    source: 'Shiva Purana, Koti Rudra Samhita 16–17',
    timeline: [['by tradition', 'Mahakala rises from the earth at Avanti'], ['1234', 'Iltutmish raids Ujjain and breaks the temple'], ['1736', 'The Maratha minister Ramchandra Baba Shenvi rebuilds it'], ['2022', 'The Mahakal Lok corridor opens']],
    biome: 'city', style: 'nagara', difficulty: 3,
    task: { kind: 'demon', title: 'Dushana at the gate', detail: 'The demon Dushana storms the shrine. Hold him off with the trishul until Mahakala rises.', foe: 'Dushana', count: 6 },
  },
  {
    id: 'omkareshwar', kind: 'jyotirlinga', name: 'Omkareshwar', sa: 'ओंकारेश्वर', place: 'Mandhata island, Narmada, Madhya Pradesh', lat: 22.25, lon: 76.15,
    story: 'The Vindhya mountain, jealous of Mount Meru, worshipped Shiva for six months to grow great. Pleased, Shiva appeared and granted the boon, and at the gods\' request stayed there in two forms: Omkara on the island and Amaleshvara (Mamaleshwar) on the bank. The island in the Narmada is itself shaped like the syllable Om.',
    source: 'Shiva Purana, Koti Rudra Samhita 18',
    timeline: [['by tradition', 'Vindhya worships, and Shiva stays as Omkara'], ['11th c.', 'Paramara kings build on Mandhata island'], ['18th c.', 'The Holkars and Peshwas restore the temples'], ['1997', 'The Om-shaped island is linked by a new bridge']],
    biome: 'river', style: 'nagara', difficulty: 2,
    task: { kind: 'offer', title: 'Round the Om', detail: 'Walk the parikrama of the Om-shaped island and gather lotuses from the Narmada.', count: 10, item: 'lotus' },
  },
  {
    id: 'kedarnath', kind: 'jyotirlinga', name: 'Kedarnath', sa: 'केदारनाथ', place: 'Rudraprayag, Uttarakhand (3,583 m)', lat: 30.73, lon: 79.07,
    story: 'Nara and Narayana, two forms of Vishnu, did austerities at Badarikashrama and every day worshipped a linga of earth. Shiva was pleased and offered a boon; they asked him to stay on the Kedara peak for the good of all, and he did. In a later and well-loved telling, the Pandavas came here after the war seeking Shiva\'s forgiveness; he hid from them as a bull, and when Bhima caught it the bull sank into the earth, leaving its hump here — the other parts rising at the four other Panch Kedar shrines.',
    source: 'Shiva Purana, Koti Rudra Samhita 19; the Pandava story from Kedarkhand of the Skanda Purana and local tradition',
    timeline: [['by tradition', 'The Pandavas raise the first temple'], ['8th c.', 'Adi Shankaracharya restores it; his samadhi lies behind'], ['13th–17th c.', 'The temple lies under snow for long stretches of a little ice age'], ['2013', 'A flood sweeps the valley; a great boulder shields the temple']],
    biome: 'snow', style: 'himalayan', difficulty: 5,
    task: { kind: 'trek', title: 'The climb to Kedar', detail: 'Sixteen kilometres from Gaurikund at nearly 3,600 metres. Rest at the shelters or the thin air will stop you.', count: 6 },
  },
  {
    id: 'bhimashankar', kind: 'jyotirlinga', name: 'Bhimashankar', sa: 'भीमशंकर', place: 'Sahyadri hills, Pune, Maharashtra', lat: 19.07, lon: 73.54,
    story: 'Bhima, the son of Kumbhakarna, grew up in the forest with his mother Karkati and, learning that Rama had killed his father, did fierce penance for power. Made invincible by Brahma\'s boon, he conquered the three worlds and threw the devout King Sudakshina of Kamarupa into prison. The king went on worshipping a linga in his cell. When Bhima swung his sword at the linga, Shiva burst out of it and burned the demon to ash, and stayed there as Bhimashankara. The Bhima river rises here.',
    source: 'Shiva Purana, Koti Rudra Samhita 20–21',
    timeline: [['by tradition', 'Shiva rises from the prisoner\'s linga'], ['13th c.', 'An older shrine stands in the Sahyadri forest'], ['18th c.', 'Nana Phadnavis builds the present hall and shikhara']],
    biome: 'forest', style: 'hemadpanti', difficulty: 3,
    task: { kind: 'demon', title: 'The sword of Bhima', detail: 'Stand by Sudakshina\'s linga and drive back the demon Bhima.', foe: 'Bhima', count: 7 },
  },
  {
    id: 'kashi-vishwanath', kind: 'jyotirlinga', name: 'Kashi Vishwanath', sa: 'काशी विश्वनाथ', place: 'Varanasi, Uttar Pradesh', lat: 25.31, lon: 83.01,
    story: 'Kashi is Shiva\'s own city, Avimukta, the place he never leaves. At the dissolution of the worlds, when everything else goes under, he holds Kashi up on the tip of his trident. Here he is Vishveshvara, Lord of the Universe, and it is said that whoever dies in Kashi hears from him the mantra that sets them free.',
    source: 'Shiva Purana, Koti Rudra Samhita 22–23',
    timeline: [['by tradition', 'Shiva makes Kashi his home'], ['1194', 'The temple is destroyed by Qutb-ud-din Aibak\'s army'], ['1585', 'Raja Todar Mal rebuilds it'], ['1669', 'Aurangzeb razes it; the Gyanvapi mosque rises on the site'], ['1780', 'Ahilyabai Holkar builds the present temple'], ['1835', 'Maharaja Ranjit Singh gilds the domes'], ['2021', 'The Kashi Vishwanath corridor opens to the Ganga']],
    biome: 'river', style: 'nagara', difficulty: 2,
    task: { kind: 'water', title: 'Ganga jal through the lanes', detail: 'Fill your pot at the ghats and carry Ganga water through the lanes to Vishveshvara.', count: 5, item: 'pot' },
  },
  {
    id: 'trimbakeshwar', kind: 'jyotirlinga', name: 'Trimbakeshwar', sa: 'त्र्यंबकेश्वर', place: 'Brahmagiri, Nashik, Maharashtra', lat: 19.93, lon: 73.53,
    story: 'The sage Gautama lived on the Brahmagiri hill, and in a drought his penance kept the ashram fed. Jealous sages sent a frail cow into his field; when he waved it away with a blade of grass it fell dead, and he was made to bear the sin of killing a cow. To be cleansed he asked Shiva for the Ganga. Shiva released her there as the Godavari, the Gautami Ganga, and stayed as Tryambaka, the three-eyed. The linga here holds three small faces: Brahma, Vishnu and Shiva.',
    source: 'Shiva Purana, Koti Rudra Samhita 24–26',
    timeline: [['by tradition', 'The Godavari springs from Brahmagiri'], ['1755–1786', 'Peshwa Balaji Bajirao (Nanasaheb) builds the present black-stone temple']],
    biome: 'hills', style: 'nagara', difficulty: 2,
    task: { kind: 'water', title: 'The Gautami Ganga', detail: 'Carry water from the Kushavarta tank, where the Godavari begins, to the three-faced linga.', count: 5, item: 'pot' },
  },
  {
    id: 'vaidyanath', kind: 'jyotirlinga', name: 'Vaidyanath', sa: 'वैद्यनाथ', place: 'Deoghar, Jharkhand', lat: 24.49, lon: 86.7,
    story: 'Ravana worshipped Shiva on Kailasa and, when he was not answered, began cutting off his heads one by one as offerings. Shiva appeared, healed him like a physician — Vaidya — and let him carry a linga to Lanka, on the condition that it never touched the ground. The gods, afraid of Ravana armed with it, made him need to relieve himself on the way; he handed the linga to a cowherd, who set it down, and there it stayed. Some hold that the Jyotirlinga is at Parli Vaijnath in Maharashtra instead.',
    source: 'Shiva Purana, Koti Rudra Samhita 27–28',
    timeline: [['by tradition', 'Ravana\'s linga comes to rest at Deoghar'], ['1596', 'Raja Puran Mal of Gidhaur builds the present temple'], ['every Shravan', 'Kanwariyas carry Ganga water 108 km on foot from Sultanganj']],
    biome: 'plains', style: 'nagara', difficulty: 3,
    task: { kind: 'carry', title: 'Do not set it down', detail: 'Carry the linga to the temple steady in your hands — let it tip too far and it will stay where it falls.', count: 1 },
  },
  {
    id: 'nageshvara', kind: 'jyotirlinga', name: 'Nageshvara', sa: 'नागेश्वर', place: 'Daruka forest, near Dwarka, Gujarat', lat: 22.34, lon: 69.08,
    story: 'The demoness Daruka and her husband Daruka ruled a forest by the western sea and waylaid travellers. They captured the merchant Supriya, a devotee of Shiva, and chained him in their city. In his cell Supriya kept chanting the name of Shiva; when the demons came to kill him, Shiva appeared with his Pashupata weapon, destroyed the demons, and stayed as Nageshvara, Lord of the Serpents. Aundha Nagnath in Maharashtra and Jageshwar in the Himalaya also claim this Jyotirlinga.',
    source: 'Shiva Purana, Koti Rudra Samhita 29–30',
    timeline: [['by tradition', 'Shiva frees Supriya in the Daruka forest'], ['1990s', 'The present temple and the great seated Shiva image are built']],
    biome: 'coast', style: 'nagara', difficulty: 3,
    task: { kind: 'demon', title: 'Free Supriya', detail: 'Supriya is chained in the demon city. Defeat Daruka and break his chains.', foe: 'Daruka', count: 7 },
  },
  {
    id: 'rameshwaram', kind: 'jyotirlinga', name: 'Rameshwaram', sa: 'रामेश्वरम्', place: 'Pamban island, Tamil Nadu', lat: 9.29, lon: 79.32,
    story: 'Before crossing the sea to Lanka, Rama worshipped Shiva on the shore for victory, and Shiva, pleased, promised to stay there as Rameshvara. In the telling kept at the temple, Rama sent Hanuman to Kailasa for a linga; when Hanuman was late, Sita shaped one from sand, and that became the main linga. Hanuman\'s, the Vishvalinga, was installed beside it, and is worshipped first to this day.',
    source: 'Shiva Purana, Koti Rudra Samhita 31; the Hanuman story from the temple\'s sthala purana',
    timeline: [['by tradition', 'Rama and Sita worship the sand linga'], ['12th c.', 'Parakramabahu of Sri Lanka enlarges the sanctum'], ['17th–18th c.', 'The Sethupathi kings build the corridors, the longest in India']],
    biome: 'island', style: 'dravida', difficulty: 2,
    task: { kind: 'water', title: 'Twenty-two wells', detail: 'Bathe at the temple\'s holy wells, one after another, and bring their water to Ramanatha.', count: 8, item: 'pot' },
  },
  {
    id: 'grishneshwar', kind: 'jyotirlinga', name: 'Grishneshwar', sa: 'घृष्णेश्वर', place: 'Verul, near Ellora, Maharashtra', lat: 20.02, lon: 75.17,
    story: 'Sudharma and Sudeha had no child, so Sudeha had her husband marry her sister Ghushma, who made a hundred and one lingas of clay every day and set them in a lake. Ghushma bore a son, and Sudeha, eaten by jealousy, killed him and threw him into the same lake. Ghushma did not stop her worship. As she set that day\'s lingas in the water her son walked out of it alive, and Shiva appeared. At her wish he forgave Sudeha, and stayed as Ghushmeshvara.',
    source: 'Shiva Purana, Koti Rudra Samhita 32–33',
    timeline: [['by tradition', 'Ghushma\'s son returns from the lake'], ['16th c.', 'Maloji Bhosale, Shivaji\'s grandfather, restores it'], ['18th c.', 'Ahilyabai Holkar rebuilds it in red stone']],
    biome: 'plains', style: 'hemadpanti', difficulty: 2,
    task: { kind: 'offer', title: 'A hundred and one', detail: 'Gather clay from the lake shore to shape lingas, as Ghushma did every day.', count: 21, item: 'clay' },
  },
];

const SHIVA_Q = (a: string, b: string, c: string, d: string, i: number): [string, string[], number] => [a, [b, c, d], i];

export const LINGAS: Site[] = [
  {
    id: 'kailash', kind: 'linga', name: 'Mount Kailash', sa: 'कैलास', place: 'Ngari, Tibet (6,638 m)', lat: 31.07, lon: 81.31,
    story: 'Kailasa is Shiva\'s own home, where he sits in meditation with Parvati, Ganesha, Kartikeya and Nandi. It is the mountain Ravana tried to lift and was pinned under by Shiva\'s toe, and where the gods come for refuge. Nobody climbs it; pilgrims walk the 52-kilometre kora around it.',
    source: 'Shiva Purana, Rudra Samhita', timeline: [['by tradition', 'Shiva\'s abode'], ['every year', 'Pilgrims walk the kora, crossing the Dolma La at 5,630 m']],
    biome: 'snow', style: 'natural', difficulty: 5,
    task: { kind: 'trek', title: 'The kora', detail: 'Walk round the mountain over the Dolma La pass. The air is thin; rest often.', count: 8 },
  },
  {
    id: 'amarnath', kind: 'linga', name: 'Amarnath', sa: 'अमरनाथ', place: 'Lidder valley, Jammu & Kashmir (3,888 m)', lat: 34.21, lon: 75.5,
    story: 'In this cave Shiva told Parvati the secret of immortality, the Amar Katha, having left Nandi, his serpents, the moon and Ganesha behind on the way so that no one would overhear. A pair of doves hidden in the cave heard it all, and are said to live there still. Every summer a linga of ice forms in the cave, waxing and waning with the moon.',
    source: 'Amarnath Mahatmya; Bhringish Samhita (local tradition)', timeline: [['by tradition', 'Shiva tells Parvati the Amar Katha'], ['1850', 'A shepherd, Buta Malik, rediscovers the cave'], ['every Shravan', 'The yatra climbs to the ice linga']],
    biome: 'snow', style: 'cave', difficulty: 5,
    task: { kind: 'trek', title: 'To the ice linga', detail: 'Climb from Pahalgam past Sheshnag and the Mahagunas pass to the cave before the snow closes in.', count: 7 },
  },
  {
    id: 'pashupatinath', kind: 'linga', name: 'Pashupatinath', sa: 'पशुपतिनाथ', place: 'Kathmandu, Nepal', lat: 27.71, lon: 85.35,
    story: 'Shiva once hid from the gods as a golden deer in the forest on the Bagmati. When they found him and caught him by the horn, it broke, and the horn became the linga — Pashupati, Lord of all creatures. The linga has four faces and a fifth looking up.',
    source: 'Nepala Mahatmya of the Skanda Purana', timeline: [['5th c.', 'Earliest records of the shrine'], ['1692', 'The present two-roofed pagoda is rebuilt']],
    biome: 'river', style: 'pagoda', difficulty: 2,
    task: { kind: 'bells', title: 'The evening aarti', detail: 'Ring the bells in time with the aarti on the Bagmati.', count: 12 },
  },
  {
    id: 'lingaraj', kind: 'linga', name: 'Lingaraj', sa: 'लिंगराज', place: 'Bhubaneswar, Odisha', lat: 20.24, lon: 85.83,
    story: 'Ekamra, the forest of one mango tree, was where Parvati slew the demons Kirti and Vasa and Shiva made his home. The linga here is Harihara — Shiva and Vishnu in one — so it is worshipped with bilva and tulsi together.',
    source: 'Ekamra Purana', timeline: [['11th c.', 'The Somavamshi kings raise the 55-metre deul'], ['12th c.', 'The Eastern Gangas add the halls']],
    biome: 'city', style: 'kalinga', difficulty: 1,
    task: { kind: 'offer', title: 'Bilva and tulsi', detail: 'Gather bilva leaves for Hara and tulsi for Hari.', count: 10, item: 'bilva' },
  },
  {
    id: 'brihadeeswarar', kind: 'linga', name: 'Brihadeeswarar', sa: 'बृहदीश्वर', place: 'Thanjavur, Tamil Nadu', lat: 10.78, lon: 79.13,
    story: 'Rajaraja Chola built the Great Temple to Shiva as Peruvudaiyar, with a vimana 66 metres high crowned by a single 80-tonne stone. Its linga is among the largest in India, and the walls carry the names of the dancers, musicians and lamp-keepers the king endowed.',
    source: 'Temple inscriptions of Rajaraja I', timeline: [['1003', 'Rajaraja Chola begins the temple'], ['1010', 'The temple is consecrated'], ['1987', 'Listed a UNESCO World Heritage Site']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'lamps', title: 'The perpetual lamps', detail: 'Rajaraja endowed lamps to burn day and night. Light them round the courtyard.', count: 12, item: 'lamp' },
  },
  {
    id: 'ekambareswarar', kind: 'linga', name: 'Ekambareswarar (earth)', sa: 'एकाम्बरेश्वर', place: 'Kanchipuram, Tamil Nadu', lat: 12.85, lon: 79.7,
    story: 'Parvati did penance under a mango tree by the Vegavati and shaped a linga of sand. Shiva sent a flood to test her; she held the linga in her arms and it survived. It is the Prithvi linga, the earth among the five elemental lingas, and is anointed with jasmine oil, not water.',
    source: 'Kanchi Mahatmya; Pancha Bhuta Sthala tradition', timeline: [['by tradition', 'Parvati embraces the sand linga'], ['c. 600', 'The Pallavas build the first temple'], ['1509', 'Krishnadevaraya builds the great gopuram']],
    biome: 'city', style: 'dravida', difficulty: 1,
    task: { kind: 'offer', title: 'The sand linga', detail: 'Gather mango leaves and jasmine for the linga of earth.', count: 10, item: 'jasmine' },
  },
  {
    id: 'jambukeswarar', kind: 'linga', name: 'Jambukeswarar (water)', sa: 'जम्बुकेश्वर', place: 'Thiruvanaikaval, Tamil Nadu', lat: 10.85, lon: 78.71,
    story: 'An elephant and a spider both worshipped a linga under a jambu tree — the spider wove a web to shade it, the elephant washed it with river water, each undoing the other\'s offering. The linga sits over an underground spring, and water seeps up around it all year: it is the Appu linga, water among the five elements.',
    source: 'Pancha Bhuta Sthala tradition', timeline: [['c. 2nd c.', 'Said to be built by Kochengan Chola'], ['later Chola & Nayak', 'Five walled courtyards grow around it']],
    biome: 'river', style: 'dravida', difficulty: 1,
    task: { kind: 'water', title: 'The elephant and the spider', detail: 'Carry water from the Kaveri, as the elephant did.', count: 5, item: 'pot' },
  },
  {
    id: 'arunachaleswarar', kind: 'linga', name: 'Arunachaleswarar (fire)', sa: 'अरुणाचलेश्वर', place: 'Tiruvannamalai, Tamil Nadu', lat: 12.23, lon: 79.07,
    story: 'Brahma and Vishnu quarrelled over who was greater, and between them appeared a pillar of fire without end. Vishnu dug down as a boar and Brahma flew up as a swan, and neither found an end. The pillar became the hill Arunachala, the Agni linga. Every Karthikai a beacon is lit on its summit.',
    source: 'Shiva Purana, Vidyeshvara Samhita 5–9 (the Lingodbhava); Arunachala Mahatmya', timeline: [['by tradition', 'The pillar of fire becomes a hill'], ['9th c.', 'The Cholas build the first temple'], ['16th c.', 'Krishnadevaraya builds the eastern gopuram, 66 m']],
    biome: 'hills', style: 'dravida', difficulty: 2,
    task: { kind: 'lamps', title: 'Karthikai deepam', detail: 'Light lamps up the hill to the beacon on the summit.', count: 12, item: 'lamp' },
  },
  {
    id: 'srikalahasti', kind: 'linga', name: 'Srikalahasti (air)', sa: 'श्रीकालहस्ती', place: 'Srikalahasti, Andhra Pradesh', lat: 13.75, lon: 79.7,
    story: 'A spider (sri), a serpent (kala) and an elephant (hasti) worshipped the linga here, and all three were freed. So was the hunter Kannappa, who, seeing the linga\'s eye bleed, offered his own eyes. It is the Vayu linga: a lamp in the sanctum flickers though no breeze can reach it.',
    source: 'Pancha Bhuta Sthala tradition; Periya Puranam (Kannappa)', timeline: [['5th c.', 'Pallava beginnings'], ['1516', 'Krishnadevaraya builds the hundred-pillared hall']],
    biome: 'hills', style: 'dravida', difficulty: 2,
    task: { kind: 'quiz', title: 'Kannappa\'s eyes', detail: 'Answer the priest\'s questions about the hunter who gave his eyes.' },
    quiz: [SHIVA_Q('Which three creatures give Srikalahasti its name?', 'A spider, a snake and an elephant', 'A cow, a deer and a horse', 'A swan, a boar and a lion', 0), SHIVA_Q('What did the hunter Kannappa offer the linga?', 'His bow', 'His own eyes', 'A thousand lotuses', 1), SHIVA_Q('Which element is Srikalahasti\'s linga?', 'Water', 'Fire', 'Air', 2)],
  },
  {
    id: 'chidambaram', kind: 'linga', name: 'Thillai Nataraja (space)', sa: 'चिदम्बरम्', place: 'Chidambaram, Tamil Nadu', lat: 11.4, lon: 79.69,
    story: 'In the Thillai forest Shiva danced the Ananda Tandava, the dance of bliss, before the sages Patanjali and Vyaghrapada. Here he is worshipped as Nataraja, and as the Akasha linga — space itself: behind a curtain in the sanctum there is nothing but a hanging garland of gold bilva leaves, the "secret of Chidambaram".',
    source: 'Chidambaram Mahatmya; Pancha Bhuta Sthala tradition', timeline: [['by tradition', 'Shiva dances in the Thillai forest'], ['10th c.', 'The Cholas cover the Chit Sabha roof in gold'], ['12th–13th c.', 'The four great gopurams rise, carved with the 108 karanas of dance']],
    biome: 'city', style: 'dravida', difficulty: 2,
    task: { kind: 'bells', title: 'The cosmic dance', detail: 'Keep the rhythm of Nataraja\'s drum.', count: 14 },
  },
  {
    id: 'murudeshwar', kind: 'linga', name: 'Murudeshwar', sa: 'मुरुडेश्वर', place: 'Bhatkal, Karnataka', lat: 14.09, lon: 74.48,
    story: 'When Ravana tore at the Atmalinga at Gokarna, he flung away the cloth that covered it; it fell on the Kanduka hill by the sea, and that became Murudeshwar. Today a 37-metre Shiva sits above the waves beside a twenty-storey gopuram.',
    source: 'Gokarna Mahatmya (Skanda Purana) and temple tradition', timeline: [['by tradition', 'The cloth of the Atmalinga falls on Kanduka hill'], ['2006', 'The great Shiva statue is completed']],
    biome: 'coast', style: 'dravida', difficulty: 1,
    task: { kind: 'offer', title: 'Shells for the shore', detail: 'Gather offerings along the beach below the great Shiva.', count: 10, item: 'flower' },
  },
  {
    id: 'gokarna', kind: 'linga', name: 'Gokarna Mahabaleshwar', sa: 'गोकर्ण', place: 'Gokarna, Karnataka', lat: 14.54, lon: 74.32,
    story: 'Ravana was carrying Shiva\'s own Atmalinga to Lanka; it would stay wherever it first touched the ground. Ganesha, disguised as a boy, offered to hold it while Ravana said his evening prayers, and set it down. Ravana pulled so hard it twisted into the shape of a cow\'s ear — Go-karna — and Mahabala, the mighty one, stays there.',
    source: 'Gokarna Mahatmya of the Skanda Purana', timeline: [['by tradition', 'Ganesha sets the Atmalinga down'], ['4th c.', 'Kadamba kings patronise the shrine']],
    biome: 'coast', style: 'dravida', difficulty: 3,
    task: { kind: 'carry', title: 'The Atmalinga', detail: 'Carry the Atmalinga without letting it touch the ground before the shrine.', count: 1 },
  },
  {
    id: 'lepakshi', kind: 'linga', name: 'Lepakshi', sa: 'लेपाक्षी', place: 'Sri Sathya Sai district, Andhra Pradesh', lat: 13.8, lon: 77.61,
    story: 'Here, it is said, Rama found the wounded Jatayu and said "Le pakshi" — rise, bird. The Veerabhadra temple holds a pillar that does not touch the floor, a great naga coiled over a linga cut from one boulder, and outside, one of the largest monolithic Nandis in India.',
    source: 'Temple tradition', timeline: [['1530s', 'Virupanna and Viranna, governors under Achyuta Deva Raya, build the temple'], ['16th c.', 'The painted ceilings of the dance hall are finished']],
    biome: 'hills', style: 'dravida', difficulty: 1,
    task: { kind: 'quiz', title: 'Rise, bird', detail: 'Answer the guide\'s questions.' },
    quiz: [SHIVA_Q('What does "Le pakshi" mean?', 'Rise, bird', 'Hide, snake', 'Come, king', 0), SHIVA_Q('What is special about one of Lepakshi\'s pillars?', 'It sings when struck', 'It hangs without touching the floor', 'It is made of gold', 1), SHIVA_Q('What coils over the linga cut from a boulder?', 'A garland', 'A peacock', 'A seven-hooded naga', 2)],
  },
  {
    id: 'gudimallam', kind: 'linga', name: 'Gudimallam', sa: 'गुडिमल्लम्', place: 'Chittoor, Andhra Pradesh', lat: 13.64, lon: 79.61,
    story: 'The linga at Gudimallam, carved around the 2nd or 1st century BCE, is among the oldest known: a standing Shiva, holding a ram and an axe, is carved on the shaft itself, standing on the shoulders of a dwarf. It is a direct link to how Shiva was worshipped two thousand years ago.',
    source: 'Archaeological Survey of India', timeline: [['2nd–1st c. BCE', 'The linga is carved'], ['9th c.', 'The Pallava–Bana temple is built around it']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'quiz', title: 'The oldest linga', detail: 'Answer the archaeologist\'s questions.' },
    quiz: [SHIVA_Q('Roughly how old is the Gudimallam linga?', 'About 200 years', 'About 2,000 years', 'About 20,000 years', 1), SHIVA_Q('What is carved on the shaft?', 'A standing Shiva', 'A lotus', 'Script only', 0), SHIVA_Q('What does the carved Shiva stand on?', 'A lotus', 'A bull', 'The shoulders of a dwarf', 2)],
  },
  {
    id: 'bhojeshwar', kind: 'linga', name: 'Bhojeshwar', sa: 'भोजेश्वर', place: 'Bhojpur, Madhya Pradesh', lat: 23.1, lon: 77.58,
    story: 'King Bhoja of the Paramaras began a temple on a cliff above the Betwa to hold one of the largest lingas in India, over 7 metres with its base. It was never finished. Drawings of its plan are scratched into the rocks nearby, and the earthen ramp used to haul up the stones is still there.',
    source: 'Archaeological Survey of India', timeline: [['c. 1035', 'Raja Bhoja begins the temple'], ['unfinished', 'Work stops; the plans stay carved in the quarry'], ['2007', 'The ASI roofs the sanctum']],
    biome: 'river', style: 'nagara', difficulty: 1,
    task: { kind: 'offer', title: 'The unfinished temple', detail: 'Gather flowers for the giant linga that was never roofed.', count: 8, item: 'flower' },
  },
  {
    id: 'kotilingeshwara', kind: 'linga', name: 'Kotilingeshwara', sa: 'कोटिलिंगेश्वर', place: 'Kammasandra, Kolar, Karnataka', lat: 13.03, lon: 78.29,
    story: 'Swami Sambha Shiva Murthy began this temple in 1980 with one linga, and devotees have added their own ever since, towards the ten million of its name. At its centre stands a 33-metre linga with an 11-metre Nandi before it.',
    source: 'Temple tradition', timeline: [['1980', 'The first linga is installed'], ['1994', 'The 33-metre linga is completed']],
    biome: 'plains', style: 'modern', difficulty: 1,
    task: { kind: 'offer', title: 'Add a linga', detail: 'Gather bilva leaves for the field of ten million lingas.', count: 10, item: 'bilva' },
  },
  {
    id: 'tungnath', kind: 'linga', name: 'Tungnath', sa: 'तुंगनाथ', place: 'Chopta, Uttarakhand (3,680 m)', lat: 30.49, lon: 79.22,
    story: 'The highest Shiva temple in the world. In the Panch Kedar story, when Shiva as a bull sank into the earth at Kedarnath, his arms rose here.',
    source: 'Kedarkhand, Skanda Purana; Panch Kedar tradition', timeline: [['by tradition', 'Shiva\'s arms appear here'], ['8th c.', 'Tradition credits the temple\'s revival to Adi Shankaracharya']],
    biome: 'snow', style: 'himalayan', difficulty: 4,
    task: { kind: 'trek', title: 'Above the meadows', detail: 'Climb from Chopta through the bugyals to the highest Shiva temple.', count: 5 },
  },
  {
    id: 'rudranath', kind: 'linga', name: 'Rudranath', sa: 'रुद्रनाथ', place: 'Chamoli, Uttarakhand (2,286 m)', lat: 30.52, lon: 79.33,
    story: 'In the Panch Kedar story, Shiva\'s face appeared here; he is worshipped as Nilakantha in a natural rock temple, reached by one of the hardest treks of the five.',
    source: 'Panch Kedar tradition', timeline: [['by tradition', 'Shiva\'s face appears'], ['winter', 'The deity moves down to Gopinath temple, Gopeshwar']],
    biome: 'snow', style: 'cave', difficulty: 5,
    task: { kind: 'trek', title: 'The face of Rudra', detail: 'A long climb through oak and rhododendron to the rock shrine.', count: 7 },
  },
  {
    id: 'madhyamaheshwar', kind: 'linga', name: 'Madhyamaheshwar', sa: 'मध्यमहेश्वर', place: 'Rudraprayag, Uttarakhand (3,497 m)', lat: 30.64, lon: 79.22,
    story: 'The navel and belly of the bull rose here, in the Panch Kedar story; the linga is navel-shaped.',
    source: 'Panch Kedar tradition', timeline: [['by tradition', 'Shiva\'s navel appears']],
    biome: 'snow', style: 'himalayan', difficulty: 4,
    task: { kind: 'trek', title: 'The middle shrine', detail: 'Trek from Ransi through the forest to the meadow shrine.', count: 6 },
  },
  {
    id: 'kalpeshwar', kind: 'linga', name: 'Kalpeshwar', sa: 'कल्पेश्वर', place: 'Urgam valley, Uttarakhand (2,200 m)', lat: 30.58, lon: 79.42,
    story: 'Shiva\'s matted hair appeared here, in the Panch Kedar story; he is worshipped as Jateshwar in a small cave temple — the only one of the five open all year.',
    source: 'Panch Kedar tradition', timeline: [['by tradition', 'Shiva\'s hair appears']],
    biome: 'forest', style: 'cave', difficulty: 3,
    task: { kind: 'trek', title: 'The matted locks', detail: 'Walk up the Urgam valley to the cave shrine.', count: 4 },
  },
  {
    id: 'amararama', kind: 'linga', name: 'Amararama', sa: 'अमरारामम्', place: 'Amaravati, Andhra Pradesh', lat: 16.57, lon: 80.36,
    story: 'The demon Tarakasura wore a linga at his throat and could not be killed while it stayed whole. When Kartikeya\'s spear shattered it, the linga broke into five pieces that fell at the five Pancharama shrines. At Amararama, Indra himself is said to have installed the piece.',
    source: 'Pancharama tradition (Skanda Purana)', timeline: [['by tradition', 'A piece of Taraka\'s linga falls here'], ['10th–11th c.', 'Chalukya-era temple on the Krishna']],
    biome: 'river', style: 'dravida', difficulty: 2,
    task: { kind: 'demon', title: 'Tarakasura', detail: 'Stand with Kartikeya against Tarakasura.', foe: 'Tarakasura', count: 6 },
  },
  {
    id: 'draksharama', kind: 'linga', name: 'Draksharama', sa: 'द्राक्षारामम्', place: 'Konaseema, Andhra Pradesh', lat: 16.79, lon: 82.06,
    story: 'Where Daksha held the sacrifice that Sati entered the fire at, according to local tradition — and so one of the Pancharamas and a Shakti Peetha at once. Surya installed the piece of Taraka\'s linga here; Bhimeshwara is a tall linga reaching two storeys.',
    source: 'Pancharama tradition', timeline: [['by tradition', 'Daksha\'s sacrifice'], ['9th–10th c.', 'Eastern Chalukya king Bhima builds the temple']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'offer', title: 'Bilva for Bhimeshwara', detail: 'Gather bilva leaves for the two-storey linga.', count: 10, item: 'bilva' },
  },
  {
    id: 'somarama', kind: 'linga', name: 'Somarama', sa: 'सोमारामम्', place: 'Bhimavaram, Andhra Pradesh', lat: 16.54, lon: 81.52,
    story: 'The Moon installed this piece of Taraka\'s linga, and the linga is said to change colour with the moon — white at full moon, dark at new moon.',
    source: 'Pancharama tradition', timeline: [['by tradition', 'The Moon installs the linga'], ['10th c.', 'Chalukya temple']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'lamps', title: 'Moonlight', detail: 'Light lamps for the moon\'s phases around the tank.', count: 10, item: 'lamp' },
  },
  {
    id: 'ksheerarama', kind: 'linga', name: 'Ksheerarama', sa: 'क्षीरारामम्', place: 'Palakollu, Andhra Pradesh', lat: 16.52, lon: 81.73,
    story: 'Here Shiva struck the earth with his trident and a stream of milk sprang up — kshira — and Vishnu installed the piece of Taraka\'s linga. The gopuram rises nine storeys over the flat delta.',
    source: 'Pancharama tradition', timeline: [['by tradition', 'Milk springs from the earth'], ['9th–10th c.', 'Chalukya temple']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'water', title: 'The milk spring', detail: 'Carry milk from the spring to the linga.', count: 5, item: 'pot' },
  },
  {
    id: 'kumararama', kind: 'linga', name: 'Kumararama', sa: 'कुमारारामम्', place: 'Samalkot, Andhra Pradesh', lat: 17.05, lon: 82.17,
    story: 'Kartikeya — Kumara — himself installed this piece of the linga he had shattered to kill Tarakasura. The temple is built like its twin at Draksharama, with a two-storey linga.',
    source: 'Pancharama tradition', timeline: [['by tradition', 'Kumara installs the linga'], ['9th–10th c.', 'Eastern Chalukya king Bhima builds it']],
    biome: 'plains', style: 'dravida', difficulty: 1,
    task: { kind: 'bells', title: 'Kumara\'s victory', detail: 'Ring the bells for the victory over Taraka.', count: 10 },
  },
  {
    id: 'ellora-kailasa', kind: 'linga', name: 'Kailasa, Ellora (Cave 16)', sa: 'कैलास', place: 'Ellora, Maharashtra', lat: 20.02, lon: 75.18,
    story: 'The Rashtrakuta king Krishna I had a whole temple carved downward out of one basalt hill: Kailasa, Shiva\'s mountain, made in stone. Some 200,000 tonnes of rock were cut away over about two decades, from the top down.',
    source: 'Archaeological Survey of India', timeline: [['756–773', 'Krishna I has the temple carved from the living rock'], ['1983', 'Ellora is listed as a UNESCO World Heritage Site']],
    biome: 'hills', style: 'rock', difficulty: 2,
    task: { kind: 'quiz', title: 'Carved from above', detail: 'Answer the stone-carver\'s questions.' },
    quiz: [SHIVA_Q('How was the Kailasa temple made?', 'Built from bricks', 'Carved down out of one hill', 'Cast in bronze', 1), SHIVA_Q('Which dynasty made it?', 'The Rashtrakutas', 'The Mughals', 'The Cholas', 0), SHIVA_Q('What mountain does it represent?', 'Meru', 'Mandara', 'Kailasa', 2)],
  },
  {
    id: 'elephanta', kind: 'linga', name: 'Elephanta Caves', sa: 'घारापुरी', place: 'Gharapuri island, Mumbai harbour', lat: 18.96, lon: 72.93,
    story: 'On an island in Mumbai\'s harbour, a cave holds the six-metre Sadashiva: three faces of Shiva — the creator, the keeper and the destroyer — carved in one wall, with a linga shrine in the hall.',
    source: 'Archaeological Survey of India', timeline: [['5th–6th c.', 'The caves are carved'], ['1987', 'Listed a UNESCO World Heritage Site']],
    biome: 'island', style: 'cave', difficulty: 2,
    task: { kind: 'lamps', title: 'Into the cave', detail: 'Light your way through the pillared hall to the three faces.', count: 10, item: 'lamp' },
  },
  {
    id: 'jageshwar', kind: 'linga', name: 'Jageshwar', sa: 'जागेश्वर', place: 'Almora, Uttarakhand', lat: 29.64, lon: 79.85,
    story: 'A cluster of 124 stone temples in a deodar forest, some claiming the Nageshvara Jyotirlinga. The rulers of Kumaon built and rebuilt here for six centuries.',
    source: 'Archaeological Survey of India; local tradition', timeline: [['9th–13th c.', 'The Katyuri kings build most of the temples'], ['14th–18th c.', 'The Chand kings add more']],
    biome: 'forest', style: 'himalayan', difficulty: 3,
    task: { kind: 'lamps', title: 'Among the deodars', detail: 'Light lamps at the temples among the deodars before dusk.', count: 12, item: 'lamp' },
  },
  {
    id: 'nilkanth', kind: 'linga', name: 'Neelkanth Mahadev', sa: 'नीलकंठ महादेव', place: 'Rishikesh, Uttarakhand', lat: 30.08, lon: 78.34,
    story: 'When gods and demons churned the ocean, a poison, halahala, rose that would have burned the worlds. Shiva drank it and Parvati held his throat so it went no further, turning it blue — Nilakantha. Tradition places the drinking here, in the hills above Rishikesh.',
    source: 'Shiva Purana, Rudra Samhita (the churning); local tradition', timeline: [['by tradition', 'Shiva drinks the poison'], ['every Shravan', 'Kanwariyas bring Ganga water from Haridwar']],
    biome: 'forest', style: 'nagara', difficulty: 2,
    task: { kind: 'water', title: 'To cool the poison', detail: 'Carry Ganga water up the forest path to cool Nilakantha\'s throat.', count: 5, item: 'pot' },
  },
  {
    id: 'shore-temple', kind: 'linga', name: 'Shore Temple', sa: 'मामल्लपुरम्', place: 'Mamallapuram, Tamil Nadu', lat: 12.62, lon: 80.2,
    story: 'The Pallava king Narasimhavarman II built these granite shrines to Shiva right on the beach, where the sea has washed them for thirteen centuries. The 2004 tsunami briefly uncovered older remains beside it.',
    source: 'Archaeological Survey of India', timeline: [['c. 700–728', 'Rajasimha builds the Shore Temple'], ['1984', 'Listed a UNESCO World Heritage Site'], ['2004', 'The tsunami exposes buried sculptures']],
    biome: 'coast', style: 'dravida', difficulty: 1,
    task: { kind: 'offer', title: 'Against the tide', detail: 'Gather flowers along the shore before the waves reach the shrine.', count: 10, item: 'flower' },
  },
  {
    id: 'virupaksha', kind: 'linga', name: 'Virupaksha, Hampi', sa: 'विरूपाक्ष', place: 'Hampi, Karnataka', lat: 15.33, lon: 76.46,
    story: 'Here Pampa, a local form of Parvati, won Shiva as her husband by her penance, and he stays as Virupaksha. The temple was the heart of Vijayanagara and has been worshipped in without a break since the 7th century, through the city\'s fall in 1565.',
    source: 'Pampa Mahatmya; local tradition', timeline: [['7th c.', 'The first shrine'], ['1510', 'Krishnadevaraya builds the hall for his coronation'], ['1565', 'Vijayanagara falls; the temple keeps its worship']],
    biome: 'hills', style: 'dravida', difficulty: 2,
    task: { kind: 'bells', title: 'The coronation hall', detail: 'Ring the bells for Virupaksha and Pampa\'s wedding.', count: 12 },
  },
  {
    id: 'tarakeswar', kind: 'linga', name: 'Tarakeswar', sa: 'तारकेश्वर', place: 'Hooghly, West Bengal', lat: 22.89, lon: 88.02,
    story: 'A Shiva who cures and saves, found, it is said, by a cowherd whose cow gave its milk to a stone in the forest. In Shravan, pilgrims walk barefoot from the Ganga with water for him.',
    source: 'Temple tradition', timeline: [['1729', 'Raja Bharamalla builds the temple']],
    biome: 'plains', style: 'bengal', difficulty: 1,
    task: { kind: 'water', title: 'Barefoot from the Ganga', detail: 'Carry Ganga water to Taraknath.', count: 4, item: 'pot' },
  },
];
