import type { Site } from './types';

/**
 * The fifty-one Shakti Peethas — where the parts of Sati's body fell.
 *
 * When Daksha insulted Shiva at his great sacrifice, Sati, Daksha's daughter
 * and Shiva's wife, gave up her body in the sacrificial fire. Shiva, mad with
 * grief, carried her body across the worlds in a dance that threatened to end
 * them; Vishnu cut it apart with his discus, and wherever a part fell became a
 * seat of the goddess, each guarded by a form of Shiva as Bhairava.
 *
 * Names, the part of the body, the goddess and her Bhairava come from the
 * MIT-licensed npm package hindu-devotional-texts (the 51 of the Sati list).
 * Traditions differ on the list and on many locations; where one is disputed
 * we give the best-known place. Coordinates, terrain and the notes are ours.
 * Generated — do not edit by hand.
 */
export const DAKSHA = 'Sati, Daksha\'s daughter and Shiva\'s wife, gave up her body in her father\'s sacrificial fire after he insulted Shiva. Shiva carried her body in a grief-stricken dance that shook the worlds, until Vishnu\'s discus cut it apart; where each part fell, the goddess is worshipped, guarded by Shiva as a Bhairava.';

export const SHAKTI: Site[] = [
  {
    id: "kamakhya", kind: 'shakti', name: "Kamakhya", sa: "कामाख्या", place: "Guwahati (Nilachal Hill), Assam, India", lat: 26.17, lon: 91.71,
    story: "Here, where Sati's yoni (womb) fell, the goddess is worshipped as Kamakhya, guarded by Bhairava as Umananda. On the Nilachal hill above the Brahmaputra; the goddess is worshipped as a yoni-shaped stone in a cave, kept wet by a spring. Each June the temple shuts for the Ambubachi Mela, when she is held to be in her monthly course.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "nagara", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Kamakhya.",count: 10,item: "hibiscus"},
    peetha: { part: "Yoni (womb)", shakti: "Kamakhya", bhairava: "Umananda" },
  },
  {
    id: "kalighat", kind: 'shakti', name: "Kalighat", sa: "कालीघाट", place: "Kolkata, West Bengal, India", lat: 22.52, lon: 88.34,
    story: "Here, where Sati's right toes fell, the goddess is worshipped as Kali, guarded by Bhairava as Nakuleshwar. On an old channel of the Ganga that gave Calcutta its name; the present temple was built in 1809.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "city", style: "bengal", difficulty: 1,
    task: {kind: "bells",title: "Aarti at Kalighat",detail: "Ring the bells for Kali's evening aarti.",count: 10},
    peetha: { part: "Right toes", shakti: "Kali", bhairava: "Nakuleshwar" },
  },
  {
    id: "vimala-puri", kind: 'shakti', name: "Vimala", sa: "विमला", place: "Puri (Jagannath temple), Odisha, India", lat: 19.805, lon: 85.818,
    story: "Here, where Sati's feet fell, the goddess is worshipped as Vimala, guarded by Bhairava as Jagannath. Inside the Jagannath temple compound; food offered to Jagannath becomes mahaprasad only after it is offered to Vimala.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "coast", style: "kalinga", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Vimala.",count: 8,item: "hibiscus"},
    peetha: { part: "Feet", shakti: "Vimala", bhairava: "Jagannath" },
  },
  {
    id: "sugandha", kind: 'shakti', name: "Sugandha", sa: "सुगन्धा", place: "Shikarpur, Barisal, Bangladesh", lat: 22.84, lon: 90.22,
    story: "Here, where Sati's nose fell, the goddess is worshipped as Sugandha, guarded by Bhairava as Trayambaka. On the Sunanda river near Barisal in Bangladesh.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Sugandha.",count: 10,item: "hibiscus"},
    peetha: { part: "Nose", shakti: "Sugandha", bhairava: "Trayambaka" },
  },
  {
    id: "mahamaya-amarnath", kind: 'shakti', name: "Mahamaya (Amarnath)", sa: "महामाया (अमरनाथ)", place: "Amarnath / Shri Parvat, Jammu & Kashmir, India", lat: 34.215, lon: 75.505,
    story: "Here, where Sati's throat fell, the goddess is worshipped as Mahamaya, guarded by Bhairava as Trisandhyeshwar. The goddess is worshipped in the Amarnath cave beside the ice linga.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "snow", style: "cave", difficulty: 5,
    task: {kind: "trek",title: "To the cave of Mahamaya",detail: "Climb through the snow to the cave.",count: 7},
    peetha: { part: "Throat", shakti: "Mahamaya", bhairava: "Trisandhyeshwar" },
  },
  {
    id: "attahas", kind: 'shakti', name: "Attahas (Phullara)", sa: "अट्टहास (फुल्लरा)", place: "Birbhum, West Bengal, India", lat: 23.64, lon: 87.98,
    story: "Here, where Sati's lips fell, the goddess is worshipped as Phullara, guarded by Bhairava as Vishvesh. By the Ishani river in Birbhum.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Phullara.",count: 8,item: "hibiscus"},
    peetha: { part: "Lips", shakti: "Phullara", bhairava: "Vishvesh" },
  },
  {
    id: "bahula", kind: 'shakti', name: "Bahula", sa: "बहुला", place: "Ketugram, Purba Bardhaman, West Bengal, India", lat: 23.7, lon: 88.04,
    story: "Here, where Sati's left arm fell, the goddess is worshipped as Bahula, guarded by Bhairava as Bhiruk. At Ketugram on the Ajay river.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Bahula.",count: 8,item: "hibiscus"},
    peetha: { part: "Left arm", shakti: "Bahula", bhairava: "Bhiruk" },
  },
  {
    id: "bakreshwar", kind: 'shakti', name: "Bakreshwar", sa: "बक्रेश्वर", place: "Birbhum, West Bengal, India", lat: 23.88, lon: 87.38,
    story: "Here, where Sati's between the eyebrows fell, the goddess is worshipped as Mahishamardini, guarded by Bhairava as Vakranath. Known for its hot springs, said to have risen with the goddess.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "bengal", difficulty: 2,
    task: {kind: "water",title: "The hot springs",detail: "Carry water from the hot springs to the shrine.",count: 5,item: "pot"},
    peetha: { part: "Between the eyebrows", shakti: "Mahishamardini", bhairava: "Vakranath" },
  },
  {
    id: "bhabanipur", kind: 'shakti', name: "Bhabanipur (Aparna)", sa: "भवानीपुर (अपर्णा)", place: "Karatoya river, Rajshahi, Bangladesh", lat: 24.79, lon: 89.43,
    story: "Here, where Sati's left anklet fell, the goddess is worshipped as Aparna, guarded by Bhairava as Vaman. Near the Karatoya river in Bangladesh.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Aparna.",count: 10,item: "hibiscus"},
    peetha: { part: "Left anklet", shakti: "Aparna", bhairava: "Vaman" },
  },
  {
    id: "biraja", kind: 'shakti', name: "Biraja (Girija)", sa: "विरजा (गिरिजा)", place: "Jajpur, Odisha, India", lat: 20.85, lon: 86.33,
    story: "Here, where Sati's navel fell, the goddess is worshipped as Biraja, guarded by Bhairava as Varah (Jagannath). At Jajpur, on the Baitarani; the goddess is two-armed, spearing Mahisha.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "kalinga", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Biraja.",count: 8,item: "hibiscus"},
    peetha: { part: "Navel", shakti: "Biraja", bhairava: "Varah (Jagannath)" },
  },
  {
    id: "mithila", kind: 'shakti', name: "Mithila", sa: "मिथिला", place: "Near Janakpur (India–Nepal border), Nepal / Bihar", lat: 26.73, lon: 85.92,
    story: "Here, where Sati's left shoulder fell, the goddess is worshipped as Uma, guarded by Bhairava as Mahodar. Near Janakpur, Sita's birthplace, on the India–Nepal border.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Uma.",count: 8,item: "hibiscus"},
    peetha: { part: "Left shoulder", shakti: "Uma", bhairava: "Mahodar" },
  },
  {
    id: "manas-kathmandu", kind: 'shakti', name: "Manas (Kathmandu)", sa: "मानस (काठमांडू)", place: "Kathmandu, Nepal", lat: 27.72, lon: 85.31,
    story: "Here, where Sati's both knees fell, the goddess is worshipped as Mahashira (Dakshayani), guarded by Bhairava as Kapali. In the Kathmandu valley.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "city", style: "pagoda", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Mahashira (Dakshayani).",count: 10,item: "hibiscus"},
    peetha: { part: "Both knees", shakti: "Mahashira (Dakshayani)", bhairava: "Kapali" },
  },
  {
    id: "guhyeshwari", kind: 'shakti', name: "Guhyeshwari", sa: "गुह्येश्वरी", place: "Kathmandu (near Pashupatinath), Nepal", lat: 27.71, lon: 85.355,
    story: "Here, where Sati's both knees (varies) fell, the goddess is worshipped as Guhyakali, guarded by Bhairava as Kapali. On the Bagmati a few hundred metres from Pashupatinath; the goddess is worshipped as a sacred pool.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "pagoda", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Guhyakali.",count: 10,item: "hibiscus"},
    peetha: { part: "Both knees (varies)", shakti: "Guhyakali", bhairava: "Kapali" },
  },
  {
    id: "gandaki", kind: 'shakti', name: "Gandaki Chandi", sa: "गण्डकी चण्डी", place: "Muktinath, Gandaki river, Nepal", lat: 28.82, lon: 83.87,
    story: "Here, where Sati's cheek / temple fell, the goddess is worshipped as Gandaki Chandi, guarded by Bhairava as Chakrapani. At Muktinath (3,710 m), where 108 spouts pour cold water; the Gandaki carries the shaligram stones.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "snow", style: "pagoda", difficulty: 4,
    task: {kind: "trek",title: "Up to Muktinath",detail: "Climb the Kali Gandaki valley to the 108 spouts.",count: 6},
    peetha: { part: "Cheek / temple", shakti: "Gandaki Chandi", bhairava: "Chakrapani" },
  },
  {
    id: "saptashrungi", kind: 'shakti', name: "Saptashrungi", sa: "सप्तशृंगी", place: "Vani, Nashik, Maharashtra, India", lat: 20.39, lon: 73.91,
    story: "Here, where Sati's chin fell, the goddess is worshipped as Saptashrungi (Bhadrakali), guarded by Bhairava as Vikritaksha. On a hill of seven peaks near Nashik; some 500 steps climb to the eighteen-armed goddess carved in the rock.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "hemadpanti", difficulty: 3,
    task: {kind: "trek",title: "Seven peaks",detail: "Climb the steps to the goddess of the seven peaks.",count: 4},
    peetha: { part: "Chin", shakti: "Saptashrungi (Bhadrakali)", bhairava: "Vikritaksha" },
  },
  {
    id: "hinglaj", kind: 'shakti', name: "Hinglaj", sa: "हिंगलाज", place: "Hingol, Balochistan, Pakistan", lat: 25.51, lon: 65.52,
    story: "Here, where Sati's brahmarandhra (crown of head) fell, the goddess is worshipped as Hinglaj (Kottari), guarded by Bhairava as Bhimalochan. In a cave in the Hingol valley in Balochistan, reached across mud volcanoes and desert; local Muslims call her Nani and make the pilgrimage too.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "desert", style: "cave", difficulty: 4,
    task: {kind: "trek",title: "Across the Hingol",detail: "Cross the desert and the mud volcanoes to Nani's cave.",count: 6},
    peetha: { part: "Brahmarandhra (crown of head)", shakti: "Hinglaj (Kottari)", bhairava: "Bhimalochan" },
  },
  {
    id: "kankalitala", kind: 'shakti', name: "Kankalitala", sa: "कंकालीतला", place: "Birbhum (Kopai river), West Bengal, India", lat: 23.72, lon: 87.73,
    story: "Here, where Sati's waist (pelvis) fell, the goddess is worshipped as Devagarbha, guarded by Bhairava as Ruru. On the Kopai river near Bolpur; the waist is said to lie in a pool here.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Devagarbha.",count: 8,item: "hibiscus"},
    peetha: { part: "Waist (pelvis)", shakti: "Devagarbha", bhairava: "Ruru" },
  },
  {
    id: "kanyakumari", kind: 'shakti', name: "Kanyakumari", sa: "कन्याकुमारी", place: "Kanyakumari, Tamil Nadu, India", lat: 8.08, lon: 77.55,
    story: "Here, where Sati's back fell, the goddess is worshipped as Sarvani (Kanyakumari), guarded by Bhairava as Nimish. At the tip of India where three seas meet; the goddess is a girl waiting, with a garland, to marry Shiva.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "coast", style: "dravida", difficulty: 1,
    task: {kind: "lamps",title: "Where three seas meet",detail: "Light lamps along the shore at sunset.",count: 10,item: "lamp"},
    peetha: { part: "Back", shakti: "Sarvani (Kanyakumari)", bhairava: "Nimish" },
  },
  {
    id: "bajreshwari", kind: 'shakti', name: "Bajreshwari (Kangra)", sa: "बज्रेश्वरी (कांगड़ा)", place: "Kangra, Himachal Pradesh, India", lat: 32.1, lon: 76.27,
    story: "Here, where Sati's left breast fell, the goddess is worshipped as Jayadurga, guarded by Bhairava as Abhiru. At Kangra; destroyed in the 1905 earthquake and rebuilt.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "himalayan", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Jayadurga.",count: 10,item: "hibiscus"},
    peetha: { part: "Left breast", shakti: "Jayadurga", bhairava: "Abhiru" },
  },
  {
    id: "kiriteswari", kind: 'shakti', name: "Kiriteswari", sa: "किरीटेश्वरी", place: "Kiritkona, Murshidabad, West Bengal, India", lat: 24.23, lon: 88.26,
    story: "Here, where Sati's crown (kirita) fell, the goddess is worshipped as Vimala (Kiriteshwari), guarded by Bhairava as Sanvarta. In Murshidabad; called the oldest temple in the district.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Vimala (Kiriteshwari).",count: 8,item: "hibiscus"},
    peetha: { part: "Crown (kirita)", shakti: "Vimala (Kiriteshwari)", bhairava: "Sanvarta" },
  },
  {
    id: "ratnavali", kind: 'shakti', name: "Ratnavali", sa: "रत्नावली", place: "Khanakul, Hooghly, West Bengal, India", lat: 22.72, lon: 87.93,
    story: "Here, where Sati's right shoulder fell, the goddess is worshipped as Kumari, guarded by Bhairava as Ghanteshwar. At Khanakul on the Kana Damodar.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Kumari.",count: 8,item: "hibiscus"},
    peetha: { part: "Right shoulder", shakti: "Kumari", bhairava: "Ghanteshwar" },
  },
  {
    id: "bhramari-jalpaiguri", kind: 'shakti', name: "Bhramari (Jalpesh)", sa: "भ्रामरी (जल्पेश)", place: "Jalpaiguri (Teesta river), West Bengal, India", lat: 26.52, lon: 88.86,
    story: "Here, where Sati's left leg fell, the goddess is worshipped as Bhramari, guarded by Bhairava as Ambar. On the Teesta near Jalpaiguri.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Bhramari.",count: 10,item: "hibiscus"},
    peetha: { part: "Left leg", shakti: "Bhramari", bhairava: "Ambar" },
  },
  {
    id: "manasa-kailash", kind: 'shakti', name: "Manasa (Kailash)", sa: "मानस (कैलाश)", place: "Lake Manasarovar, Mt Kailash, Tibet (China)", lat: 30.66, lon: 81.47,
    story: "Here, where Sati's right hand fell, the goddess is worshipped as Dakshayani, guarded by Bhairava as Amar. Lake Manasarovar at the foot of Kailash (4,590 m), made first in Brahma's mind; the goddess is the lake itself.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "snow", style: "natural", difficulty: 5,
    task: {kind: "trek",title: "Round Manasarovar",detail: "Walk the lake's parikrama in the thin air.",count: 7},
    peetha: { part: "Right hand", shakti: "Dakshayani", bhairava: "Amar" },
  },
  {
    id: "ugratara-mahishi", kind: 'shakti', name: "Ugratara (Mahishi)", sa: "उग्रतारा (महिषी)", place: "Mahishi, Saharsa, Bihar, India", lat: 25.85, lon: 86.47,
    story: "Here, where Sati's left eye fell, the goddess is worshipped as Tara (Ugratara). At Mahishi near Saharsa, a centre of Tantric worship.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Tara (Ugratara).",count: 8,item: "hibiscus"},
    peetha: { part: "Left eye", shakti: "Tara (Ugratara)", bhairava: "" },
  },
  {
    id: "gayatri-manibandh", kind: 'shakti', name: "Gayatri (Manibandh)", sa: "गायत्री (मणिबन्ध)", place: "Pushkar (Gayatri hill), Rajasthan, India", lat: 26.49, lon: 74.55,
    story: "Here, where Sati's wrists fell, the goddess is worshipped as Gayatri, guarded by Bhairava as Sarvananda. On the Gayatri hill above Pushkar.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "desert", style: "nagara", difficulty: 2,
    task: {kind: "trek",title: "Up the Gayatri hill",detail: "Climb from Pushkar lake to the hill shrine.",count: 3},
    peetha: { part: "Wrists", shakti: "Gayatri", bhairava: "Sarvananda" },
  },
  {
    id: "indrakshi", kind: 'shakti', name: "Indrakshi (Nainativu)", sa: "इन्द्राक्षी (नैनातीवु)", place: "Nainativu island, Sri Lanka", lat: 9.62, lon: 79.77,
    story: "Here, where Sati's anklets fell, the goddess is worshipped as Indrakshi, guarded by Bhairava as Rakshasesh. The Nagapooshani Amman temple on Nainativu island off Jaffna.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "island", style: "dravida", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Indrakshi.",count: 10,item: "hibiscus"},
    peetha: { part: "Anklets", shakti: "Indrakshi", bhairava: "Rakshasesh" },
  },
  {
    id: "jayanti-nartiang", kind: 'shakti', name: "Jayanti (Nartiang)", sa: "जयन्ती (नर्तियांग)", place: "Nartiang, Jaintia Hills, Meghalaya, India", lat: 25.58, lon: 92.18,
    story: "Here, where Sati's left thigh fell, the goddess is worshipped as Jayanti, guarded by Bhairava as Kramadishwar. In the Jaintia Hills, near a field of standing monoliths raised by the Jaintia kings.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "modern", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Jayanti.",count: 10,item: "hibiscus"},
    peetha: { part: "Left thigh", shakti: "Jayanti", bhairava: "Kramadishwar" },
  },
  {
    id: "jeshoreshwari", kind: 'shakti', name: "Jeshoreshwari", sa: "जशोरेश्वरी", place: "Ishwaripur, Satkhira, Bangladesh", lat: 22.35, lon: 89.08,
    story: "Here, where Sati's palms and soles fell, the goddess is worshipped as Jeshoreshwari, guarded by Bhairava as Chanda. At Ishwaripur in Satkhira, Bangladesh.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Jeshoreshwari.",count: 8,item: "hibiscus"},
    peetha: { part: "Palms and soles", shakti: "Jeshoreshwari", bhairava: "Chanda" },
  },
  {
    id: "jwalamukhi", kind: 'shakti', name: "Jwalamukhi (Jwala Ji)", sa: "ज्वालामुखी (ज्वाला जी)", place: "Kangra, Himachal Pradesh, India", lat: 31.88, lon: 76.32,
    story: "Here, where Sati's tongue fell, the goddess is worshipped as Siddhida (Ambika), guarded by Bhairava as Unmatta. There is no image: the goddess is a set of natural flames that burn from the rock, fed by a gas seep, and have never been put out.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "himalayan", difficulty: 2,
    task: {kind: "lamps",title: "The eternal flames",detail: "Keep the nine flames burning.",count: 9,item: "lamp"},
    peetha: { part: "Tongue", shakti: "Siddhida (Ambika)", bhairava: "Unmatta" },
  },
  {
    id: "panchsagar", kind: 'shakti', name: "Panchsagar", sa: "पंचसागर", place: "Varanasi, Uttar Pradesh, India", lat: 25.3, lon: 83,
    story: "Here, where Sati's lower teeth fell, the goddess is worshipped as Varahi, guarded by Bhairava as Maharudra. In Varanasi.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Varahi.",count: 8,item: "hibiscus"},
    peetha: { part: "Lower teeth", shakti: "Varahi", bhairava: "Maharudra" },
  },
  {
    id: "prabhas-chandrabhaga", kind: 'shakti', name: "Prabhas (Chandrabhaga)", sa: "प्रभास (चन्द्रभागा)", place: "Prabhas Patan, near Somnath, Gujarat, India", lat: 20.895, lon: 70.405,
    story: "Here, where Sati's stomach fell, the goddess is worshipped as Chandrabhaga, guarded by Bhairava as Vakratunda. At Prabhas Patan, near Somnath.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "coast", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Chandrabhaga.",count: 8,item: "hibiscus"},
    peetha: { part: "Stomach", shakti: "Chandrabhaga", bhairava: "Vakratunda" },
  },
  {
    id: "lalita-prayag", kind: 'shakti', name: "Lalita (Alopi)", sa: "ललिता (अलोपी)", place: "Prayagraj (Sangam), Uttar Pradesh, India", lat: 25.44, lon: 81.86,
    story: "Here, where Sati's fingers fell, the goddess is worshipped as Lalita (Madhaveshwari), guarded by Bhairava as Bhava. At the Alopi Devi temple near the Sangam, where there is no image — the goddess is worshipped as a wooden cradle, a doli.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "nagara", difficulty: 1,
    task: {kind: "water",title: "At the Sangam",detail: "Carry water from where the Ganga and Yamuna meet.",count: 4,item: "pot"},
    peetha: { part: "Fingers", shakti: "Lalita (Madhaveshwari)", bhairava: "Bhava" },
  },
  {
    id: "bhadrakali-kurukshetra", kind: 'shakti', name: "Bhadrakali (Kurukshetra)", sa: "भद्रकाली (कुरुक्षेत्र)", place: "Thanesar, Kurukshetra, Haryana, India", lat: 29.97, lon: 76.83,
    story: "Here, where Sati's ankle fell, the goddess is worshipped as Savitri (Bhadrakali), guarded by Bhairava as Sthanu. In Kurukshetra, where, tradition says, the Pandavas prayed before the war.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Savitri (Bhadrakali).",count: 8,item: "hibiscus"},
    peetha: { part: "Ankle", shakti: "Savitri (Bhadrakali)", bhairava: "Sthanu" },
  },
  {
    id: "sharada-maihar", kind: 'shakti', name: "Sharada (Maihar)", sa: "शारदा (मैहर)", place: "Maihar (Trikut hill), Madhya Pradesh, India", lat: 24.27, lon: 80.75,
    story: "Here, where Sati's necklace (hara) fell, the goddess is worshipped as Sharada. On the Trikut hill above Maihar, up 1,063 steps.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "nagara", difficulty: 3,
    task: {kind: "trek",title: "1,063 steps",detail: "Climb the Trikut hill to Sharada.",count: 4},
    peetha: { part: "Necklace (hara)", shakti: "Sharada", bhairava: "" },
  },
  {
    id: "nandikeshwari", kind: 'shakti', name: "Nandikeshwari", sa: "नन्दिकेश्वरी", place: "Sainthia, Birbhum, West Bengal, India", lat: 23.95, lon: 87.68,
    story: "Here, where Sati's necklace fell, the goddess is worshipped as Nandini, guarded by Bhairava as Nandikeshwar. At Sainthia in Birbhum.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Nandini.",count: 8,item: "hibiscus"},
    peetha: { part: "Necklace", shakti: "Nandini", bhairava: "Nandikeshwar" },
  },
  {
    id: "manikyamba", kind: 'shakti', name: "Manikyamba (Draksharamam)", sa: "माणिक्याम्बा (द्राक्षारामम्)", place: "Draksharamam, Andhra Pradesh, India", lat: 16.79, lon: 82.065,
    story: "Here, where Sati's left cheek fell, the goddess is worshipped as Manikyamba, guarded by Bhairava as Bhimeshwar. Beside Bhimeshwara at Draksharama.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "dravida", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Manikyamba.",count: 8,item: "hibiscus"},
    peetha: { part: "Left cheek", shakti: "Manikyamba", bhairava: "Bhimeshwar" },
  },
  {
    id: "naina-devi", kind: 'shakti', name: "Mahishamardini (Naina Devi)", sa: "महिषमर्दिनी (नैना देवी)", place: "Naina Devi, Bilaspur, Himachal Pradesh, India", lat: 31.31, lon: 76.53,
    story: "Here, where Sati's eyes fell, the goddess is worshipped as Mahishamardini (Naina), guarded by Bhairava as Krodhish. On a hilltop above the Gobind Sagar lake.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "himalayan", difficulty: 3,
    task: {kind: "trek",title: "Naina Devi hill",detail: "Climb to the hilltop shrine.",count: 4},
    peetha: { part: "Eyes", shakti: "Mahishamardini (Naina)", bhairava: "Krodhish" },
  },
  {
    id: "narmada-shondesh", kind: 'shakti', name: "Narmada (Shondesh)", sa: "नर्मदा (शोणदेश)", place: "Amarkantak, Madhya Pradesh, India", lat: 22.67, lon: 81.75,
    story: "Here, where Sati's right buttock fell, the goddess is worshipped as Narmada, guarded by Bhairava as Bhadrasen. At Amarkantak, where the Narmada rises.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "forest", style: "nagara", difficulty: 2,
    task: {kind: "water",title: "The source of the Narmada",detail: "Carry water from the Narmada kund.",count: 5,item: "pot"},
    peetha: { part: "Right buttock", shakti: "Narmada", bhairava: "Bhadrasen" },
  },
  {
    id: "bhramaramba", kind: 'shakti', name: "Bhramaramba (Srisailam)", sa: "भ्रमराम्बा (श्रीशैलम्)", place: "Srisailam, Andhra Pradesh, India", lat: 16.075, lon: 78.875,
    story: "Here, where Sati's neck fell, the goddess is worshipped as Bhramarambika, guarded by Bhairava as Mallikarjuna. On the Srisailam hill beside Mallikarjuna; as a swarm of bees she killed the demon Arunasura.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "dravida", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Bhramarambika.",count: 10,item: "hibiscus"},
    peetha: { part: "Neck", shakti: "Bhramarambika", bhairava: "Mallikarjuna" },
  },
  {
    id: "narayani-suchindram", kind: 'shakti', name: "Narayani (Suchindram)", sa: "नारायणी (सुचीन्द्रम्)", place: "Suchindram, Tamil Nadu, India", lat: 8.15, lon: 77.47,
    story: "Here, where Sati's upper teeth fell, the goddess is worshipped as Narayani, guarded by Bhairava as Sanhar. At Suchindram, known for its musical pillars.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "city", style: "dravida", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Narayani.",count: 8,item: "hibiscus"},
    peetha: { part: "Upper teeth", shakti: "Narayani", bhairava: "Sanhar" },
  },
  {
    id: "tripura-sundari", kind: 'shakti', name: "Tripura Sundari (Udaipur)", sa: "त्रिपुर सुन्दरी (उदयपुर)", place: "Udaipur, Tripura, Tripura, India", lat: 23.51, lon: 91.5,
    story: "Here, where Sati's right foot fell, the goddess is worshipped as Tripura Sundari, guarded by Bhairava as Tripuresh. At Udaipur, Tripura, on a hill shaped like a tortoise.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "hills", style: "bengal", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Tripura Sundari.",count: 10,item: "hibiscus"},
    peetha: { part: "Right foot", shakti: "Tripura Sundari", bhairava: "Tripuresh" },
  },
  {
    id: "ujaani", kind: 'shakti', name: "Ujaani (Mangal Chandika)", sa: "उज्जानी (मंगल चण्डिका)", place: "Guskara, Purba Bardhaman, West Bengal, India", lat: 23.49, lon: 87.75,
    story: "Here, where Sati's right wrist fell, the goddess is worshipped as Mangal Chandika, guarded by Bhairava as Kapilambar. At Guskara in Purba Bardhaman.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Mangal Chandika.",count: 8,item: "hibiscus"},
    peetha: { part: "Right wrist", shakti: "Mangal Chandika", bhairava: "Kapilambar" },
  },
  {
    id: "vishalakshi", kind: 'shakti', name: "Vishalakshi (Varanasi)", sa: "विशालाक्षी (वाराणसी)", place: "Varanasi (Manikarnika), Uttar Pradesh, India", lat: 25.31, lon: 83.012,
    story: "Here, where Sati's earring (manikarnika) fell, the goddess is worshipped as Vishalakshi, guarded by Bhairava as Kala Bhairava. In Varanasi near Manikarnika ghat, where the earring fell.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "nagara", difficulty: 1,
    task: {kind: "water",title: "Manikarnika",detail: "Carry Ganga water from Manikarnika ghat.",count: 4,item: "pot"},
    peetha: { part: "Earring (manikarnika)", shakti: "Vishalakshi", bhairava: "Kala Bhairava" },
  },
  {
    id: "vibhash-bargabhima", kind: 'shakti', name: "Vibhash (Bargabhima)", sa: "विभाष (वर्गभीमा)", place: "Tamluk, Purba Medinipur, West Bengal, India", lat: 22.3, lon: 87.92,
    story: "Here, where Sati's left ankle fell, the goddess is worshipped as Kapalini (Bhimarupa), guarded by Bhairava as Sarvananda. At Tamluk, the ancient port of Tamralipta.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "river", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Kapalini (Bhimarupa).",count: 8,item: "hibiscus"},
    peetha: { part: "Left ankle", shakti: "Kapalini (Bhimarupa)", bhairava: "Sarvananda" },
  },
  {
    id: "ambika-bharatpur", kind: 'shakti', name: "Ambika (Virat)", sa: "अम्बिका (विराट)", place: "Bharatpur (Virat region), Rajasthan, India", lat: 27.41, lon: 76.17,
    story: "Here, where Sati's left foot toes fell, the goddess is worshipped as Ambika, guarded by Bhairava as Amriteshwar. In the Virat (Bairat) region, the ancient Matsya kingdom.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "desert", style: "nagara", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Ambika.",count: 10,item: "hibiscus"},
    peetha: { part: "Left foot toes", shakti: "Ambika", bhairava: "Amriteshwar" },
  },
  {
    id: "katyayani-vrindavan", kind: 'shakti', name: "Katyayani (Vrindavan)", sa: "कात्यायनी (वृन्दावन)", place: "Vrindavan, Uttar Pradesh, India", lat: 27.585, lon: 77.705,
    story: "Here, where Sati's ringlets of hair fell, the goddess is worshipped as Katyayani (Uma), guarded by Bhairava as Bhuteshwar. In Vrindavan, where the gopis prayed to Katyayani for Krishna as a husband.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "forest", style: "haveli", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Katyayani (Uma).",count: 8,item: "hibiscus"},
    peetha: { part: "Ringlets of hair", shakti: "Katyayani (Uma)", bhairava: "Bhuteshwar" },
  },
  {
    id: "tripuramalini-jalandhar", kind: 'shakti', name: "Tripuramalini (Jalandhar)", sa: "त्रिपुरमालिनी (जालन्धर)", place: "Jalandhar (Devi Talab), Punjab, India", lat: 31.33, lon: 75.58,
    story: "Here, where Sati's left breast fell, the goddess is worshipped as Tripuramalini, guarded by Bhairava as Bhishan. At the Devi Talab temple in Jalandhar.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "city", style: "nagara", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Tripuramalini.",count: 8,item: "hibiscus"},
    peetha: { part: "Left breast", shakti: "Tripuramalini", bhairava: "Bhishan" },
  },
  {
    id: "jayadurga-deoghar", kind: 'shakti', name: "Jayadurga (Baidyanath)", sa: "जयदुर्गा (बैद्यनाथ)", place: "Deoghar, Jharkhand, India", lat: 24.495, lon: 86.705,
    story: "Here, where Sati's heart fell, the goddess is worshipped as Jayadurga, guarded by Bhairava as Vaidyanath. Beside Vaidyanath in Deoghar, where Sati's heart fell.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "nagara", difficulty: 2,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Jayadurga.",count: 10,item: "hibiscus"},
    peetha: { part: "Heart", shakti: "Jayadurga", bhairava: "Vaidyanath" },
  },
  {
    id: "kamakshi-kanchi", kind: 'shakti', name: "Kamakshi (Kanchipuram)", sa: "कामाक्षी (कांचीपुरम)", place: "Kanchipuram, Tamil Nadu, India", lat: 12.84, lon: 79.7,
    story: "Here, where Sati's navel fell, the goddess is worshipped as Kamakshi, guarded by Bhairava as Ekambaranath. In Kanchipuram; the goddess sits in the posture of a yogini, and is the one Kamakshi temple in the city.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "city", style: "dravida", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Kamakshi.",count: 8,item: "hibiscus"},
    peetha: { part: "Navel", shakti: "Kamakshi", bhairava: "Ekambaranath" },
  },
  {
    id: "jogadya-khirgram", kind: 'shakti', name: "Jogadya (Khirgram)", sa: "योगाद्या (क्षीरग्राम)", place: "Khirgram, Purba Bardhaman, West Bengal, India", lat: 23.44, lon: 88,
    story: "Here, where Sati's right big toe fell, the goddess is worshipped as Jogadya, guarded by Bhairava as Ksheer Khandak. At Khirgram, where the image is kept under water and brought out once a year.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "bengal", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Jogadya.",count: 8,item: "hibiscus"},
    peetha: { part: "Right big toe", shakti: "Jogadya", bhairava: "Ksheer Khandak" },
  },
  {
    id: "puruhutika-pithapuram", kind: 'shakti', name: "Puruhutika (Pithapuram)", sa: "पुरुहूतिका (पीठापुरम)", place: "Pithapuram, Andhra Pradesh, India", lat: 17.12, lon: 82.25,
    story: "Here, where Sati's back fell, the goddess is worshipped as Puruhutika, guarded by Bhairava as Kukkuteswar. At Pithapuram, also sacred as the birthplace of Sripada Sri Vallabha.",
    source: 'Devi Bhagavata Purana 7.30; Kalika Purana; the 51 of the Pitha-nirnaya (Tantrachudamani)',
    biome: "plains", style: "dravida", difficulty: 1,
    task: {kind: "offer",title: "Red hibiscus",detail: "Gather red hibiscus and a red chunri for Puruhutika.",count: 8,item: "hibiscus"},
    peetha: { part: "Back", shakti: "Puruhutika", bhairava: "Kukkuteswar" },
  },
];
